package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Albaranes generated by hbm2java
 */
public class Albaranes implements java.io.Serializable {

	private Integer id;
	private short codcli;
	private String tipalb;
	private String seralb;
	private short ejerci;
	private int numalb;
	private Date fecalb;
	private Short totbul;
	private BigDecimal totkil;
	private BigDecimal totvol;
	private Short totpal;
	private BigDecimal imptot;
	private BigDecimal reembo;
	private String nomter;
	private String dirter;
	private String pobter;
	private Integer cpoter;
	private String codter;
	private Character inddis;
	private String observ;
	private String nomtra;
	private String serped;
	private Short ejeped;
	private Integer numped;
	private Short coddel;
	private int codtra;
	private int numexp;

	public Albaranes() {
	}

	public Albaranes(short codcli, String seralb, short ejerci, int numalb, int codtra, int numexp) {
		this.codcli = codcli;
		this.seralb = seralb;
		this.ejerci = ejerci;
		this.numalb = numalb;
		this.codtra = codtra;
		this.numexp = numexp;
	}

	public Albaranes(short codcli, String tipalb, String seralb, short ejerci, int numalb, Date fecalb, Short totbul,
			BigDecimal totkil, BigDecimal totvol, Short totpal, BigDecimal imptot, BigDecimal reembo, String nomter,
			String dirter, String pobter, Integer cpoter, String codter, Character inddis, String observ, String nomtra,
			String serped, Short ejeped, Integer numped, Short coddel, int codtra, int numexp) {
		this.codcli = codcli;
		this.tipalb = tipalb;
		this.seralb = seralb;
		this.ejerci = ejerci;
		this.numalb = numalb;
		this.fecalb = fecalb;
		this.totbul = totbul;
		this.totkil = totkil;
		this.totvol = totvol;
		this.totpal = totpal;
		this.imptot = imptot;
		this.reembo = reembo;
		this.nomter = nomter;
		this.dirter = dirter;
		this.pobter = pobter;
		this.cpoter = cpoter;
		this.codter = codter;
		this.inddis = inddis;
		this.observ = observ;
		this.nomtra = nomtra;
		this.serped = serped;
		this.ejeped = ejeped;
		this.numped = numped;
		this.coddel = coddel;
		this.codtra = codtra;
		this.numexp = numexp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public String getTipalb() {
		return this.tipalb;
	}

	public void setTipalb(String tipalb) {
		this.tipalb = tipalb;
	}

	public String getSeralb() {
		return this.seralb;
	}

	public void setSeralb(String seralb) {
		this.seralb = seralb;
	}

	public short getEjerci() {
		return this.ejerci;
	}

	public void setEjerci(short ejerci) {
		this.ejerci = ejerci;
	}

	public int getNumalb() {
		return this.numalb;
	}

	public void setNumalb(int numalb) {
		this.numalb = numalb;
	}

	public Date getFecalb() {
		return this.fecalb;
	}

	public void setFecalb(Date fecalb) {
		this.fecalb = fecalb;
	}

	public Short getTotbul() {
		return this.totbul;
	}

	public void setTotbul(Short totbul) {
		this.totbul = totbul;
	}

	public BigDecimal getTotkil() {
		return this.totkil;
	}

	public void setTotkil(BigDecimal totkil) {
		this.totkil = totkil;
	}

	public BigDecimal getTotvol() {
		return this.totvol;
	}

	public void setTotvol(BigDecimal totvol) {
		this.totvol = totvol;
	}

	public Short getTotpal() {
		return this.totpal;
	}

	public void setTotpal(Short totpal) {
		this.totpal = totpal;
	}

	public BigDecimal getImptot() {
		return this.imptot;
	}

	public void setImptot(BigDecimal imptot) {
		this.imptot = imptot;
	}

	public BigDecimal getReembo() {
		return this.reembo;
	}

	public void setReembo(BigDecimal reembo) {
		this.reembo = reembo;
	}

	public String getNomter() {
		return this.nomter;
	}

	public void setNomter(String nomter) {
		this.nomter = nomter;
	}

	public String getDirter() {
		return this.dirter;
	}

	public void setDirter(String dirter) {
		this.dirter = dirter;
	}

	public String getPobter() {
		return this.pobter;
	}

	public void setPobter(String pobter) {
		this.pobter = pobter;
	}

	public Integer getCpoter() {
		return this.cpoter;
	}

	public void setCpoter(Integer cpoter) {
		this.cpoter = cpoter;
	}

	public String getCodter() {
		return this.codter;
	}

	public void setCodter(String codter) {
		this.codter = codter;
	}

	public Character getInddis() {
		return this.inddis;
	}

	public void setInddis(Character inddis) {
		this.inddis = inddis;
	}

	public String getObserv() {
		return this.observ;
	}

	public void setObserv(String observ) {
		this.observ = observ;
	}

	public String getNomtra() {
		return this.nomtra;
	}

	public void setNomtra(String nomtra) {
		this.nomtra = nomtra;
	}

	public String getSerped() {
		return this.serped;
	}

	public void setSerped(String serped) {
		this.serped = serped;
	}

	public Short getEjeped() {
		return this.ejeped;
	}

	public void setEjeped(Short ejeped) {
		this.ejeped = ejeped;
	}

	public Integer getNumped() {
		return this.numped;
	}

	public void setNumped(Integer numped) {
		this.numped = numped;
	}

	public Short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(Short coddel) {
		this.coddel = coddel;
	}

	public int getCodtra() {
		return this.codtra;
	}

	public void setCodtra(int codtra) {
		this.codtra = codtra;
	}

	public int getNumexp() {
		return this.numexp;
	}

	public void setNumexp(int numexp) {
		this.numexp = numexp;
	}

}
