package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Articulos generated by hbm2java
 */
public class Articulos implements java.io.Serializable {

	private ArticulosId id;
	private String descri;
	private BigDecimal stkfis;
	private BigDecimal stkrsv;
	private BigDecimal pdtsrv;
	private BigDecimal stkdis;
	private BigDecimal pdtrec;
	private BigDecimal stkcar;

	public Articulos() {
	}

	public Articulos(ArticulosId id, String descri, BigDecimal stkfis, BigDecimal stkrsv, BigDecimal pdtsrv,
			BigDecimal stkdis, BigDecimal pdtrec, BigDecimal stkcar) {
		this.id = id;
		this.descri = descri;
		this.stkfis = stkfis;
		this.stkrsv = stkrsv;
		this.pdtsrv = pdtsrv;
		this.stkdis = stkdis;
		this.pdtrec = pdtrec;
		this.stkcar = stkcar;
	}

	public ArticulosId getId() {
		return this.id;
	}

	public void setId(ArticulosId id) {
		this.id = id;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public BigDecimal getStkfis() {
		return this.stkfis;
	}

	public void setStkfis(BigDecimal stkfis) {
		this.stkfis = stkfis;
	}

	public BigDecimal getStkrsv() {
		return this.stkrsv;
	}

	public void setStkrsv(BigDecimal stkrsv) {
		this.stkrsv = stkrsv;
	}

	public BigDecimal getPdtsrv() {
		return this.pdtsrv;
	}

	public void setPdtsrv(BigDecimal pdtsrv) {
		this.pdtsrv = pdtsrv;
	}

	public BigDecimal getStkdis() {
		return this.stkdis;
	}

	public void setStkdis(BigDecimal stkdis) {
		this.stkdis = stkdis;
	}

	public BigDecimal getPdtrec() {
		return this.pdtrec;
	}

	public void setPdtrec(BigDecimal pdtrec) {
		this.pdtrec = pdtrec;
	}

	public BigDecimal getStkcar() {
		return this.stkcar;
	}

	public void setStkcar(BigDecimal stkcar) {
		this.stkcar = stkcar;
	}

}
