package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

/**
 * AutenticacionUsuarios generated by hbm2java
 */
public class AutenticacionUsuarios implements java.io.Serializable {

	private Integer identificador;
	private String username;
	private String password;
	private String tipoEntidad;
	private String idEntidad;
	private Integer lastLogin;
	private Boolean loggeado;

	public AutenticacionUsuarios() {
	}

	public AutenticacionUsuarios(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public AutenticacionUsuarios(String username, String password, String tipoEntidad, String idEntidad,
			Integer lastLogin, Boolean loggeado) {
		this.username = username;
		this.password = password;
		this.tipoEntidad = tipoEntidad;
		this.idEntidad = idEntidad;
		this.lastLogin = lastLogin;
		this.loggeado = loggeado;
	}

	public Integer getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(Integer identificador) {
		this.identificador = identificador;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getTipoEntidad() {
		return this.tipoEntidad;
	}

	public void setTipoEntidad(String tipoEntidad) {
		this.tipoEntidad = tipoEntidad;
	}

	public String getIdEntidad() {
		return this.idEntidad;
	}

	public void setIdEntidad(String idEntidad) {
		this.idEntidad = idEntidad;
	}

	public Integer getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Integer lastLogin) {
		this.lastLogin = lastLogin;
	}

	public Boolean getLoggeado() {
		return this.loggeado;
	}

	public void setLoggeado(Boolean loggeado) {
		this.loggeado = loggeado;
	}

}
