package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private Integer identificador;
	private short codcli;
	private String nomcli;
	private String domcli;
	private String pobcli;
	private Integer cpocli;
	private String nomusu;
	private String passwd;

	public Clientes() {
	}

	public Clientes(short codcli) {
		this.codcli = codcli;
	}

	public Clientes(short codcli, String nomcli, String domcli, String pobcli, Integer cpocli, String nomusu,
			String passwd) {
		this.codcli = codcli;
		this.nomcli = nomcli;
		this.domcli = domcli;
		this.pobcli = pobcli;
		this.cpocli = cpocli;
		this.nomusu = nomusu;
		this.passwd = passwd;
	}

	public Integer getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(Integer identificador) {
		this.identificador = identificador;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public String getNomcli() {
		return this.nomcli;
	}

	public void setNomcli(String nomcli) {
		this.nomcli = nomcli;
	}

	public String getDomcli() {
		return this.domcli;
	}

	public void setDomcli(String domcli) {
		this.domcli = domcli;
	}

	public String getPobcli() {
		return this.pobcli;
	}

	public void setPobcli(String pobcli) {
		this.pobcli = pobcli;
	}

	public Integer getCpocli() {
		return this.cpocli;
	}

	public void setCpocli(Integer cpocli) {
		this.cpocli = cpocli;
	}

	public String getNomusu() {
		return this.nomusu;
	}

	public void setNomusu(String nomusu) {
		this.nomusu = nomusu;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

}
