package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Detallearticulos generated by hbm2java
 */
public class Detallearticulos implements java.io.Serializable {

	private DetallearticulosId id;
	private String descri;
	private BigDecimal cantid;

	public Detallearticulos() {
	}

	public Detallearticulos(DetallearticulosId id, String descri, BigDecimal cantid) {
		this.id = id;
		this.descri = descri;
		this.cantid = cantid;
	}

	public DetallearticulosId getId() {
		return this.id;
	}

	public void setId(DetallearticulosId id) {
		this.id = id;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public BigDecimal getCantid() {
		return this.cantid;
	}

	public void setCantid(BigDecimal cantid) {
		this.cantid = cantid;
	}

}
