package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Expediciones generated by hbm2java
 */
public class Expediciones implements java.io.Serializable {

	private Integer identificador;
	private int expedicion;
	private Date fecha;
	private String estado;
	private String imagen;

	public Expediciones() {
	}

	public Expediciones(int expedicion, Date fecha, String estado, String imagen) {
		this.expedicion = expedicion;
		this.fecha = fecha;
		this.estado = estado;
		this.imagen = imagen;
	}

	public Integer getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(Integer identificador) {
		this.identificador = identificador;
	}

	public int getExpedicion() {
		return this.expedicion;
	}

	public void setExpedicion(int expedicion) {
		this.expedicion = expedicion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

}
