package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

/**
 * I18nValores generated by hbm2java
 */
public class I18nValores implements java.io.Serializable {

	private Integer identificador;
	private String key;
	private String local;
	private String valor;

	public I18nValores() {
	}

	public I18nValores(String key, String local) {
		this.key = key;
		this.local = local;
	}

	public I18nValores(String key, String local, String valor) {
		this.key = key;
		this.local = local;
		this.valor = valor;
	}

	public Integer getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(Integer identificador) {
		this.identificador = identificador;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getLocal() {
		return this.local;
	}

	public void setLocal(String local) {
		this.local = local;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

}
