package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

/**
 * I18nLocales generated by hbm2java
 */
public class I18nLocales implements java.io.Serializable {

	private Integer identificador;
	private String codigo;
	private String idioma;

	public I18nLocales() {
	}

	public I18nLocales(String codigo, String idioma) {
		this.codigo = codigo;
		this.idioma = idioma;
	}

	public Integer getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(Integer identificador) {
		this.identificador = identificador;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getIdioma() {
		return this.idioma;
	}

	public void setIdioma(String idioma) {
		this.idioma = idioma;
	}

}
