package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

/**
 * I18nKeys generated by hbm2java
 */
public class I18nKeys implements java.io.Serializable {

	private Integer identificador;
	private String key;

	public I18nKeys() {
	}

	public I18nKeys(String key) {
		this.key = key;
	}

	public Integer getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(Integer identificador) {
		this.identificador = identificador;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

}
