package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

/**
 * LineaspedidoId generated by hbm2java
 */
public class LineaspedidoId implements java.io.Serializable {

	private short codcli;
	private char tipped;
	private String serped;
	private short ejeped;
	private int numped;
	private short numlin;

	public LineaspedidoId() {
	}

	public LineaspedidoId(short codcli, char tipped, String serped, short ejeped, int numped, short numlin) {
		this.codcli = codcli;
		this.tipped = tipped;
		this.serped = serped;
		this.ejeped = ejeped;
		this.numped = numped;
		this.numlin = numlin;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public char getTipped() {
		return this.tipped;
	}

	public void setTipped(char tipped) {
		this.tipped = tipped;
	}

	public String getSerped() {
		return this.serped;
	}

	public void setSerped(String serped) {
		this.serped = serped;
	}

	public short getEjeped() {
		return this.ejeped;
	}

	public void setEjeped(short ejeped) {
		this.ejeped = ejeped;
	}

	public int getNumped() {
		return this.numped;
	}

	public void setNumped(int numped) {
		this.numped = numped;
	}

	public short getNumlin() {
		return this.numlin;
	}

	public void setNumlin(short numlin) {
		this.numlin = numlin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LineaspedidoId))
			return false;
		LineaspedidoId castOther = (LineaspedidoId) other;

		return (this.getCodcli() == castOther.getCodcli()) && (this.getTipped() == castOther.getTipped())
				&& ((this.getSerped() == castOther.getSerped()) || (this.getSerped() != null
						&& castOther.getSerped() != null && this.getSerped().equals(castOther.getSerped())))
				&& (this.getEjeped() == castOther.getEjeped()) && (this.getNumped() == castOther.getNumped())
				&& (this.getNumlin() == castOther.getNumlin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodcli();
		result = 37 * result + this.getTipped();
		result = 37 * result + (getSerped() == null ? 0 : this.getSerped().hashCode());
		result = 37 * result + this.getEjeped();
		result = 37 * result + this.getNumped();
		result = 37 * result + this.getNumlin();
		return result;
	}

}
