package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Lineasalbaran generated by hbm2java
 */
public class Lineasalbaran implements java.io.Serializable {

	private LineasalbaranId id;
	private int idalb;
	private String codart;
	private BigDecimal cantid;
	private Short bultos;
	private BigDecimal kilos;
	private BigDecimal volume;
	private Short palets;
	private Date fecalb;
	private String descri;
	private Date fcaduc;
	private String lotefb;
	private String nserie;
	private String serped;
	private Short ejeped;
	private Integer numped;
	private Short linped;
	private BigDecimal precio;
	private BigDecimal dtoli1;
	private BigDecimal dtoli2;
	private Short coddel;

	public Lineasalbaran() {
	}

	public Lineasalbaran(LineasalbaranId id, int idalb, String codart) {
		this.id = id;
		this.idalb = idalb;
		this.codart = codart;
	}

	public Lineasalbaran(LineasalbaranId id, int idalb, String codart, BigDecimal cantid, Short bultos,
			BigDecimal kilos, BigDecimal volume, Short palets, Date fecalb, String descri, Date fcaduc, String lotefb,
			String nserie, String serped, Short ejeped, Integer numped, Short linped, BigDecimal precio,
			BigDecimal dtoli1, BigDecimal dtoli2, Short coddel) {
		this.id = id;
		this.idalb = idalb;
		this.codart = codart;
		this.cantid = cantid;
		this.bultos = bultos;
		this.kilos = kilos;
		this.volume = volume;
		this.palets = palets;
		this.fecalb = fecalb;
		this.descri = descri;
		this.fcaduc = fcaduc;
		this.lotefb = lotefb;
		this.nserie = nserie;
		this.serped = serped;
		this.ejeped = ejeped;
		this.numped = numped;
		this.linped = linped;
		this.precio = precio;
		this.dtoli1 = dtoli1;
		this.dtoli2 = dtoli2;
		this.coddel = coddel;
	}

	public LineasalbaranId getId() {
		return this.id;
	}

	public void setId(LineasalbaranId id) {
		this.id = id;
	}

	public int getIdalb() {
		return this.idalb;
	}

	public void setIdalb(int idalb) {
		this.idalb = idalb;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public BigDecimal getCantid() {
		return this.cantid;
	}

	public void setCantid(BigDecimal cantid) {
		this.cantid = cantid;
	}

	public Short getBultos() {
		return this.bultos;
	}

	public void setBultos(Short bultos) {
		this.bultos = bultos;
	}

	public BigDecimal getKilos() {
		return this.kilos;
	}

	public void setKilos(BigDecimal kilos) {
		this.kilos = kilos;
	}

	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	public Short getPalets() {
		return this.palets;
	}

	public void setPalets(Short palets) {
		this.palets = palets;
	}

	public Date getFecalb() {
		return this.fecalb;
	}

	public void setFecalb(Date fecalb) {
		this.fecalb = fecalb;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public Date getFcaduc() {
		return this.fcaduc;
	}

	public void setFcaduc(Date fcaduc) {
		this.fcaduc = fcaduc;
	}

	public String getLotefb() {
		return this.lotefb;
	}

	public void setLotefb(String lotefb) {
		this.lotefb = lotefb;
	}

	public String getNserie() {
		return this.nserie;
	}

	public void setNserie(String nserie) {
		this.nserie = nserie;
	}

	public String getSerped() {
		return this.serped;
	}

	public void setSerped(String serped) {
		this.serped = serped;
	}

	public Short getEjeped() {
		return this.ejeped;
	}

	public void setEjeped(Short ejeped) {
		this.ejeped = ejeped;
	}

	public Integer getNumped() {
		return this.numped;
	}

	public void setNumped(Integer numped) {
		this.numped = numped;
	}

	public Short getLinped() {
		return this.linped;
	}

	public void setLinped(Short linped) {
		this.linped = linped;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public BigDecimal getDtoli1() {
		return this.dtoli1;
	}

	public void setDtoli1(BigDecimal dtoli1) {
		this.dtoli1 = dtoli1;
	}

	public BigDecimal getDtoli2() {
		return this.dtoli2;
	}

	public void setDtoli2(BigDecimal dtoli2) {
		this.dtoli2 = dtoli2;
	}

	public Short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(Short coddel) {
		this.coddel = coddel;
	}

}
