package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Lineaspedido generated by hbm2java
 */
public class Lineaspedido implements java.io.Serializable {

	private LineaspedidoId id;
	private int idped;
	private String codart;
	private BigDecimal cantid;
	private Short bultos;
	private BigDecimal kilos;
	private BigDecimal volume;
	private BigDecimal precio;
	private BigDecimal dtoli1;
	private BigDecimal dtoli2;
	private String descri;
	private BigDecimal tipiva;
	private Character estado;
	private BigDecimal canser;
	private Short coddel;

	public Lineaspedido() {
	}

	public Lineaspedido(LineaspedidoId id, int idped, String codart) {
		this.id = id;
		this.idped = idped;
		this.codart = codart;
	}

	public Lineaspedido(LineaspedidoId id, int idped, String codart, BigDecimal cantid, Short bultos, BigDecimal kilos,
			BigDecimal volume, BigDecimal precio, BigDecimal dtoli1, BigDecimal dtoli2, String descri,
			BigDecimal tipiva, Character estado, BigDecimal canser, Short coddel) {
		this.id = id;
		this.idped = idped;
		this.codart = codart;
		this.cantid = cantid;
		this.bultos = bultos;
		this.kilos = kilos;
		this.volume = volume;
		this.precio = precio;
		this.dtoli1 = dtoli1;
		this.dtoli2 = dtoli2;
		this.descri = descri;
		this.tipiva = tipiva;
		this.estado = estado;
		this.canser = canser;
		this.coddel = coddel;
	}

	public LineaspedidoId getId() {
		return this.id;
	}

	public void setId(LineaspedidoId id) {
		this.id = id;
	}

	public int getIdped() {
		return this.idped;
	}

	public void setIdped(int idped) {
		this.idped = idped;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public BigDecimal getCantid() {
		return this.cantid;
	}

	public void setCantid(BigDecimal cantid) {
		this.cantid = cantid;
	}

	public Short getBultos() {
		return this.bultos;
	}

	public void setBultos(Short bultos) {
		this.bultos = bultos;
	}

	public BigDecimal getKilos() {
		return this.kilos;
	}

	public void setKilos(BigDecimal kilos) {
		this.kilos = kilos;
	}

	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public BigDecimal getDtoli1() {
		return this.dtoli1;
	}

	public void setDtoli1(BigDecimal dtoli1) {
		this.dtoli1 = dtoli1;
	}

	public BigDecimal getDtoli2() {
		return this.dtoli2;
	}

	public void setDtoli2(BigDecimal dtoli2) {
		this.dtoli2 = dtoli2;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public BigDecimal getTipiva() {
		return this.tipiva;
	}

	public void setTipiva(BigDecimal tipiva) {
		this.tipiva = tipiva;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public BigDecimal getCanser() {
		return this.canser;
	}

	public void setCanser(BigDecimal canser) {
		this.canser = canser;
	}

	public Short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(Short coddel) {
		this.coddel = coddel;
	}

}
