package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

/**
 * SesionItems generated by hbm2java
 */
public class SesionItems implements java.io.Serializable {

	private Integer identificador;
	private String clave;
	private String valor;
	private String sesion;

	public SesionItems() {
	}

	public SesionItems(String clave, String valor, String sesion) {
		this.clave = clave;
		this.valor = valor;
		this.sesion = sesion;
	}

	public Integer getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(Integer identificador) {
		this.identificador = identificador;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public String getSesion() {
		return this.sesion;
	}

	public void setSesion(String sesion) {
		this.sesion = sesion;
	}

}
