package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

/**
 * SesionSesiones generated by hbm2java
 */
public class SesionSesiones implements java.io.Serializable {

	private Integer identificador;
	private String nombre;
	private int timeout;
	private int inicio;

	public SesionSesiones() {
	}

	public SesionSesiones(String nombre, int timeout, int inicio) {
		this.nombre = nombre;
		this.timeout = timeout;
		this.inicio = inicio;
	}

	public Integer getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(Integer identificador) {
		this.identificador = identificador;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getTimeout() {
		return this.timeout;
	}

	public void setTimeout(int timeout) {
		this.timeout = timeout;
	}

	public int getInicio() {
		return this.inicio;
	}

	public void setInicio(int inicio) {
		this.inicio = inicio;
	}

}
