package hostingmodels;
// Generated 02-mar-2016 10:43:18 by Hibernate Tools 3.4.0.CR1

/**
 * Transportistas generated by hbm2java
 */
public class Transportistas implements java.io.Serializable {

	private Integer identificador;
	private String codigo;
	private String nombre;

	public Transportistas() {
	}

	public Transportistas(String codigo, String nombre) {
		this.codigo = codigo;
		this.nombre = nombre;
	}

	public Integer getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(Integer identificador) {
		this.identificador = identificador;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
