package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Acumovi generated by hbm2java
 */
public class Acumovi implements java.io.Serializable {

	private AcumoviId id;

	public Acumovi() {
	}

	public Acumovi(AcumoviId id) {
		this.id = id;
	}

	public AcumoviId getId() {
		return this.id;
	}

	public void setId(AcumoviId id) {
		this.id = id;
	}

}
