package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Albaran generated by hbm2java
 */
public class Albaran implements java.io.Serializable {

	private AlbaranId id;
	private Short cenfac;
	private Character serfac;
	private Short ejefac;
	private Integer numfac;
	private Character indrep;
	private Date fecalb;
	private Date fecexp;
	private Integer totbul;
	private BigDecimal totkil;
	private BigDecimal totvol;
	private BigDecimal imptot;
	private BigDecimal reembo;
	private Short ejevia;
	private Integer numvia;
	private String cloper;
	private String nomter;
	private String dirter;
	private String pobter;
	private Integer cpoter;
	private String codter;
	private Character inddis;
	private Character barrxp;
	private Short grupo;
	private BigDecimal impdis;
	private Character indedi;
	private String observ;
	private Short codtra;
	private String serped;
	private Short ejeped;
	private Integer numped;
	private Character estado;
	private Character envweb;
	private Short totpal;
	private String pobdis;
	private Integer cpodis;
	private Short ejeope;
	private Integer numope;
	private Character finope;
	private String docref;
	private Short anyexp;
	private Long numexp;
	private Date fecent;
	private String idetkt;
	private Short copias;

	public Albaran() {
	}

	public Albaran(AlbaranId id, Date fecalb) {
		this.id = id;
		this.fecalb = fecalb;
	}

	public Albaran(AlbaranId id, Short cenfac, Character serfac, Short ejefac, Integer numfac, Character indrep,
			Date fecalb, Date fecexp, Integer totbul, BigDecimal totkil, BigDecimal totvol, BigDecimal imptot,
			BigDecimal reembo, Short ejevia, Integer numvia, String cloper, String nomter, String dirter, String pobter,
			Integer cpoter, String codter, Character inddis, Character barrxp, Short grupo, BigDecimal impdis,
			Character indedi, String observ, Short codtra, String serped, Short ejeped, Integer numped,
			Character estado, Character envweb, Short totpal, String pobdis, Integer cpodis, Short ejeope,
			Integer numope, Character finope, String docref, Short anyexp, Long numexp, Date fecent, String idetkt,
			Short copias) {
		this.id = id;
		this.cenfac = cenfac;
		this.serfac = serfac;
		this.ejefac = ejefac;
		this.numfac = numfac;
		this.indrep = indrep;
		this.fecalb = fecalb;
		this.fecexp = fecexp;
		this.totbul = totbul;
		this.totkil = totkil;
		this.totvol = totvol;
		this.imptot = imptot;
		this.reembo = reembo;
		this.ejevia = ejevia;
		this.numvia = numvia;
		this.cloper = cloper;
		this.nomter = nomter;
		this.dirter = dirter;
		this.pobter = pobter;
		this.cpoter = cpoter;
		this.codter = codter;
		this.inddis = inddis;
		this.barrxp = barrxp;
		this.grupo = grupo;
		this.impdis = impdis;
		this.indedi = indedi;
		this.observ = observ;
		this.codtra = codtra;
		this.serped = serped;
		this.ejeped = ejeped;
		this.numped = numped;
		this.estado = estado;
		this.envweb = envweb;
		this.totpal = totpal;
		this.pobdis = pobdis;
		this.cpodis = cpodis;
		this.ejeope = ejeope;
		this.numope = numope;
		this.finope = finope;
		this.docref = docref;
		this.anyexp = anyexp;
		this.numexp = numexp;
		this.fecent = fecent;
		this.idetkt = idetkt;
		this.copias = copias;
	}

	public AlbaranId getId() {
		return this.id;
	}

	public void setId(AlbaranId id) {
		this.id = id;
	}

	public Short getCenfac() {
		return this.cenfac;
	}

	public void setCenfac(Short cenfac) {
		this.cenfac = cenfac;
	}

	public Character getSerfac() {
		return this.serfac;
	}

	public void setSerfac(Character serfac) {
		this.serfac = serfac;
	}

	public Short getEjefac() {
		return this.ejefac;
	}

	public void setEjefac(Short ejefac) {
		this.ejefac = ejefac;
	}

	public Integer getNumfac() {
		return this.numfac;
	}

	public void setNumfac(Integer numfac) {
		this.numfac = numfac;
	}

	public Character getIndrep() {
		return this.indrep;
	}

	public void setIndrep(Character indrep) {
		this.indrep = indrep;
	}

	public Date getFecalb() {
		return this.fecalb;
	}

	public void setFecalb(Date fecalb) {
		this.fecalb = fecalb;
	}

	public Date getFecexp() {
		return this.fecexp;
	}

	public void setFecexp(Date fecexp) {
		this.fecexp = fecexp;
	}

	public Integer getTotbul() {
		return this.totbul;
	}

	public void setTotbul(Integer totbul) {
		this.totbul = totbul;
	}

	public BigDecimal getTotkil() {
		return this.totkil;
	}

	public void setTotkil(BigDecimal totkil) {
		this.totkil = totkil;
	}

	public BigDecimal getTotvol() {
		return this.totvol;
	}

	public void setTotvol(BigDecimal totvol) {
		this.totvol = totvol;
	}

	public BigDecimal getImptot() {
		return this.imptot;
	}

	public void setImptot(BigDecimal imptot) {
		this.imptot = imptot;
	}

	public BigDecimal getReembo() {
		return this.reembo;
	}

	public void setReembo(BigDecimal reembo) {
		this.reembo = reembo;
	}

	public Short getEjevia() {
		return this.ejevia;
	}

	public void setEjevia(Short ejevia) {
		this.ejevia = ejevia;
	}

	public Integer getNumvia() {
		return this.numvia;
	}

	public void setNumvia(Integer numvia) {
		this.numvia = numvia;
	}

	public String getCloper() {
		return this.cloper;
	}

	public void setCloper(String cloper) {
		this.cloper = cloper;
	}

	public String getNomter() {
		return this.nomter;
	}

	public void setNomter(String nomter) {
		this.nomter = nomter;
	}

	public String getDirter() {
		return this.dirter;
	}

	public void setDirter(String dirter) {
		this.dirter = dirter;
	}

	public String getPobter() {
		return this.pobter;
	}

	public void setPobter(String pobter) {
		this.pobter = pobter;
	}

	public Integer getCpoter() {
		return this.cpoter;
	}

	public void setCpoter(Integer cpoter) {
		this.cpoter = cpoter;
	}

	public String getCodter() {
		return this.codter;
	}

	public void setCodter(String codter) {
		this.codter = codter;
	}

	public Character getInddis() {
		return this.inddis;
	}

	public void setInddis(Character inddis) {
		this.inddis = inddis;
	}

	public Character getBarrxp() {
		return this.barrxp;
	}

	public void setBarrxp(Character barrxp) {
		this.barrxp = barrxp;
	}

	public Short getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Short grupo) {
		this.grupo = grupo;
	}

	public BigDecimal getImpdis() {
		return this.impdis;
	}

	public void setImpdis(BigDecimal impdis) {
		this.impdis = impdis;
	}

	public Character getIndedi() {
		return this.indedi;
	}

	public void setIndedi(Character indedi) {
		this.indedi = indedi;
	}

	public String getObserv() {
		return this.observ;
	}

	public void setObserv(String observ) {
		this.observ = observ;
	}

	public Short getCodtra() {
		return this.codtra;
	}

	public void setCodtra(Short codtra) {
		this.codtra = codtra;
	}

	public String getSerped() {
		return this.serped;
	}

	public void setSerped(String serped) {
		this.serped = serped;
	}

	public Short getEjeped() {
		return this.ejeped;
	}

	public void setEjeped(Short ejeped) {
		this.ejeped = ejeped;
	}

	public Integer getNumped() {
		return this.numped;
	}

	public void setNumped(Integer numped) {
		this.numped = numped;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public Character getEnvweb() {
		return this.envweb;
	}

	public void setEnvweb(Character envweb) {
		this.envweb = envweb;
	}

	public Short getTotpal() {
		return this.totpal;
	}

	public void setTotpal(Short totpal) {
		this.totpal = totpal;
	}

	public String getPobdis() {
		return this.pobdis;
	}

	public void setPobdis(String pobdis) {
		this.pobdis = pobdis;
	}

	public Integer getCpodis() {
		return this.cpodis;
	}

	public void setCpodis(Integer cpodis) {
		this.cpodis = cpodis;
	}

	public Short getEjeope() {
		return this.ejeope;
	}

	public void setEjeope(Short ejeope) {
		this.ejeope = ejeope;
	}

	public Integer getNumope() {
		return this.numope;
	}

	public void setNumope(Integer numope) {
		this.numope = numope;
	}

	public Character getFinope() {
		return this.finope;
	}

	public void setFinope(Character finope) {
		this.finope = finope;
	}

	public String getDocref() {
		return this.docref;
	}

	public void setDocref(String docref) {
		this.docref = docref;
	}

	public Short getAnyexp() {
		return this.anyexp;
	}

	public void setAnyexp(Short anyexp) {
		this.anyexp = anyexp;
	}

	public Long getNumexp() {
		return this.numexp;
	}

	public void setNumexp(Long numexp) {
		this.numexp = numexp;
	}

	public Date getFecent() {
		return this.fecent;
	}

	public void setFecent(Date fecent) {
		this.fecent = fecent;
	}

	public String getIdetkt() {
		return this.idetkt;
	}

	public void setIdetkt(String idetkt) {
		this.idetkt = idetkt;
	}

	public Short getCopias() {
		return this.copias;
	}

	public void setCopias(Short copias) {
		this.copias = copias;
	}

}
