package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * AreasalmId generated by hbm2java
 */
public class AreasalmId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private String horizo;
	private short vertic;

	public AreasalmId() {
	}

	public AreasalmId(short codemp, short coddel, String horizo, short vertic) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.horizo = horizo;
		this.vertic = vertic;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public String getHorizo() {
		return this.horizo;
	}

	public void setHorizo(String horizo) {
		this.horizo = horizo;
	}

	public short getVertic() {
		return this.vertic;
	}

	public void setVertic(short vertic) {
		this.vertic = vertic;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AreasalmId))
			return false;
		AreasalmId castOther = (AreasalmId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& ((this.getHorizo() == castOther.getHorizo()) || (this.getHorizo() != null
						&& castOther.getHorizo() != null && this.getHorizo().equals(castOther.getHorizo())))
				&& (this.getVertic() == castOther.getVertic());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + (getHorizo() == null ? 0 : this.getHorizo().hashCode());
		result = 37 * result + this.getVertic();
		return result;
	}

}
