package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Artblocf generated by hbm2java
 */
public class Artblocf implements java.io.Serializable {

	private String codfal;

	public Artblocf() {
	}

	public Artblocf(String codfal) {
		this.codfal = codfal;
	}

	public String getCodfal() {
		return this.codfal;
	}

	public void setCodfal(String codfal) {
		this.codfal = codfal;
	}

}
