package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Artbloc generated by hbm2java
 */
public class Artbloc implements java.io.Serializable {

	private ArtblocId id;

	public Artbloc() {
	}

	public Artbloc(ArtblocId id) {
		this.id = id;
	}

	public ArtblocId getId() {
		return this.id;
	}

	public void setId(ArtblocId id) {
		this.id = id;
	}

}
