package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Artblocd generated by hbm2java
 */
public class Artblocd implements java.io.Serializable {

	private String coddup;

	public Artblocd() {
	}

	public Artblocd(String coddup) {
		this.coddup = coddup;
	}

	public String getCoddup() {
		return this.coddup;
	}

	public void setCoddup(String coddup) {
		this.coddup = coddup;
	}

}
