package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Articul generated by hbm2java
 */
public class Articul implements java.io.Serializable {

	private String codigo;
	private String dscart;
	private BigDecimal pdtser;
	private BigDecimal pdtrec;

	public Articul() {
	}

	public Articul(String codigo, String dscart) {
		this.codigo = codigo;
		this.dscart = dscart;
	}

	public Articul(String codigo, String dscart, BigDecimal pdtser, BigDecimal pdtrec) {
		this.codigo = codigo;
		this.dscart = dscart;
		this.pdtser = pdtser;
		this.pdtrec = pdtrec;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDscart() {
		return this.dscart;
	}

	public void setDscart(String dscart) {
		this.dscart = dscart;
	}

	public BigDecimal getPdtser() {
		return this.pdtser;
	}

	public void setPdtser(BigDecimal pdtser) {
		this.pdtser = pdtser;
	}

	public BigDecimal getPdtrec() {
		return this.pdtrec;
	}

	public void setPdtrec(BigDecimal pdtrec) {
		this.pdtrec = pdtrec;
	}

}
