package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Articwka generated by hbm2java
 */
public class Articwka implements java.io.Serializable {

	private ArticwkaId id;

	public Articwka() {
	}

	public Articwka(ArticwkaId id) {
		this.id = id;
	}

	public ArticwkaId getId() {
		return this.id;
	}

	public void setId(ArticwkaId id) {
		this.id = id;
	}

}
