package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Artic generated by hbm2java
 */
public class Artic implements java.io.Serializable {

	private ArticId id;

	public Artic() {
	}

	public Artic(ArticId id) {
		this.id = id;
	}

	public ArticId getId() {
		return this.id;
	}

	public void setId(ArticId id) {
		this.id = id;
	}

}
