package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ArticwkaId generated by hbm2java
 */
public class ArticwkaId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private short ejerci;
	private int numdoc;
	private String codart;
	private String descri;
	private String codbar;
	private Character indica;
	private Character ctlser;
	private Character ctlcad;
	private Character ctllot;
	private BigDecimal peso;

	public ArticwkaId() {
	}

	public ArticwkaId(short codemp, short coddel, short ejerci, int numdoc) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.ejerci = ejerci;
		this.numdoc = numdoc;
	}

	public ArticwkaId(short codemp, short coddel, short ejerci, int numdoc, String codart, String descri, String codbar,
			Character indica, Character ctlser, Character ctlcad, Character ctllot, BigDecimal peso) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.ejerci = ejerci;
		this.numdoc = numdoc;
		this.codart = codart;
		this.descri = descri;
		this.codbar = codbar;
		this.indica = indica;
		this.ctlser = ctlser;
		this.ctlcad = ctlcad;
		this.ctllot = ctllot;
		this.peso = peso;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public short getEjerci() {
		return this.ejerci;
	}

	public void setEjerci(short ejerci) {
		this.ejerci = ejerci;
	}

	public int getNumdoc() {
		return this.numdoc;
	}

	public void setNumdoc(int numdoc) {
		this.numdoc = numdoc;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public String getCodbar() {
		return this.codbar;
	}

	public void setCodbar(String codbar) {
		this.codbar = codbar;
	}

	public Character getIndica() {
		return this.indica;
	}

	public void setIndica(Character indica) {
		this.indica = indica;
	}

	public Character getCtlser() {
		return this.ctlser;
	}

	public void setCtlser(Character ctlser) {
		this.ctlser = ctlser;
	}

	public Character getCtlcad() {
		return this.ctlcad;
	}

	public void setCtlcad(Character ctlcad) {
		this.ctlcad = ctlcad;
	}

	public Character getCtllot() {
		return this.ctllot;
	}

	public void setCtllot(Character ctllot) {
		this.ctllot = ctllot;
	}

	public BigDecimal getPeso() {
		return this.peso;
	}

	public void setPeso(BigDecimal peso) {
		this.peso = peso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArticwkaId))
			return false;
		ArticwkaId castOther = (ArticwkaId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& (this.getEjerci() == castOther.getEjerci()) && (this.getNumdoc() == castOther.getNumdoc())
				&& ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
						&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())))
				&& ((this.getDescri() == castOther.getDescri()) || (this.getDescri() != null
						&& castOther.getDescri() != null && this.getDescri().equals(castOther.getDescri())))
				&& ((this.getCodbar() == castOther.getCodbar()) || (this.getCodbar() != null
						&& castOther.getCodbar() != null && this.getCodbar().equals(castOther.getCodbar())))
				&& ((this.getIndica() == castOther.getIndica()) || (this.getIndica() != null
						&& castOther.getIndica() != null && this.getIndica().equals(castOther.getIndica())))
				&& ((this.getCtlser() == castOther.getCtlser()) || (this.getCtlser() != null
						&& castOther.getCtlser() != null && this.getCtlser().equals(castOther.getCtlser())))
				&& ((this.getCtlcad() == castOther.getCtlcad()) || (this.getCtlcad() != null
						&& castOther.getCtlcad() != null && this.getCtlcad().equals(castOther.getCtlcad())))
				&& ((this.getCtllot() == castOther.getCtllot()) || (this.getCtllot() != null
						&& castOther.getCtllot() != null && this.getCtllot().equals(castOther.getCtllot())))
				&& ((this.getPeso() == castOther.getPeso()) || (this.getPeso() != null && castOther.getPeso() != null
						&& this.getPeso().equals(castOther.getPeso())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + this.getEjerci();
		result = 37 * result + this.getNumdoc();
		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		result = 37 * result + (getDescri() == null ? 0 : this.getDescri().hashCode());
		result = 37 * result + (getCodbar() == null ? 0 : this.getCodbar().hashCode());
		result = 37 * result + (getIndica() == null ? 0 : this.getIndica().hashCode());
		result = 37 * result + (getCtlser() == null ? 0 : this.getCtlser().hashCode());
		result = 37 * result + (getCtlcad() == null ? 0 : this.getCtlcad().hashCode());
		result = 37 * result + (getCtllot() == null ? 0 : this.getCtllot().hashCode());
		result = 37 * result + (getPeso() == null ? 0 : this.getPeso().hashCode());
		return result;
	}

}
