package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * ArtLin generated by hbm2java
 */
public class ArtLin implements java.io.Serializable {

	private ArtLinId id;

	public ArtLin() {
	}

	public ArtLin(ArtLinId id) {
		this.id = id;
	}

	public ArtLinId getId() {
		return this.id;
	}

	public void setId(ArtLinId id) {
		this.id = id;
	}

}
