package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ArtLinId generated by hbm2java
 */
public class ArtLinId implements java.io.Serializable {

	private String codart;
	private Integer cantid;
	private BigDecimal udsalm;
	private Short bultos;
	private BigDecimal kilos;
	private BigDecimal volume;
	private String lotefb;
	private Date fcaduc;
	private Integer norden;
	private int sublin;
	private Character seralb;
	private Integer numalb;
	private Short numlin;
	private String horizo;
	private Short vertic;
	private Character indret;

	public ArtLinId() {
	}

	public ArtLinId(int sublin) {
		this.sublin = sublin;
	}

	public ArtLinId(String codart, Integer cantid, BigDecimal udsalm, Short bultos, BigDecimal kilos, BigDecimal volume,
			String lotefb, Date fcaduc, Integer norden, int sublin, Character seralb, Integer numalb, Short numlin,
			String horizo, Short vertic, Character indret) {
		this.codart = codart;
		this.cantid = cantid;
		this.udsalm = udsalm;
		this.bultos = bultos;
		this.kilos = kilos;
		this.volume = volume;
		this.lotefb = lotefb;
		this.fcaduc = fcaduc;
		this.norden = norden;
		this.sublin = sublin;
		this.seralb = seralb;
		this.numalb = numalb;
		this.numlin = numlin;
		this.horizo = horizo;
		this.vertic = vertic;
		this.indret = indret;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public Integer getCantid() {
		return this.cantid;
	}

	public void setCantid(Integer cantid) {
		this.cantid = cantid;
	}

	public BigDecimal getUdsalm() {
		return this.udsalm;
	}

	public void setUdsalm(BigDecimal udsalm) {
		this.udsalm = udsalm;
	}

	public Short getBultos() {
		return this.bultos;
	}

	public void setBultos(Short bultos) {
		this.bultos = bultos;
	}

	public BigDecimal getKilos() {
		return this.kilos;
	}

	public void setKilos(BigDecimal kilos) {
		this.kilos = kilos;
	}

	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	public String getLotefb() {
		return this.lotefb;
	}

	public void setLotefb(String lotefb) {
		this.lotefb = lotefb;
	}

	public Date getFcaduc() {
		return this.fcaduc;
	}

	public void setFcaduc(Date fcaduc) {
		this.fcaduc = fcaduc;
	}

	public Integer getNorden() {
		return this.norden;
	}

	public void setNorden(Integer norden) {
		this.norden = norden;
	}

	public int getSublin() {
		return this.sublin;
	}

	public void setSublin(int sublin) {
		this.sublin = sublin;
	}

	public Character getSeralb() {
		return this.seralb;
	}

	public void setSeralb(Character seralb) {
		this.seralb = seralb;
	}

	public Integer getNumalb() {
		return this.numalb;
	}

	public void setNumalb(Integer numalb) {
		this.numalb = numalb;
	}

	public Short getNumlin() {
		return this.numlin;
	}

	public void setNumlin(Short numlin) {
		this.numlin = numlin;
	}

	public String getHorizo() {
		return this.horizo;
	}

	public void setHorizo(String horizo) {
		this.horizo = horizo;
	}

	public Short getVertic() {
		return this.vertic;
	}

	public void setVertic(Short vertic) {
		this.vertic = vertic;
	}

	public Character getIndret() {
		return this.indret;
	}

	public void setIndret(Character indret) {
		this.indret = indret;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArtLinId))
			return false;
		ArtLinId castOther = (ArtLinId) other;

		return ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
				&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())))
				&& ((this.getCantid() == castOther.getCantid()) || (this.getCantid() != null
						&& castOther.getCantid() != null && this.getCantid().equals(castOther.getCantid())))
				&& ((this.getUdsalm() == castOther.getUdsalm()) || (this.getUdsalm() != null
						&& castOther.getUdsalm() != null && this.getUdsalm().equals(castOther.getUdsalm())))
				&& ((this.getBultos() == castOther.getBultos()) || (this.getBultos() != null
						&& castOther.getBultos() != null && this.getBultos().equals(castOther.getBultos())))
				&& ((this.getKilos() == castOther.getKilos()) || (this.getKilos() != null
						&& castOther.getKilos() != null && this.getKilos().equals(castOther.getKilos())))
				&& ((this.getVolume() == castOther.getVolume()) || (this.getVolume() != null
						&& castOther.getVolume() != null && this.getVolume().equals(castOther.getVolume())))
				&& ((this.getLotefb() == castOther.getLotefb()) || (this.getLotefb() != null
						&& castOther.getLotefb() != null && this.getLotefb().equals(castOther.getLotefb())))
				&& ((this.getFcaduc() == castOther.getFcaduc()) || (this.getFcaduc() != null
						&& castOther.getFcaduc() != null && this.getFcaduc().equals(castOther.getFcaduc())))
				&& ((this.getNorden() == castOther.getNorden()) || (this.getNorden() != null
						&& castOther.getNorden() != null && this.getNorden().equals(castOther.getNorden())))
				&& (this.getSublin() == castOther.getSublin())
				&& ((this.getSeralb() == castOther.getSeralb()) || (this.getSeralb() != null
						&& castOther.getSeralb() != null && this.getSeralb().equals(castOther.getSeralb())))
				&& ((this.getNumalb() == castOther.getNumalb()) || (this.getNumalb() != null
						&& castOther.getNumalb() != null && this.getNumalb().equals(castOther.getNumalb())))
				&& ((this.getNumlin() == castOther.getNumlin()) || (this.getNumlin() != null
						&& castOther.getNumlin() != null && this.getNumlin().equals(castOther.getNumlin())))
				&& ((this.getHorizo() == castOther.getHorizo()) || (this.getHorizo() != null
						&& castOther.getHorizo() != null && this.getHorizo().equals(castOther.getHorizo())))
				&& ((this.getVertic() == castOther.getVertic()) || (this.getVertic() != null
						&& castOther.getVertic() != null && this.getVertic().equals(castOther.getVertic())))
				&& ((this.getIndret() == castOther.getIndret()) || (this.getIndret() != null
						&& castOther.getIndret() != null && this.getIndret().equals(castOther.getIndret())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		result = 37 * result + (getCantid() == null ? 0 : this.getCantid().hashCode());
		result = 37 * result + (getUdsalm() == null ? 0 : this.getUdsalm().hashCode());
		result = 37 * result + (getBultos() == null ? 0 : this.getBultos().hashCode());
		result = 37 * result + (getKilos() == null ? 0 : this.getKilos().hashCode());
		result = 37 * result + (getVolume() == null ? 0 : this.getVolume().hashCode());
		result = 37 * result + (getLotefb() == null ? 0 : this.getLotefb().hashCode());
		result = 37 * result + (getFcaduc() == null ? 0 : this.getFcaduc().hashCode());
		result = 37 * result + (getNorden() == null ? 0 : this.getNorden().hashCode());
		result = 37 * result + this.getSublin();
		result = 37 * result + (getSeralb() == null ? 0 : this.getSeralb().hashCode());
		result = 37 * result + (getNumalb() == null ? 0 : this.getNumalb().hashCode());
		result = 37 * result + (getNumlin() == null ? 0 : this.getNumlin().hashCode());
		result = 37 * result + (getHorizo() == null ? 0 : this.getHorizo().hashCode());
		result = 37 * result + (getVertic() == null ? 0 : this.getVertic().hashCode());
		result = 37 * result + (getIndret() == null ? 0 : this.getIndret().hashCode());
		return result;
	}

}
