package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * ArtPed generated by hbm2java
 */
public class ArtPed implements java.io.Serializable {

	private ArtPedId id;

	public ArtPed() {
	}

	public ArtPed(ArtPedId id) {
		this.id = id;
	}

	public ArtPedId getId() {
		return this.id;
	}

	public void setId(ArtPedId id) {
		this.id = id;
	}

}
