package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ArtPedId generated by hbm2java
 */
public class ArtPedId implements java.io.Serializable {

	private String codart;
	private Integer cantid;
	private BigDecimal udsalm;
	private String lotefb;
	private Date fcaduc;
	private int norden;
	private Integer udsstk;

	public ArtPedId() {
	}

	public ArtPedId(int norden) {
		this.norden = norden;
	}

	public ArtPedId(String codart, Integer cantid, BigDecimal udsalm, String lotefb, Date fcaduc, int norden,
			Integer udsstk) {
		this.codart = codart;
		this.cantid = cantid;
		this.udsalm = udsalm;
		this.lotefb = lotefb;
		this.fcaduc = fcaduc;
		this.norden = norden;
		this.udsstk = udsstk;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public Integer getCantid() {
		return this.cantid;
	}

	public void setCantid(Integer cantid) {
		this.cantid = cantid;
	}

	public BigDecimal getUdsalm() {
		return this.udsalm;
	}

	public void setUdsalm(BigDecimal udsalm) {
		this.udsalm = udsalm;
	}

	public String getLotefb() {
		return this.lotefb;
	}

	public void setLotefb(String lotefb) {
		this.lotefb = lotefb;
	}

	public Date getFcaduc() {
		return this.fcaduc;
	}

	public void setFcaduc(Date fcaduc) {
		this.fcaduc = fcaduc;
	}

	public int getNorden() {
		return this.norden;
	}

	public void setNorden(int norden) {
		this.norden = norden;
	}

	public Integer getUdsstk() {
		return this.udsstk;
	}

	public void setUdsstk(Integer udsstk) {
		this.udsstk = udsstk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArtPedId))
			return false;
		ArtPedId castOther = (ArtPedId) other;

		return ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
				&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())))
				&& ((this.getCantid() == castOther.getCantid()) || (this.getCantid() != null
						&& castOther.getCantid() != null && this.getCantid().equals(castOther.getCantid())))
				&& ((this.getUdsalm() == castOther.getUdsalm()) || (this.getUdsalm() != null
						&& castOther.getUdsalm() != null && this.getUdsalm().equals(castOther.getUdsalm())))
				&& ((this.getLotefb() == castOther.getLotefb()) || (this.getLotefb() != null
						&& castOther.getLotefb() != null && this.getLotefb().equals(castOther.getLotefb())))
				&& ((this.getFcaduc() == castOther.getFcaduc()) || (this.getFcaduc() != null
						&& castOther.getFcaduc() != null && this.getFcaduc().equals(castOther.getFcaduc())))
				&& (this.getNorden() == castOther.getNorden())
				&& ((this.getUdsstk() == castOther.getUdsstk()) || (this.getUdsstk() != null
						&& castOther.getUdsstk() != null && this.getUdsstk().equals(castOther.getUdsstk())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		result = 37 * result + (getCantid() == null ? 0 : this.getCantid().hashCode());
		result = 37 * result + (getUdsalm() == null ? 0 : this.getUdsalm().hashCode());
		result = 37 * result + (getLotefb() == null ? 0 : this.getLotefb().hashCode());
		result = 37 * result + (getFcaduc() == null ? 0 : this.getFcaduc().hashCode());
		result = 37 * result + this.getNorden();
		result = 37 * result + (getUdsstk() == null ? 0 : this.getUdsstk().hashCode());
		return result;
	}

}
