package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * ArtWka generated by hbm2java
 */
public class ArtWka implements java.io.Serializable {

	private ArtWkaId id;

	public ArtWka() {
	}

	public ArtWka(ArtWkaId id) {
		this.id = id;
	}

	public ArtWkaId getId() {
		return this.id;
	}

	public void setId(ArtWkaId id) {
		this.id = id;
	}

}
