package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ArtWkaId generated by hbm2java
 */
public class ArtWkaId implements java.io.Serializable {

	private String horizo;
	private Short vertic;
	private String codart;
	private String descri;
	private String codbar;
	private Integer cantid;
	private BigDecimal udsalm;

	public ArtWkaId() {
	}

	public ArtWkaId(String horizo, Short vertic, String codart, String descri, String codbar, Integer cantid,
			BigDecimal udsalm) {
		this.horizo = horizo;
		this.vertic = vertic;
		this.codart = codart;
		this.descri = descri;
		this.codbar = codbar;
		this.cantid = cantid;
		this.udsalm = udsalm;
	}

	public String getHorizo() {
		return this.horizo;
	}

	public void setHorizo(String horizo) {
		this.horizo = horizo;
	}

	public Short getVertic() {
		return this.vertic;
	}

	public void setVertic(Short vertic) {
		this.vertic = vertic;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public String getCodbar() {
		return this.codbar;
	}

	public void setCodbar(String codbar) {
		this.codbar = codbar;
	}

	public Integer getCantid() {
		return this.cantid;
	}

	public void setCantid(Integer cantid) {
		this.cantid = cantid;
	}

	public BigDecimal getUdsalm() {
		return this.udsalm;
	}

	public void setUdsalm(BigDecimal udsalm) {
		this.udsalm = udsalm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArtWkaId))
			return false;
		ArtWkaId castOther = (ArtWkaId) other;

		return ((this.getHorizo() == castOther.getHorizo()) || (this.getHorizo() != null
				&& castOther.getHorizo() != null && this.getHorizo().equals(castOther.getHorizo())))
				&& ((this.getVertic() == castOther.getVertic()) || (this.getVertic() != null
						&& castOther.getVertic() != null && this.getVertic().equals(castOther.getVertic())))
				&& ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
						&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())))
				&& ((this.getDescri() == castOther.getDescri()) || (this.getDescri() != null
						&& castOther.getDescri() != null && this.getDescri().equals(castOther.getDescri())))
				&& ((this.getCodbar() == castOther.getCodbar()) || (this.getCodbar() != null
						&& castOther.getCodbar() != null && this.getCodbar().equals(castOther.getCodbar())))
				&& ((this.getCantid() == castOther.getCantid()) || (this.getCantid() != null
						&& castOther.getCantid() != null && this.getCantid().equals(castOther.getCantid())))
				&& ((this.getUdsalm() == castOther.getUdsalm()) || (this.getUdsalm() != null
						&& castOther.getUdsalm() != null && this.getUdsalm().equals(castOther.getUdsalm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHorizo() == null ? 0 : this.getHorizo().hashCode());
		result = 37 * result + (getVertic() == null ? 0 : this.getVertic().hashCode());
		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		result = 37 * result + (getDescri() == null ? 0 : this.getDescri().hashCode());
		result = 37 * result + (getCodbar() == null ? 0 : this.getCodbar().hashCode());
		result = 37 * result + (getCantid() == null ? 0 : this.getCantid().hashCode());
		result = 37 * result + (getUdsalm() == null ? 0 : this.getUdsalm().hashCode());
		return result;
	}

}
