package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ArtzonaId generated by hbm2java
 */
public class ArtzonaId implements java.io.Serializable {

	private String horizo;
	private Short vertic;
	private String basalm;
	private String codart;
	private BigDecimal udsart;
	private Date fcaduc;
	private String lotefb;

	public ArtzonaId() {
	}

	public ArtzonaId(String horizo, Short vertic, String basalm, String codart, BigDecimal udsart, Date fcaduc,
			String lotefb) {
		this.horizo = horizo;
		this.vertic = vertic;
		this.basalm = basalm;
		this.codart = codart;
		this.udsart = udsart;
		this.fcaduc = fcaduc;
		this.lotefb = lotefb;
	}

	public String getHorizo() {
		return this.horizo;
	}

	public void setHorizo(String horizo) {
		this.horizo = horizo;
	}

	public Short getVertic() {
		return this.vertic;
	}

	public void setVertic(Short vertic) {
		this.vertic = vertic;
	}

	public String getBasalm() {
		return this.basalm;
	}

	public void setBasalm(String basalm) {
		this.basalm = basalm;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public BigDecimal getUdsart() {
		return this.udsart;
	}

	public void setUdsart(BigDecimal udsart) {
		this.udsart = udsart;
	}

	public Date getFcaduc() {
		return this.fcaduc;
	}

	public void setFcaduc(Date fcaduc) {
		this.fcaduc = fcaduc;
	}

	public String getLotefb() {
		return this.lotefb;
	}

	public void setLotefb(String lotefb) {
		this.lotefb = lotefb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArtzonaId))
			return false;
		ArtzonaId castOther = (ArtzonaId) other;

		return ((this.getHorizo() == castOther.getHorizo()) || (this.getHorizo() != null
				&& castOther.getHorizo() != null && this.getHorizo().equals(castOther.getHorizo())))
				&& ((this.getVertic() == castOther.getVertic()) || (this.getVertic() != null
						&& castOther.getVertic() != null && this.getVertic().equals(castOther.getVertic())))
				&& ((this.getBasalm() == castOther.getBasalm()) || (this.getBasalm() != null
						&& castOther.getBasalm() != null && this.getBasalm().equals(castOther.getBasalm())))
				&& ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
						&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())))
				&& ((this.getUdsart() == castOther.getUdsart()) || (this.getUdsart() != null
						&& castOther.getUdsart() != null && this.getUdsart().equals(castOther.getUdsart())))
				&& ((this.getFcaduc() == castOther.getFcaduc()) || (this.getFcaduc() != null
						&& castOther.getFcaduc() != null && this.getFcaduc().equals(castOther.getFcaduc())))
				&& ((this.getLotefb() == castOther.getLotefb()) || (this.getLotefb() != null
						&& castOther.getLotefb() != null && this.getLotefb().equals(castOther.getLotefb())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHorizo() == null ? 0 : this.getHorizo().hashCode());
		result = 37 * result + (getVertic() == null ? 0 : this.getVertic().hashCode());
		result = 37 * result + (getBasalm() == null ? 0 : this.getBasalm().hashCode());
		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		result = 37 * result + (getUdsart() == null ? 0 : this.getUdsart().hashCode());
		result = 37 * result + (getFcaduc() == null ? 0 : this.getFcaduc().hashCode());
		result = 37 * result + (getLotefb() == null ? 0 : this.getLotefb().hashCode());
		return result;
	}

}
