package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Artzona generated by hbm2java
 */
public class Artzona implements java.io.Serializable {

	private ArtzonaId id;

	public Artzona() {
	}

	public Artzona(ArtzonaId id) {
		this.id = id;
	}

	public ArtzonaId getId() {
		return this.id;
	}

	public void setId(ArtzonaId id) {
		this.id = id;
	}

}
