package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Bastarif generated by hbm2java
 */
public class Bastarif implements java.io.Serializable {

	private BastarifId id;

	public Bastarif() {
	}

	public Bastarif(BastarifId id) {
		this.id = id;
	}

	public BastarifId getId() {
		return this.id;
	}

	public void setId(BastarifId id) {
		this.id = id;
	}

}
