package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * BastarifId generated by hbm2java
 */
public class BastarifId implements java.io.Serializable {

	private short codemp;
	private String aplica;
	private String bastar;
	private String dscbas;

	public BastarifId() {
	}

	public BastarifId(short codemp, String aplica, String bastar) {
		this.codemp = codemp;
		this.aplica = aplica;
		this.bastar = bastar;
	}

	public BastarifId(short codemp, String aplica, String bastar, String dscbas) {
		this.codemp = codemp;
		this.aplica = aplica;
		this.bastar = bastar;
		this.dscbas = dscbas;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public String getAplica() {
		return this.aplica;
	}

	public void setAplica(String aplica) {
		this.aplica = aplica;
	}

	public String getBastar() {
		return this.bastar;
	}

	public void setBastar(String bastar) {
		this.bastar = bastar;
	}

	public String getDscbas() {
		return this.dscbas;
	}

	public void setDscbas(String dscbas) {
		this.dscbas = dscbas;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BastarifId))
			return false;
		BastarifId castOther = (BastarifId) other;

		return (this.getCodemp() == castOther.getCodemp())
				&& ((this.getAplica() == castOther.getAplica()) || (this.getAplica() != null
						&& castOther.getAplica() != null && this.getAplica().equals(castOther.getAplica())))
				&& ((this.getBastar() == castOther.getBastar()) || (this.getBastar() != null
						&& castOther.getBastar() != null && this.getBastar().equals(castOther.getBastar())))
				&& ((this.getDscbas() == castOther.getDscbas()) || (this.getDscbas() != null
						&& castOther.getDscbas() != null && this.getDscbas().equals(castOther.getDscbas())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + (getAplica() == null ? 0 : this.getAplica().hashCode());
		result = 37 * result + (getBastar() == null ? 0 : this.getBastar().hashCode());
		result = 37 * result + (getDscbas() == null ? 0 : this.getDscbas().hashCode());
		return result;
	}

}
