package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Cabfactu generated by hbm2java
 */
public class Cabfactu implements java.io.Serializable {

	private CabfactuId id;
	private Date fecfac;
	private short codcli;
	private String codter;
	private String nif;
	private String nomcli;
	private String domici;
	private String poblac;
	private Integer codpos;
	private Short pais;
	private Short provin;
	private BigDecimal impbru;
	private BigDecimal dtofac;
	private BigDecimal impdfac;
	private BigDecimal basiva;
	private BigDecimal tipiva;
	private BigDecimal impiva;
	private BigDecimal totfac;
	private String forpag;
	private Character indctb;
	private String observ;
	private boolean web;
	private boolean reducida;
	private boolean email_sent;
	private List<Linfactu> lines;

	public Cabfactu() {
	}

	public Cabfactu(CabfactuId id, short codcli) {
		this.id = id;
		this.codcli = codcli;
	}

	public Cabfactu(CabfactuId id, Date fecfac, short codcli, String codter, String nif, String nomcli, String domici,
			String poblac, Integer codpos, Short pais, Short provin, BigDecimal impbru, BigDecimal dtofac,
			BigDecimal impdfac, BigDecimal basiva, BigDecimal tipiva, BigDecimal impiva, BigDecimal totfac,
			String forpag, Character indctb, String observ) {
		this.id = id;
		this.fecfac = fecfac;
		this.codcli = codcli;
		this.codter = codter;
		this.nif = nif;
		this.nomcli = nomcli;
		this.domici = domici;
		this.poblac = poblac;
		this.codpos = codpos;
		this.pais = pais;
		this.provin = provin;
		this.impbru = impbru;
		this.dtofac = dtofac;
		this.impdfac = impdfac;
		this.basiva = basiva;
		this.tipiva = tipiva;
		this.impiva = impiva;
		this.totfac = totfac;
		this.forpag = forpag;
		this.indctb = indctb;
		this.observ = observ;
	}

	public CabfactuId getId() {
		return this.id;
	}

	public void setId(CabfactuId id) {
		this.id = id;
	}

	public Date getFecfac() {
		return this.fecfac;
	}

	public void setFecfac(Date fecfac) {
		this.fecfac = fecfac;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public String getCodter() {
		return this.codter;
	}

	public void setCodter(String codter) {
		this.codter = codter;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getNomcli() {
		return this.nomcli;
	}

	public void setNomcli(String nomcli) {
		this.nomcli = nomcli;
	}

	public String getDomici() {
		return this.domici;
	}

	public void setDomici(String domici) {
		this.domici = domici;
	}

	public String getPoblac() {
		return this.poblac;
	}

	public void setPoblac(String poblac) {
		this.poblac = poblac;
	}

	public Integer getCodpos() {
		return this.codpos;
	}

	public void setCodpos(Integer codpos) {
		this.codpos = codpos;
	}

	public Short getPais() {
		return this.pais;
	}

	public void setPais(Short pais) {
		this.pais = pais;
	}

	public Short getProvin() {
		return this.provin;
	}

	public void setProvin(Short provin) {
		this.provin = provin;
	}

	public BigDecimal getImpbru() {
		return this.impbru;
	}

	public void setImpbru(BigDecimal impbru) {
		this.impbru = impbru;
	}

	public BigDecimal getDtofac() {
		return this.dtofac;
	}

	public void setDtofac(BigDecimal dtofac) {
		this.dtofac = dtofac;
	}

	public BigDecimal getImpdfac() {
		return this.impdfac;
	}

	public void setImpdfac(BigDecimal impdfac) {
		this.impdfac = impdfac;
	}

	public BigDecimal getBasiva() {
		return this.basiva;
	}

	public void setBasiva(BigDecimal basiva) {
		this.basiva = basiva;
	}

	public BigDecimal getTipiva() {
		return this.tipiva;
	}

	public void setTipiva(BigDecimal tipiva) {
		this.tipiva = tipiva;
	}

	public BigDecimal getImpiva() {
		return this.impiva;
	}

	public void setImpiva(BigDecimal impiva) {
		this.impiva = impiva;
	}

	public BigDecimal getTotfac() {
		return this.totfac;
	}

	public void setTotfac(BigDecimal totfac) {
		this.totfac = totfac;
	}

	public String getForpag() {
		return this.forpag;
	}

	public void setForpag(String forpag) {
		this.forpag = forpag;
	}

	public Character getIndctb() {
		return this.indctb;
	}

	public void setIndctb(Character indctb) {
		this.indctb = indctb;
	}

	public String getObserv() {
		return this.observ;
	}

	public void setObserv(String observ) {
		this.observ = observ;
	}

	public boolean isWeb() {
		return web;
	}

	public void setWeb(boolean web) {
		this.web = web;
	}

	public boolean isReducida() {
		return reducida;
	}

	public void setReducida(boolean reducida) {
		this.reducida = reducida;
	}

	public List<Linfactu> getLines() {
		return lines;
	}

	public void setLines(List<Linfactu> lines) {
		this.lines = lines;
	}

	public boolean isEmail_sent() {
		return email_sent;
	}

	public void setEmail_sent(boolean email_sent) {
		this.email_sent = email_sent;
	}
	
	
	
	
	
	

}
