package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Calprefac generated by hbm2java
 */
public class Calprefac implements java.io.Serializable {

	private CalprefacId id;
	private BigDecimal udsalm;

	public Calprefac() {
	}

	public Calprefac(CalprefacId id) {
		this.id = id;
	}

	public Calprefac(CalprefacId id, BigDecimal udsalm) {
		this.id = id;
		this.udsalm = udsalm;
	}

	public CalprefacId getId() {
		return this.id;
	}

	public void setId(CalprefacId id) {
		this.id = id;
	}

	public BigDecimal getUdsalm() {
		return this.udsalm;
	}

	public void setUdsalm(BigDecimal udsalm) {
		this.udsalm = udsalm;
	}

}
