package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * ClientesId generated by hbm2java
 */
public class ClientesId implements java.io.Serializable {

	private short codemp;
	private short codcli;

	public ClientesId() {
	}

	public ClientesId(short codemp, short codcli) {
		this.codemp = codemp;
		this.codcli = codcli;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClientesId))
			return false;
		ClientesId castOther = (ClientesId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCodcli() == castOther.getCodcli());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCodcli();
		return result;
	}

}
