package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private ClientesId id;
	private String nomacc;
	private String nomcli;
	private String domcli;
	private String pobcli;
	private Integer codpos;
	private Short provin;
	private Short pais;
	private String telefo;
	private String telefx;
	private String person;
	private String cifdni;
	private String forpag;
	private String codpro;
	private char tipiva;
	private String sislog;
	private Date fecalt;
	private Date fecbaj;
	private Character serlib;
	private String serent;
	private String sersal;
	private Character autone;
	private Character autons;
	private Short copias;
	private Character tpapel;
	private String ctactb;
	private String email;

	public Clientes() {
	}

	public Clientes(ClientesId id, String nomacc, String nomcli, String domcli, String pobcli, char tipiva) {
		this.id = id;
		this.nomacc = nomacc;
		this.nomcli = nomcli;
		this.domcli = domcli;
		this.pobcli = pobcli;
		this.tipiva = tipiva;
	}

	public Clientes(ClientesId id, String nomacc, String nomcli, String domcli, String pobcli, Integer codpos,
			Short provin, Short pais, String telefo, String telefx, String person, String cifdni, String forpag,
			String codpro, char tipiva, String sislog, Date fecalt, Date fecbaj, Character serlib, String serent,
			String sersal, Character autone, Character autons, Short copias, Character tpapel, String ctactb) {
		this.id = id;
		this.nomacc = nomacc;
		this.nomcli = nomcli;
		this.domcli = domcli;
		this.pobcli = pobcli;
		this.codpos = codpos;
		this.provin = provin;
		this.pais = pais;
		this.telefo = telefo;
		this.telefx = telefx;
		this.person = person;
		this.cifdni = cifdni;
		this.forpag = forpag;
		this.codpro = codpro;
		this.tipiva = tipiva;
		this.sislog = sislog;
		this.fecalt = fecalt;
		this.fecbaj = fecbaj;
		this.serlib = serlib;
		this.serent = serent;
		this.sersal = sersal;
		this.autone = autone;
		this.autons = autons;
		this.copias = copias;
		this.tpapel = tpapel;
		this.ctactb = ctactb;
	}

	public ClientesId getId() {
		return this.id;
	}

	public void setId(ClientesId id) {
		this.id = id;
	}

	public String getNomacc() {
		return this.nomacc;
	}

	public void setNomacc(String nomacc) {
		this.nomacc = nomacc;
	}

	public String getNomcli() {
		return this.nomcli;
	}

	public void setNomcli(String nomcli) {
		this.nomcli = nomcli;
	}

	public String getDomcli() {
		return this.domcli;
	}

	public void setDomcli(String domcli) {
		this.domcli = domcli;
	}

	public String getPobcli() {
		return this.pobcli;
	}

	public void setPobcli(String pobcli) {
		this.pobcli = pobcli;
	}

	public Integer getCodpos() {
		return this.codpos;
	}

	public void setCodpos(Integer codpos) {
		this.codpos = codpos;
	}

	public Short getProvin() {
		return this.provin;
	}

	public void setProvin(Short provin) {
		this.provin = provin;
	}

	public Short getPais() {
		return this.pais;
	}

	public void setPais(Short pais) {
		this.pais = pais;
	}

	public String getTelefo() {
		return this.telefo;
	}

	public void setTelefo(String telefo) {
		this.telefo = telefo;
	}

	public String getTelefx() {
		return this.telefx;
	}

	public void setTelefx(String telefx) {
		this.telefx = telefx;
	}

	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	public String getCifdni() {
		return this.cifdni;
	}

	public void setCifdni(String cifdni) {
		this.cifdni = cifdni;
	}

	public String getForpag() {
		return this.forpag;
	}

	public void setForpag(String forpag) {
		this.forpag = forpag;
	}

	public String getCodpro() {
		return this.codpro;
	}

	public void setCodpro(String codpro) {
		this.codpro = codpro;
	}

	public char getTipiva() {
		return this.tipiva;
	}

	public void setTipiva(char tipiva) {
		this.tipiva = tipiva;
	}

	public String getSislog() {
		return this.sislog;
	}

	public void setSislog(String sislog) {
		this.sislog = sislog;
	}

	public Date getFecalt() {
		return this.fecalt;
	}

	public void setFecalt(Date fecalt) {
		this.fecalt = fecalt;
	}

	public Date getFecbaj() {
		return this.fecbaj;
	}

	public void setFecbaj(Date fecbaj) {
		this.fecbaj = fecbaj;
	}

	public Character getSerlib() {
		return this.serlib;
	}

	public void setSerlib(Character serlib) {
		this.serlib = serlib;
	}

	public String getSerent() {
		return this.serent;
	}

	public void setSerent(String serent) {
		this.serent = serent;
	}

	public String getSersal() {
		return this.sersal;
	}

	public void setSersal(String sersal) {
		this.sersal = sersal;
	}

	public Character getAutone() {
		return this.autone;
	}

	public void setAutone(Character autone) {
		this.autone = autone;
	}

	public Character getAutons() {
		return this.autons;
	}

	public void setAutons(Character autons) {
		this.autons = autons;
	}

	public Short getCopias() {
		return this.copias;
	}

	public void setCopias(Short copias) {
		this.copias = copias;
	}

	public Character getTpapel() {
		return this.tpapel;
	}

	public void setTpapel(Character tpapel) {
		this.tpapel = tpapel;
	}

	public String getCtactb() {
		return this.ctactb;
	}

	public void setCtactb(String ctactb) {
		this.ctactb = ctactb;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	

}
