package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * ClitercerId generated by hbm2java
 */
public class ClitercerId implements java.io.Serializable {

	private short codemp;
	private short codcli;
	private String codter;

	public ClitercerId() {
	}

	public ClitercerId(short codemp, short codcli, String codter) {
		this.codemp = codemp;
		this.codcli = codcli;
		this.codter = codter;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public String getCodter() {
		return this.codter;
	}

	public void setCodter(String codter) {
		this.codter = codter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClitercerId))
			return false;
		ClitercerId castOther = (ClitercerId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCodcli() == castOther.getCodcli())
				&& ((this.getCodter() == castOther.getCodter()) || (this.getCodter() != null
						&& castOther.getCodter() != null && this.getCodter().equals(castOther.getCodter())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCodcli();
		result = 37 * result + (getCodter() == null ? 0 : this.getCodter().hashCode());
		return result;
	}

}
