package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Clitercer generated by hbm2java
 */
public class Clitercer implements java.io.Serializable {

	private ClitercerId id;
	private String nomcli;
	private String domcli;
	private String pobcli;
	private Integer codpos;
	private Short provin;
	private Short pais;
	private String telefo;
	private String telefx;
	private String person;
	private Character cladis;
	private String cifdni;

	public Clitercer() {
	}

	public Clitercer(ClitercerId id, String nomcli, String domcli, String pobcli) {
		this.id = id;
		this.nomcli = nomcli;
		this.domcli = domcli;
		this.pobcli = pobcli;
	}

	public Clitercer(ClitercerId id, String nomcli, String domcli, String pobcli, Integer codpos, Short provin,
			Short pais, String telefo, String telefx, String person, Character cladis, String cifdni) {
		this.id = id;
		this.nomcli = nomcli;
		this.domcli = domcli;
		this.pobcli = pobcli;
		this.codpos = codpos;
		this.provin = provin;
		this.pais = pais;
		this.telefo = telefo;
		this.telefx = telefx;
		this.person = person;
		this.cladis = cladis;
		this.cifdni = cifdni;
	}

	public ClitercerId getId() {
		return this.id;
	}

	public void setId(ClitercerId id) {
		this.id = id;
	}

	public String getNomcli() {
		return this.nomcli;
	}

	public void setNomcli(String nomcli) {
		this.nomcli = nomcli;
	}

	public String getDomcli() {
		return this.domcli;
	}

	public void setDomcli(String domcli) {
		this.domcli = domcli;
	}

	public String getPobcli() {
		return this.pobcli;
	}

	public void setPobcli(String pobcli) {
		this.pobcli = pobcli;
	}

	public Integer getCodpos() {
		return this.codpos;
	}

	public void setCodpos(Integer codpos) {
		this.codpos = codpos;
	}

	public Short getProvin() {
		return this.provin;
	}

	public void setProvin(Short provin) {
		this.provin = provin;
	}

	public Short getPais() {
		return this.pais;
	}

	public void setPais(Short pais) {
		this.pais = pais;
	}

	public String getTelefo() {
		return this.telefo;
	}

	public void setTelefo(String telefo) {
		this.telefo = telefo;
	}

	public String getTelefx() {
		return this.telefx;
	}

	public void setTelefx(String telefx) {
		this.telefx = telefx;
	}

	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	public Character getCladis() {
		return this.cladis;
	}

	public void setCladis(Character cladis) {
		this.cladis = cladis;
	}

	public String getCifdni() {
		return this.cifdni;
	}

	public void setCifdni(String cifdni) {
		this.cifdni = cifdni;
	}

}
