package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Codigos generated by hbm2java
 */
public class Codigos implements java.io.Serializable {

	private CodigosId id;

	public Codigos() {
	}

	public Codigos(CodigosId id) {
		this.id = id;
	}

	public CodigosId getId() {
		return this.id;
	}

	public void setId(CodigosId id) {
		this.id = id;
	}

}
