package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * CodigosId generated by hbm2java
 */
public class CodigosId implements java.io.Serializable {

	private String codbar;
	private String codart;
	private String descri;
	private BigDecimal volume;
	private BigDecimal peso;

	public CodigosId() {
	}

	public CodigosId(String codbar, String codart, String descri, BigDecimal volume, BigDecimal peso) {
		this.codbar = codbar;
		this.codart = codart;
		this.descri = descri;
		this.volume = volume;
		this.peso = peso;
	}

	public String getCodbar() {
		return this.codbar;
	}

	public void setCodbar(String codbar) {
		this.codbar = codbar;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	public BigDecimal getPeso() {
		return this.peso;
	}

	public void setPeso(BigDecimal peso) {
		this.peso = peso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CodigosId))
			return false;
		CodigosId castOther = (CodigosId) other;

		return ((this.getCodbar() == castOther.getCodbar()) || (this.getCodbar() != null
				&& castOther.getCodbar() != null && this.getCodbar().equals(castOther.getCodbar())))
				&& ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
						&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())))
				&& ((this.getDescri() == castOther.getDescri()) || (this.getDescri() != null
						&& castOther.getDescri() != null && this.getDescri().equals(castOther.getDescri())))
				&& ((this.getVolume() == castOther.getVolume()) || (this.getVolume() != null
						&& castOther.getVolume() != null && this.getVolume().equals(castOther.getVolume())))
				&& ((this.getPeso() == castOther.getPeso()) || (this.getPeso() != null && castOther.getPeso() != null
						&& this.getPeso().equals(castOther.getPeso())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodbar() == null ? 0 : this.getCodbar().hashCode());
		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		result = 37 * result + (getDescri() == null ? 0 : this.getDescri().hashCode());
		result = 37 * result + (getVolume() == null ? 0 : this.getVolume().hashCode());
		result = 37 * result + (getPeso() == null ? 0 : this.getPeso().hashCode());
		return result;
	}

}
