package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * CondicTasacion generated by hbm2java
 */
public class CondicTasacion implements java.io.Serializable {

	private CondicTasacionId id;
	private Short numtar;
	private Character tipcal;
	private Character grufac;
	private Short basdia;
	private BigDecimal dtofac;
	private BigDecimal perseg;
	private BigDecimal minseg;
	private Integer equkm3;
	private String aplcge;
	private BigDecimal minser;
	private Character artlin;
	private BigDecimal valdet;

	public CondicTasacion() {
	}

	public CondicTasacion(CondicTasacionId id) {
		this.id = id;
	}

	public CondicTasacion(CondicTasacionId id, Short numtar, Character tipcal, Character grufac, Short basdia,
			BigDecimal dtofac, BigDecimal perseg, BigDecimal minseg, Integer equkm3, String aplcge, BigDecimal minser,
			Character artlin, BigDecimal valdet) {
		this.id = id;
		this.numtar = numtar;
		this.tipcal = tipcal;
		this.grufac = grufac;
		this.basdia = basdia;
		this.dtofac = dtofac;
		this.perseg = perseg;
		this.minseg = minseg;
		this.equkm3 = equkm3;
		this.aplcge = aplcge;
		this.minser = minser;
		this.artlin = artlin;
		this.valdet = valdet;
	}

	public CondicTasacionId getId() {
		return this.id;
	}

	public void setId(CondicTasacionId id) {
		this.id = id;
	}

	public Short getNumtar() {
		return this.numtar;
	}

	public void setNumtar(Short numtar) {
		this.numtar = numtar;
	}

	public Character getTipcal() {
		return this.tipcal;
	}

	public void setTipcal(Character tipcal) {
		this.tipcal = tipcal;
	}

	public Character getGrufac() {
		return this.grufac;
	}

	public void setGrufac(Character grufac) {
		this.grufac = grufac;
	}

	public Short getBasdia() {
		return this.basdia;
	}

	public void setBasdia(Short basdia) {
		this.basdia = basdia;
	}

	public BigDecimal getDtofac() {
		return this.dtofac;
	}

	public void setDtofac(BigDecimal dtofac) {
		this.dtofac = dtofac;
	}

	public BigDecimal getPerseg() {
		return this.perseg;
	}

	public void setPerseg(BigDecimal perseg) {
		this.perseg = perseg;
	}

	public BigDecimal getMinseg() {
		return this.minseg;
	}

	public void setMinseg(BigDecimal minseg) {
		this.minseg = minseg;
	}

	public Integer getEqukm3() {
		return this.equkm3;
	}

	public void setEqukm3(Integer equkm3) {
		this.equkm3 = equkm3;
	}

	public String getAplcge() {
		return this.aplcge;
	}

	public void setAplcge(String aplcge) {
		this.aplcge = aplcge;
	}

	public BigDecimal getMinser() {
		return this.minser;
	}

	public void setMinser(BigDecimal minser) {
		this.minser = minser;
	}

	public Character getArtlin() {
		return this.artlin;
	}

	public void setArtlin(Character artlin) {
		this.artlin = artlin;
	}

	public BigDecimal getValdet() {
		return this.valdet;
	}

	public void setValdet(BigDecimal valdet) {
		this.valdet = valdet;
	}

}
