package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * CondicTasacionId generated by hbm2java
 */
public class CondicTasacionId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private short codcli;
	private String aplica;
	private String bastar;

	public CondicTasacionId() {
	}

	public CondicTasacionId(short codemp, short coddel, short codcli, String aplica, String bastar) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.codcli = codcli;
		this.aplica = aplica;
		this.bastar = bastar;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public String getAplica() {
		return this.aplica;
	}

	public void setAplica(String aplica) {
		this.aplica = aplica;
	}

	public String getBastar() {
		return this.bastar;
	}

	public void setBastar(String bastar) {
		this.bastar = bastar;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CondicTasacionId))
			return false;
		CondicTasacionId castOther = (CondicTasacionId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& (this.getCodcli() == castOther.getCodcli())
				&& ((this.getAplica() == castOther.getAplica()) || (this.getAplica() != null
						&& castOther.getAplica() != null && this.getAplica().equals(castOther.getAplica())))
				&& ((this.getBastar() == castOther.getBastar()) || (this.getBastar() != null
						&& castOther.getBastar() != null && this.getBastar().equals(castOther.getBastar())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + this.getCodcli();
		result = 37 * result + (getAplica() == null ? 0 : this.getAplica().hashCode());
		result = 37 * result + (getBastar() == null ? 0 : this.getBastar().hashCode());
		return result;
	}

}
