package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Cpostal generated by hbm2java
 */
public class Cpostal implements java.io.Serializable {

	private CpostalId id;

	public Cpostal() {
	}

	public Cpostal(CpostalId id) {
		this.id = id;
	}

	public CpostalId getId() {
		return this.id;
	}

	public void setId(CpostalId id) {
		this.id = id;
	}

}
