package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * CpostalId generated by hbm2java
 */
public class CpostalId implements java.io.Serializable {

	private Integer codpos;
	private String nompob;

	public CpostalId() {
	}

	public CpostalId(Integer codpos, String nompob) {
		this.codpos = codpos;
		this.nompob = nompob;
	}

	public Integer getCodpos() {
		return this.codpos;
	}

	public void setCodpos(Integer codpos) {
		this.codpos = codpos;
	}

	public String getNompob() {
		return this.nompob;
	}

	public void setNompob(String nompob) {
		this.nompob = nompob;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CpostalId))
			return false;
		CpostalId castOther = (CpostalId) other;

		return ((this.getCodpos() == castOther.getCodpos()) || (this.getCodpos() != null
				&& castOther.getCodpos() != null && this.getCodpos().equals(castOther.getCodpos())))
				&& ((this.getNompob() == castOther.getNompob()) || (this.getNompob() != null
						&& castOther.getNompob() != null && this.getNompob().equals(castOther.getNompob())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodpos() == null ? 0 : this.getCodpos().hashCode());
		result = 37 * result + (getNompob() == null ? 0 : this.getNompob().hashCode());
		return result;
	}

}
