package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Delegaciones generated by hbm2java
 */
public class Delegaciones implements java.io.Serializable {

	private DelegacionesId id;
	private String cifdni;
	private String nombre;
	private String domici;
	private Integer codpos;
	private String poblac;
	private Short provin;
	private Short pais;
	private String nomplz;
	private char tipplz;
	private String sislog;
	private String telefo;
	private String telefx;

	public Delegaciones() {
	}

	public Delegaciones(DelegacionesId id, char tipplz) {
		this.id = id;
		this.tipplz = tipplz;
	}

	public Delegaciones(DelegacionesId id, String cifdni, String nombre, String domici, Integer codpos, String poblac,
			Short provin, Short pais, String nomplz, char tipplz, String sislog, String telefo, String telefx) {
		this.id = id;
		this.cifdni = cifdni;
		this.nombre = nombre;
		this.domici = domici;
		this.codpos = codpos;
		this.poblac = poblac;
		this.provin = provin;
		this.pais = pais;
		this.nomplz = nomplz;
		this.tipplz = tipplz;
		this.sislog = sislog;
		this.telefo = telefo;
		this.telefx = telefx;
	}

	public DelegacionesId getId() {
		return this.id;
	}

	public void setId(DelegacionesId id) {
		this.id = id;
	}

	public String getCifdni() {
		return this.cifdni;
	}

	public void setCifdni(String cifdni) {
		this.cifdni = cifdni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDomici() {
		return this.domici;
	}

	public void setDomici(String domici) {
		this.domici = domici;
	}

	public Integer getCodpos() {
		return this.codpos;
	}

	public void setCodpos(Integer codpos) {
		this.codpos = codpos;
	}

	public String getPoblac() {
		return this.poblac;
	}

	public void setPoblac(String poblac) {
		this.poblac = poblac;
	}

	public Short getProvin() {
		return this.provin;
	}

	public void setProvin(Short provin) {
		this.provin = provin;
	}

	public Short getPais() {
		return this.pais;
	}

	public void setPais(Short pais) {
		this.pais = pais;
	}

	public String getNomplz() {
		return this.nomplz;
	}

	public void setNomplz(String nomplz) {
		this.nomplz = nomplz;
	}

	public char getTipplz() {
		return this.tipplz;
	}

	public void setTipplz(char tipplz) {
		this.tipplz = tipplz;
	}

	public String getSislog() {
		return this.sislog;
	}

	public void setSislog(String sislog) {
		this.sislog = sislog;
	}

	public String getTelefo() {
		return this.telefo;
	}

	public void setTelefo(String telefo) {
		this.telefo = telefo;
	}

	public String getTelefx() {
		return this.telefx;
	}

	public void setTelefx(String telefx) {
		this.telefx = telefx;
	}

}
