package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * DelegacionesId generated by hbm2java
 */
public class DelegacionesId implements java.io.Serializable {

	private short codemp;
	private short coddel;

	public DelegacionesId() {
	}

	public DelegacionesId(short codemp, short coddel) {
		this.codemp = codemp;
		this.coddel = coddel;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DelegacionesId))
			return false;
		DelegacionesId castOther = (DelegacionesId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		return result;
	}

}
