package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Empresas generated by hbm2java
 */
public class Empresas implements java.io.Serializable {

	private short codemp;
	private String nomemp;
	private String cifdni;
	private String domfis;
	private Integer codpos;
	private String pobfis;
	private Short provin;
	private Short pais;
	private String telefo;
	private String telefx;

	public Empresas() {
	}

	public Empresas(short codemp, String nomemp, String cifdni, String domfis, String pobfis) {
		this.codemp = codemp;
		this.nomemp = nomemp;
		this.cifdni = cifdni;
		this.domfis = domfis;
		this.pobfis = pobfis;
	}

	public Empresas(short codemp, String nomemp, String cifdni, String domfis, Integer codpos, String pobfis,
			Short provin, Short pais, String telefo, String telefx) {
		this.codemp = codemp;
		this.nomemp = nomemp;
		this.cifdni = cifdni;
		this.domfis = domfis;
		this.codpos = codpos;
		this.pobfis = pobfis;
		this.provin = provin;
		this.pais = pais;
		this.telefo = telefo;
		this.telefx = telefx;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public String getNomemp() {
		return this.nomemp;
	}

	public void setNomemp(String nomemp) {
		this.nomemp = nomemp;
	}

	public String getCifdni() {
		return this.cifdni;
	}

	public void setCifdni(String cifdni) {
		this.cifdni = cifdni;
	}

	public String getDomfis() {
		return this.domfis;
	}

	public void setDomfis(String domfis) {
		this.domfis = domfis;
	}

	public Integer getCodpos() {
		return this.codpos;
	}

	public void setCodpos(Integer codpos) {
		this.codpos = codpos;
	}

	public String getPobfis() {
		return this.pobfis;
	}

	public void setPobfis(String pobfis) {
		this.pobfis = pobfis;
	}

	public Short getProvin() {
		return this.provin;
	}

	public void setProvin(Short provin) {
		this.provin = provin;
	}

	public Short getPais() {
		return this.pais;
	}

	public void setPais(Short pais) {
		this.pais = pais;
	}

	public String getTelefo() {
		return this.telefo;
	}

	public void setTelefo(String telefo) {
		this.telefo = telefo;
	}

	public String getTelefx() {
		return this.telefx;
	}

	public void setTelefx(String telefx) {
		this.telefx = telefx;
	}

}
