package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * FifolifoId generated by hbm2java
 */
public class FifolifoId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private short codcli;
	private String codart;
	private Date fecent;
	private String horizo;
	private short vertic;
	private BigDecimal udsart;

	public FifolifoId() {
	}

	public FifolifoId(short codemp, short coddel, short codcli, String codart, String horizo, short vertic) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.codcli = codcli;
		this.codart = codart;
		this.horizo = horizo;
		this.vertic = vertic;
	}

	public FifolifoId(short codemp, short coddel, short codcli, String codart, Date fecent, String horizo, short vertic,
			BigDecimal udsart) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.codcli = codcli;
		this.codart = codart;
		this.fecent = fecent;
		this.horizo = horizo;
		this.vertic = vertic;
		this.udsart = udsart;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public Date getFecent() {
		return this.fecent;
	}

	public void setFecent(Date fecent) {
		this.fecent = fecent;
	}

	public String getHorizo() {
		return this.horizo;
	}

	public void setHorizo(String horizo) {
		this.horizo = horizo;
	}

	public short getVertic() {
		return this.vertic;
	}

	public void setVertic(short vertic) {
		this.vertic = vertic;
	}

	public BigDecimal getUdsart() {
		return this.udsart;
	}

	public void setUdsart(BigDecimal udsart) {
		this.udsart = udsart;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FifolifoId))
			return false;
		FifolifoId castOther = (FifolifoId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& (this.getCodcli() == castOther.getCodcli())
				&& ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
						&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())))
				&& ((this.getFecent() == castOther.getFecent()) || (this.getFecent() != null
						&& castOther.getFecent() != null && this.getFecent().equals(castOther.getFecent())))
				&& ((this.getHorizo() == castOther.getHorizo()) || (this.getHorizo() != null
						&& castOther.getHorizo() != null && this.getHorizo().equals(castOther.getHorizo())))
				&& (this.getVertic() == castOther.getVertic())
				&& ((this.getUdsart() == castOther.getUdsart()) || (this.getUdsart() != null
						&& castOther.getUdsart() != null && this.getUdsart().equals(castOther.getUdsart())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + this.getCodcli();
		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		result = 37 * result + (getFecent() == null ? 0 : this.getFecent().hashCode());
		result = 37 * result + (getHorizo() == null ? 0 : this.getHorizo().hashCode());
		result = 37 * result + this.getVertic();
		result = 37 * result + (getUdsart() == null ? 0 : this.getUdsart().hashCode());
		return result;
	}

}
