package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Fifolifo generated by hbm2java
 */
public class Fifolifo implements java.io.Serializable {

	private FifolifoId id;

	public Fifolifo() {
	}

	public Fifolifo(FifolifoId id) {
		this.id = id;
	}

	public FifolifoId getId() {
		return this.id;
	}

	public void setId(FifolifoId id) {
		this.id = id;
	}

}
