package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Formetiq generated by hbm2java
 */
public class Formetiq implements java.io.Serializable {

	private FormetiqId id;

	public Formetiq() {
	}

	public Formetiq(FormetiqId id) {
		this.id = id;
	}

	public FormetiqId getId() {
		return this.id;
	}

	public void setId(FormetiqId id) {
		this.id = id;
	}

}
