package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * FormetiqId generated by hbm2java
 */
public class FormetiqId implements java.io.Serializable {

	private String fmtoetiq;
	private String fmtodesc;
	private String fmtoarch;
	private String fmtoimpr;

	public FormetiqId() {
	}

	public FormetiqId(String fmtoetiq, String fmtodesc, String fmtoarch, String fmtoimpr) {
		this.fmtoetiq = fmtoetiq;
		this.fmtodesc = fmtodesc;
		this.fmtoarch = fmtoarch;
		this.fmtoimpr = fmtoimpr;
	}

	public String getFmtoetiq() {
		return this.fmtoetiq;
	}

	public void setFmtoetiq(String fmtoetiq) {
		this.fmtoetiq = fmtoetiq;
	}

	public String getFmtodesc() {
		return this.fmtodesc;
	}

	public void setFmtodesc(String fmtodesc) {
		this.fmtodesc = fmtodesc;
	}

	public String getFmtoarch() {
		return this.fmtoarch;
	}

	public void setFmtoarch(String fmtoarch) {
		this.fmtoarch = fmtoarch;
	}

	public String getFmtoimpr() {
		return this.fmtoimpr;
	}

	public void setFmtoimpr(String fmtoimpr) {
		this.fmtoimpr = fmtoimpr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FormetiqId))
			return false;
		FormetiqId castOther = (FormetiqId) other;

		return ((this.getFmtoetiq() == castOther.getFmtoetiq()) || (this.getFmtoetiq() != null
				&& castOther.getFmtoetiq() != null && this.getFmtoetiq().equals(castOther.getFmtoetiq())))
				&& ((this.getFmtodesc() == castOther.getFmtodesc()) || (this.getFmtodesc() != null
						&& castOther.getFmtodesc() != null && this.getFmtodesc().equals(castOther.getFmtodesc())))
				&& ((this.getFmtoarch() == castOther.getFmtoarch()) || (this.getFmtoarch() != null
						&& castOther.getFmtoarch() != null && this.getFmtoarch().equals(castOther.getFmtoarch())))
				&& ((this.getFmtoimpr() == castOther.getFmtoimpr()) || (this.getFmtoimpr() != null
						&& castOther.getFmtoimpr() != null && this.getFmtoimpr().equals(castOther.getFmtoimpr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFmtoetiq() == null ? 0 : this.getFmtoetiq().hashCode());
		result = 37 * result + (getFmtodesc() == null ? 0 : this.getFmtodesc().hashCode());
		result = 37 * result + (getFmtoarch() == null ? 0 : this.getFmtoarch().hashCode());
		result = 37 * result + (getFmtoimpr() == null ? 0 : this.getFmtoimpr().hashCode());
		return result;
	}

}
