package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Forpagos generated by hbm2java
 */
public class Forpagos implements java.io.Serializable {

	private ForpagosId id;

	public Forpagos() {
	}

	public Forpagos(ForpagosId id) {
		this.id = id;
	}

	public ForpagosId getId() {
		return this.id;
	}

	public void setId(ForpagosId id) {
		this.id = id;
	}

}
