package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * ForpagosId generated by hbm2java
 */
public class ForpagosId implements java.io.Serializable {

	private String forpag;
	private String descri;

	public ForpagosId() {
	}

	public ForpagosId(String forpag, String descri) {
		this.forpag = forpag;
		this.descri = descri;
	}

	public String getForpag() {
		return this.forpag;
	}

	public void setForpag(String forpag) {
		this.forpag = forpag;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ForpagosId))
			return false;
		ForpagosId castOther = (ForpagosId) other;

		return ((this.getForpag() == castOther.getForpag()) || (this.getForpag() != null
				&& castOther.getForpag() != null && this.getForpag().equals(castOther.getForpag())))
				&& ((this.getDescri() == castOther.getDescri()) || (this.getDescri() != null
						&& castOther.getDescri() != null && this.getDescri().equals(castOther.getDescri())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getForpag() == null ? 0 : this.getForpag().hashCode());
		result = 37 * result + (getDescri() == null ? 0 : this.getDescri().hashCode());
		return result;
	}

}
