package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * GrupTarifId generated by hbm2java
 */
public class GrupTarifId implements java.io.Serializable {

	private short codemp;
	private short grupo;
	private String dscgru;

	public GrupTarifId() {
	}

	public GrupTarifId(short codemp, short grupo, String dscgru) {
		this.codemp = codemp;
		this.grupo = grupo;
		this.dscgru = dscgru;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getGrupo() {
		return this.grupo;
	}

	public void setGrupo(short grupo) {
		this.grupo = grupo;
	}

	public String getDscgru() {
		return this.dscgru;
	}

	public void setDscgru(String dscgru) {
		this.dscgru = dscgru;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GrupTarifId))
			return false;
		GrupTarifId castOther = (GrupTarifId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getGrupo() == castOther.getGrupo())
				&& ((this.getDscgru() == castOther.getDscgru()) || (this.getDscgru() != null
						&& castOther.getDscgru() != null && this.getDscgru().equals(castOther.getDscgru())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getGrupo();
		result = 37 * result + (getDscgru() == null ? 0 : this.getDscgru().hashCode());
		return result;
	}

}
