package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * GrupTarif generated by hbm2java
 */
public class GrupTarif implements java.io.Serializable {

	private GrupTarifId id;

	public GrupTarif() {
	}

	public GrupTarif(GrupTarifId id) {
		this.id = id;
	}

	public GrupTarifId getId() {
		return this.id;
	}

	public void setId(GrupTarifId id) {
		this.id = id;
	}

}
