package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * IvasId generated by hbm2java
 */
public class IvasId implements java.io.Serializable {

	private Character tipiva;
	private BigDecimal periva;
	private BigDecimal perreq;

	public IvasId() {
	}

	public IvasId(Character tipiva, BigDecimal periva, BigDecimal perreq) {
		this.tipiva = tipiva;
		this.periva = periva;
		this.perreq = perreq;
	}

	public Character getTipiva() {
		return this.tipiva;
	}

	public void setTipiva(Character tipiva) {
		this.tipiva = tipiva;
	}

	public BigDecimal getPeriva() {
		return this.periva;
	}

	public void setPeriva(BigDecimal periva) {
		this.periva = periva;
	}

	public BigDecimal getPerreq() {
		return this.perreq;
	}

	public void setPerreq(BigDecimal perreq) {
		this.perreq = perreq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IvasId))
			return false;
		IvasId castOther = (IvasId) other;

		return ((this.getTipiva() == castOther.getTipiva()) || (this.getTipiva() != null
				&& castOther.getTipiva() != null && this.getTipiva().equals(castOther.getTipiva())))
				&& ((this.getPeriva() == castOther.getPeriva()) || (this.getPeriva() != null
						&& castOther.getPeriva() != null && this.getPeriva().equals(castOther.getPeriva())))
				&& ((this.getPerreq() == castOther.getPerreq()) || (this.getPerreq() != null
						&& castOther.getPerreq() != null && this.getPerreq().equals(castOther.getPerreq())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTipiva() == null ? 0 : this.getTipiva().hashCode());
		result = 37 * result + (getPeriva() == null ? 0 : this.getPeriva().hashCode());
		result = 37 * result + (getPerreq() == null ? 0 : this.getPerreq().hashCode());
		return result;
	}

}
