package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Ivas generated by hbm2java
 */
public class Ivas implements java.io.Serializable {

	private IvasId id;

	public Ivas() {
	}

	public Ivas(IvasId id) {
		this.id = id;
	}

	public IvasId getId() {
		return this.id;
	}

	public void setId(IvasId id) {
		this.id = id;
	}

}
