package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * KachakilId generated by hbm2java
 */
public class KachakilId implements java.io.Serializable {

	private String modelo;
	private String tallas;
	private String marca;
	private String destino;
	private Integer cajas;
	private Integer pares;
	private int norden;

	public KachakilId() {
	}

	public KachakilId(int norden) {
		this.norden = norden;
	}

	public KachakilId(String modelo, String tallas, String marca, String destino, Integer cajas, Integer pares,
			int norden) {
		this.modelo = modelo;
		this.tallas = tallas;
		this.marca = marca;
		this.destino = destino;
		this.cajas = cajas;
		this.pares = pares;
		this.norden = norden;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getTallas() {
		return this.tallas;
	}

	public void setTallas(String tallas) {
		this.tallas = tallas;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getDestino() {
		return this.destino;
	}

	public void setDestino(String destino) {
		this.destino = destino;
	}

	public Integer getCajas() {
		return this.cajas;
	}

	public void setCajas(Integer cajas) {
		this.cajas = cajas;
	}

	public Integer getPares() {
		return this.pares;
	}

	public void setPares(Integer pares) {
		this.pares = pares;
	}

	public int getNorden() {
		return this.norden;
	}

	public void setNorden(int norden) {
		this.norden = norden;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KachakilId))
			return false;
		KachakilId castOther = (KachakilId) other;

		return ((this.getModelo() == castOther.getModelo()) || (this.getModelo() != null
				&& castOther.getModelo() != null && this.getModelo().equals(castOther.getModelo())))
				&& ((this.getTallas() == castOther.getTallas()) || (this.getTallas() != null
						&& castOther.getTallas() != null && this.getTallas().equals(castOther.getTallas())))
				&& ((this.getMarca() == castOther.getMarca()) || (this.getMarca() != null
						&& castOther.getMarca() != null && this.getMarca().equals(castOther.getMarca())))
				&& ((this.getDestino() == castOther.getDestino()) || (this.getDestino() != null
						&& castOther.getDestino() != null && this.getDestino().equals(castOther.getDestino())))
				&& ((this.getCajas() == castOther.getCajas()) || (this.getCajas() != null
						&& castOther.getCajas() != null && this.getCajas().equals(castOther.getCajas())))
				&& ((this.getPares() == castOther.getPares()) || (this.getPares() != null
						&& castOther.getPares() != null && this.getPares().equals(castOther.getPares())))
				&& (this.getNorden() == castOther.getNorden());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getModelo() == null ? 0 : this.getModelo().hashCode());
		result = 37 * result + (getTallas() == null ? 0 : this.getTallas().hashCode());
		result = 37 * result + (getMarca() == null ? 0 : this.getMarca().hashCode());
		result = 37 * result + (getDestino() == null ? 0 : this.getDestino().hashCode());
		result = 37 * result + (getCajas() == null ? 0 : this.getCajas().hashCode());
		result = 37 * result + (getPares() == null ? 0 : this.getPares().hashCode());
		result = 37 * result + this.getNorden();
		return result;
	}

}
