package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Kachakil generated by hbm2java
 */
public class Kachakil implements java.io.Serializable {

	private KachakilId id;

	public Kachakil() {
	}

	public Kachakil(KachakilId id) {
		this.id = id;
	}

	public KachakilId getId() {
		return this.id;
	}

	public void setId(KachakilId id) {
		this.id = id;
	}

}
