package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Lin2006 generated by hbm2java
 */
public class Lin2006 implements java.io.Serializable {

	private Lin2006Id id;
	private String codart;
	private BigDecimal cantid;
	private short bultos;
	private BigDecimal kilos;
	private BigDecimal volume;
	private BigDecimal precio;
	private Date fecalb;
	private Date fcaduc;
	private String horizo;
	private Short vertic;
	private Character baralm;
	private BigDecimal udsalm;
	private String basalm;
	private String lotefb;
	private String tipemb;
	private BigDecimal dtoli1;
	private BigDecimal dtoli2;
	private String descri;
	private String serped;
	private Short ejeped;
	private Integer numped;
	private Short linped;
	private Character estado;
	private Short palets;
	private String nserie;
	private String idsscc;
	private Integer nopick;
	private Short lnpick;
	private String codkit;

	public Lin2006() {
	}

	public Lin2006(Lin2006Id id, String codart, BigDecimal cantid, short bultos, BigDecimal kilos, Date fecalb) {
		this.id = id;
		this.codart = codart;
		this.cantid = cantid;
		this.bultos = bultos;
		this.kilos = kilos;
		this.fecalb = fecalb;
	}

	public Lin2006(Lin2006Id id, String codart, BigDecimal cantid, short bultos, BigDecimal kilos, BigDecimal volume,
			BigDecimal precio, Date fecalb, Date fcaduc, String horizo, Short vertic, Character baralm,
			BigDecimal udsalm, String basalm, String lotefb, String tipemb, BigDecimal dtoli1, BigDecimal dtoli2,
			String descri, String serped, Short ejeped, Integer numped, Short linped, Character estado, Short palets,
			String nserie, String idsscc, Integer nopick, Short lnpick, String codkit) {
		this.id = id;
		this.codart = codart;
		this.cantid = cantid;
		this.bultos = bultos;
		this.kilos = kilos;
		this.volume = volume;
		this.precio = precio;
		this.fecalb = fecalb;
		this.fcaduc = fcaduc;
		this.horizo = horizo;
		this.vertic = vertic;
		this.baralm = baralm;
		this.udsalm = udsalm;
		this.basalm = basalm;
		this.lotefb = lotefb;
		this.tipemb = tipemb;
		this.dtoli1 = dtoli1;
		this.dtoli2 = dtoli2;
		this.descri = descri;
		this.serped = serped;
		this.ejeped = ejeped;
		this.numped = numped;
		this.linped = linped;
		this.estado = estado;
		this.palets = palets;
		this.nserie = nserie;
		this.idsscc = idsscc;
		this.nopick = nopick;
		this.lnpick = lnpick;
		this.codkit = codkit;
	}

	public Lin2006Id getId() {
		return this.id;
	}

	public void setId(Lin2006Id id) {
		this.id = id;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public BigDecimal getCantid() {
		return this.cantid;
	}

	public void setCantid(BigDecimal cantid) {
		this.cantid = cantid;
	}

	public short getBultos() {
		return this.bultos;
	}

	public void setBultos(short bultos) {
		this.bultos = bultos;
	}

	public BigDecimal getKilos() {
		return this.kilos;
	}

	public void setKilos(BigDecimal kilos) {
		this.kilos = kilos;
	}

	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public Date getFecalb() {
		return this.fecalb;
	}

	public void setFecalb(Date fecalb) {
		this.fecalb = fecalb;
	}

	public Date getFcaduc() {
		return this.fcaduc;
	}

	public void setFcaduc(Date fcaduc) {
		this.fcaduc = fcaduc;
	}

	public String getHorizo() {
		return this.horizo;
	}

	public void setHorizo(String horizo) {
		this.horizo = horizo;
	}

	public Short getVertic() {
		return this.vertic;
	}

	public void setVertic(Short vertic) {
		this.vertic = vertic;
	}

	public Character getBaralm() {
		return this.baralm;
	}

	public void setBaralm(Character baralm) {
		this.baralm = baralm;
	}

	public BigDecimal getUdsalm() {
		return this.udsalm;
	}

	public void setUdsalm(BigDecimal udsalm) {
		this.udsalm = udsalm;
	}

	public String getBasalm() {
		return this.basalm;
	}

	public void setBasalm(String basalm) {
		this.basalm = basalm;
	}

	public String getLotefb() {
		return this.lotefb;
	}

	public void setLotefb(String lotefb) {
		this.lotefb = lotefb;
	}

	public String getTipemb() {
		return this.tipemb;
	}

	public void setTipemb(String tipemb) {
		this.tipemb = tipemb;
	}

	public BigDecimal getDtoli1() {
		return this.dtoli1;
	}

	public void setDtoli1(BigDecimal dtoli1) {
		this.dtoli1 = dtoli1;
	}

	public BigDecimal getDtoli2() {
		return this.dtoli2;
	}

	public void setDtoli2(BigDecimal dtoli2) {
		this.dtoli2 = dtoli2;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public String getSerped() {
		return this.serped;
	}

	public void setSerped(String serped) {
		this.serped = serped;
	}

	public Short getEjeped() {
		return this.ejeped;
	}

	public void setEjeped(Short ejeped) {
		this.ejeped = ejeped;
	}

	public Integer getNumped() {
		return this.numped;
	}

	public void setNumped(Integer numped) {
		this.numped = numped;
	}

	public Short getLinped() {
		return this.linped;
	}

	public void setLinped(Short linped) {
		this.linped = linped;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public Short getPalets() {
		return this.palets;
	}

	public void setPalets(Short palets) {
		this.palets = palets;
	}

	public String getNserie() {
		return this.nserie;
	}

	public void setNserie(String nserie) {
		this.nserie = nserie;
	}

	public String getIdsscc() {
		return this.idsscc;
	}

	public void setIdsscc(String idsscc) {
		this.idsscc = idsscc;
	}

	public Integer getNopick() {
		return this.nopick;
	}

	public void setNopick(Integer nopick) {
		this.nopick = nopick;
	}

	public Short getLnpick() {
		return this.lnpick;
	}

	public void setLnpick(Short lnpick) {
		this.lnpick = lnpick;
	}

	public String getCodkit() {
		return this.codkit;
	}

	public void setCodkit(String codkit) {
		this.codkit = codkit;
	}

}
