package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Linfactu generated by hbm2java
 */
public class Linfactu implements java.io.Serializable {

	private LinfactuId id;
	private String aplica;
	private Date feccal;
	private String descri;
	private String bastar;
	private BigDecimal unitas;
	private BigDecimal import_;
	private String docref;
	private BigDecimal perseg;
	private BigDecimal seguro;
	private Character tipalb;
	private String txtadi;

	public Linfactu() {
	}

	public Linfactu(LinfactuId id, String aplica, Date feccal) {
		this.id = id;
		this.aplica = aplica;
		this.feccal = feccal;
	}

	public Linfactu(LinfactuId id, String aplica, Date feccal, String descri, String bastar, BigDecimal unitas,
			BigDecimal import_, String docref, BigDecimal perseg, BigDecimal seguro, Character tipalb, String txtadi) {
		this.id = id;
		this.aplica = aplica;
		this.feccal = feccal;
		this.descri = descri;
		this.bastar = bastar;
		this.unitas = unitas;
		this.import_ = import_;
		this.docref = docref;
		this.perseg = perseg;
		this.seguro = seguro;
		this.tipalb = tipalb;
		this.txtadi = txtadi;
	}

	public LinfactuId getId() {
		return this.id;
	}

	public void setId(LinfactuId id) {
		this.id = id;
	}

	public String getAplica() {
		return this.aplica;
	}

	public void setAplica(String aplica) {
		this.aplica = aplica;
	}

	public Date getFeccal() {
		return this.feccal;
	}

	public void setFeccal(Date feccal) {
		this.feccal = feccal;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public String getBastar() {
		return this.bastar;
	}

	public void setBastar(String bastar) {
		this.bastar = bastar;
	}

	public BigDecimal getUnitas() {
		return this.unitas;
	}

	public void setUnitas(BigDecimal unitas) {
		this.unitas = unitas;
	}

	public BigDecimal getImport_() {
		return this.import_;
	}

	public void setImport_(BigDecimal import_) {
		this.import_ = import_;
	}

	public String getDocref() {
		return this.docref;
	}

	public void setDocref(String docref) {
		this.docref = docref;
	}

	public BigDecimal getPerseg() {
		return this.perseg;
	}

	public void setPerseg(BigDecimal perseg) {
		this.perseg = perseg;
	}

	public BigDecimal getSeguro() {
		return this.seguro;
	}

	public void setSeguro(BigDecimal seguro) {
		this.seguro = seguro;
	}

	public Character getTipalb() {
		return this.tipalb;
	}

	public void setTipalb(Character tipalb) {
		this.tipalb = tipalb;
	}

	public String getTxtadi() {
		return this.txtadi;
	}

	public void setTxtadi(String txtadi) {
		this.txtadi = txtadi;
	}

}
