package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * LinfactuId generated by hbm2java
 */
public class LinfactuId implements java.io.Serializable {

	private short codemp;
	private short cenfac;
	private char serfac;
	private short ejefac;
	private int numfac;
	private short numlin;

	public LinfactuId() {
	}

	public LinfactuId(short codemp, short cenfac, char serfac, short ejefac, int numfac, short numlin) {
		this.codemp = codemp;
		this.cenfac = cenfac;
		this.serfac = serfac;
		this.ejefac = ejefac;
		this.numfac = numfac;
		this.numlin = numlin;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCenfac() {
		return this.cenfac;
	}

	public void setCenfac(short cenfac) {
		this.cenfac = cenfac;
	}

	public char getSerfac() {
		return this.serfac;
	}

	public void setSerfac(char serfac) {
		this.serfac = serfac;
	}

	public short getEjefac() {
		return this.ejefac;
	}

	public void setEjefac(short ejefac) {
		this.ejefac = ejefac;
	}

	public int getNumfac() {
		return this.numfac;
	}

	public void setNumfac(int numfac) {
		this.numfac = numfac;
	}

	public short getNumlin() {
		return this.numlin;
	}

	public void setNumlin(short numlin) {
		this.numlin = numlin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LinfactuId))
			return false;
		LinfactuId castOther = (LinfactuId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCenfac() == castOther.getCenfac())
				&& (this.getSerfac() == castOther.getSerfac()) && (this.getEjefac() == castOther.getEjefac())
				&& (this.getNumfac() == castOther.getNumfac()) && (this.getNumlin() == castOther.getNumlin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCenfac();
		result = 37 * result + this.getSerfac();
		result = 37 * result + this.getEjefac();
		result = 37 * result + this.getNumfac();
		result = 37 * result + this.getNumlin();
		return result;
	}

}
