package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * LinpedalId generated by hbm2java
 */
public class LinpedalId implements java.io.Serializable {

	private int nproce;
	private short linalb;

	public LinpedalId() {
	}

	public LinpedalId(int nproce, short linalb) {
		this.nproce = nproce;
		this.linalb = linalb;
	}

	public int getNproce() {
		return this.nproce;
	}

	public void setNproce(int nproce) {
		this.nproce = nproce;
	}

	public short getLinalb() {
		return this.linalb;
	}

	public void setLinalb(short linalb) {
		this.linalb = linalb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LinpedalId))
			return false;
		LinpedalId castOther = (LinpedalId) other;

		return (this.getNproce() == castOther.getNproce()) && (this.getLinalb() == castOther.getLinalb());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNproce();
		result = 37 * result + this.getLinalb();
		return result;
	}

}
