package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Linpedidos generated by hbm2java
 */
public class Linpedidos implements java.io.Serializable {

	private LinpedidosId id;
	private String codart;
	private BigDecimal cantid;
	private short bultos;
	private BigDecimal kilos;
	private BigDecimal volume;
	private BigDecimal precio;
	private BigDecimal dtoli1;
	private BigDecimal dtoli2;
	private String descri;
	private Character estado;
	private Character tipdoc;
	private BigDecimal tipiva;
	private Character edilin;
	private Short asocia;
	private Integer nopick;
	private Short lnpick;
	private String codkit;

	public Linpedidos() {
	}

	public Linpedidos(LinpedidosId id, String codart, BigDecimal cantid, short bultos, BigDecimal kilos) {
		this.id = id;
		this.codart = codart;
		this.cantid = cantid;
		this.bultos = bultos;
		this.kilos = kilos;
	}

	public Linpedidos(LinpedidosId id, String codart, BigDecimal cantid, short bultos, BigDecimal kilos,
			BigDecimal volume, BigDecimal precio, BigDecimal dtoli1, BigDecimal dtoli2, String descri, Character estado,
			Character tipdoc, BigDecimal tipiva, Character edilin, Short asocia, Integer nopick, Short lnpick,
			String codkit) {
		this.id = id;
		this.codart = codart;
		this.cantid = cantid;
		this.bultos = bultos;
		this.kilos = kilos;
		this.volume = volume;
		this.precio = precio;
		this.dtoli1 = dtoli1;
		this.dtoli2 = dtoli2;
		this.descri = descri;
		this.estado = estado;
		this.tipdoc = tipdoc;
		this.tipiva = tipiva;
		this.edilin = edilin;
		this.asocia = asocia;
		this.nopick = nopick;
		this.lnpick = lnpick;
		this.codkit = codkit;
	}

	public LinpedidosId getId() {
		return this.id;
	}

	public void setId(LinpedidosId id) {
		this.id = id;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public BigDecimal getCantid() {
		return this.cantid;
	}

	public void setCantid(BigDecimal cantid) {
		this.cantid = cantid;
	}

	public short getBultos() {
		return this.bultos;
	}

	public void setBultos(short bultos) {
		this.bultos = bultos;
	}

	public BigDecimal getKilos() {
		return this.kilos;
	}

	public void setKilos(BigDecimal kilos) {
		this.kilos = kilos;
	}

	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public BigDecimal getDtoli1() {
		return this.dtoli1;
	}

	public void setDtoli1(BigDecimal dtoli1) {
		this.dtoli1 = dtoli1;
	}

	public BigDecimal getDtoli2() {
		return this.dtoli2;
	}

	public void setDtoli2(BigDecimal dtoli2) {
		this.dtoli2 = dtoli2;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public Character getTipdoc() {
		return this.tipdoc;
	}

	public void setTipdoc(Character tipdoc) {
		this.tipdoc = tipdoc;
	}

	public BigDecimal getTipiva() {
		return this.tipiva;
	}

	public void setTipiva(BigDecimal tipiva) {
		this.tipiva = tipiva;
	}

	public Character getEdilin() {
		return this.edilin;
	}

	public void setEdilin(Character edilin) {
		this.edilin = edilin;
	}

	public Short getAsocia() {
		return this.asocia;
	}

	public void setAsocia(Short asocia) {
		this.asocia = asocia;
	}

	public Integer getNopick() {
		return this.nopick;
	}

	public void setNopick(Integer nopick) {
		this.nopick = nopick;
	}

	public Short getLnpick() {
		return this.lnpick;
	}

	public void setLnpick(Short lnpick) {
		this.lnpick = lnpick;
	}

	public String getCodkit() {
		return this.codkit;
	}

	public void setCodkit(String codkit) {
		this.codkit = codkit;
	}

}
