package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Linpedhw generated by hbm2java
 */
public class Linpedhw implements java.io.Serializable {

	private LinpedhwId id;
	private int numped;
	private Short linped;
	private String codart;
	private String descri;
	private Date fcaduc;
	private String lotefb;
	private String nserie;
	private BigDecimal cantid;
	private Short bultos;
	private BigDecimal kilos;
	private BigDecimal volume;
	private Short palets;
	private BigDecimal precio;
	private BigDecimal dtoli1;
	private BigDecimal dtoli2;
	private String idsscc;
	private String codkit;

	public Linpedhw() {
	}

	public Linpedhw(LinpedhwId id, int numped) {
		this.id = id;
		this.numped = numped;
	}

	public Linpedhw(LinpedhwId id, int numped, Short linped, String codart, String descri, Date fcaduc, String lotefb,
			String nserie, BigDecimal cantid, Short bultos, BigDecimal kilos, BigDecimal volume, Short palets,
			BigDecimal precio, BigDecimal dtoli1, BigDecimal dtoli2, String idsscc, String codkit) {
		this.id = id;
		this.numped = numped;
		this.linped = linped;
		this.codart = codart;
		this.descri = descri;
		this.fcaduc = fcaduc;
		this.lotefb = lotefb;
		this.nserie = nserie;
		this.cantid = cantid;
		this.bultos = bultos;
		this.kilos = kilos;
		this.volume = volume;
		this.palets = palets;
		this.precio = precio;
		this.dtoli1 = dtoli1;
		this.dtoli2 = dtoli2;
		this.idsscc = idsscc;
		this.codkit = codkit;
	}

	public LinpedhwId getId() {
		return this.id;
	}

	public void setId(LinpedhwId id) {
		this.id = id;
	}

	public int getNumped() {
		return this.numped;
	}

	public void setNumped(int numped) {
		this.numped = numped;
	}

	public Short getLinped() {
		return this.linped;
	}

	public void setLinped(Short linped) {
		this.linped = linped;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public Date getFcaduc() {
		return this.fcaduc;
	}

	public void setFcaduc(Date fcaduc) {
		this.fcaduc = fcaduc;
	}

	public String getLotefb() {
		return this.lotefb;
	}

	public void setLotefb(String lotefb) {
		this.lotefb = lotefb;
	}

	public String getNserie() {
		return this.nserie;
	}

	public void setNserie(String nserie) {
		this.nserie = nserie;
	}

	public BigDecimal getCantid() {
		return this.cantid;
	}

	public void setCantid(BigDecimal cantid) {
		this.cantid = cantid;
	}

	public Short getBultos() {
		return this.bultos;
	}

	public void setBultos(Short bultos) {
		this.bultos = bultos;
	}

	public BigDecimal getKilos() {
		return this.kilos;
	}

	public void setKilos(BigDecimal kilos) {
		this.kilos = kilos;
	}

	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	public Short getPalets() {
		return this.palets;
	}

	public void setPalets(Short palets) {
		this.palets = palets;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public BigDecimal getDtoli1() {
		return this.dtoli1;
	}

	public void setDtoli1(BigDecimal dtoli1) {
		this.dtoli1 = dtoli1;
	}

	public BigDecimal getDtoli2() {
		return this.dtoli2;
	}

	public void setDtoli2(BigDecimal dtoli2) {
		this.dtoli2 = dtoli2;
	}

	public String getIdsscc() {
		return this.idsscc;
	}

	public void setIdsscc(String idsscc) {
		this.idsscc = idsscc;
	}

	public String getCodkit() {
		return this.codkit;
	}

	public void setCodkit(String codkit) {
		this.codkit = codkit;
	}

}
