package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * LinpedidosId generated by hbm2java
 */
public class LinpedidosId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private short codcli;
	private char tipped;
	private String serped;
	private short ejeped;
	private int numped;
	private short numlin;

	public LinpedidosId() {
	}

	public LinpedidosId(short codemp, short coddel, short codcli, char tipped, String serped, short ejeped, int numped,
			short numlin) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.codcli = codcli;
		this.tipped = tipped;
		this.serped = serped;
		this.ejeped = ejeped;
		this.numped = numped;
		this.numlin = numlin;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public char getTipped() {
		return this.tipped;
	}

	public void setTipped(char tipped) {
		this.tipped = tipped;
	}

	public String getSerped() {
		return this.serped;
	}

	public void setSerped(String serped) {
		this.serped = serped;
	}

	public short getEjeped() {
		return this.ejeped;
	}

	public void setEjeped(short ejeped) {
		this.ejeped = ejeped;
	}

	public int getNumped() {
		return this.numped;
	}

	public void setNumped(int numped) {
		this.numped = numped;
	}

	public short getNumlin() {
		return this.numlin;
	}

	public void setNumlin(short numlin) {
		this.numlin = numlin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LinpedidosId))
			return false;
		LinpedidosId castOther = (LinpedidosId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& (this.getCodcli() == castOther.getCodcli()) && (this.getTipped() == castOther.getTipped())
				&& ((this.getSerped() == castOther.getSerped()) || (this.getSerped() != null
						&& castOther.getSerped() != null && this.getSerped().equals(castOther.getSerped())))
				&& (this.getEjeped() == castOther.getEjeped()) && (this.getNumped() == castOther.getNumped())
				&& (this.getNumlin() == castOther.getNumlin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + this.getCodcli();
		result = 37 * result + this.getTipped();
		result = 37 * result + (getSerped() == null ? 0 : this.getSerped().hashCode());
		result = 37 * result + this.getEjeped();
		result = 37 * result + this.getNumped();
		result = 37 * result + this.getNumlin();
		return result;
	}

}
