package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Linrepartos generated by hbm2java
 */
public class Linrepartos implements java.io.Serializable {

	private LinrepartosId id;

	public Linrepartos() {
	}

	public Linrepartos(LinrepartosId id) {
		this.id = id;
	}

	public LinrepartosId getId() {
		return this.id;
	}

	public void setId(LinrepartosId id) {
		this.id = id;
	}

}
