package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Numeros generated by hbm2java
 */
public class Numeros implements java.io.Serializable {

	private NumerosId id;

	public Numeros() {
	}

	public Numeros(NumerosId id) {
		this.id = id;
	}

	public NumerosId getId() {
		return this.id;
	}

	public void setId(NumerosId id) {
		this.id = id;
	}

}
