package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * NumerosId generated by hbm2java
 */
public class NumerosId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private short ejerci;
	private String clanum;
	private Integer numero;
	private Integer limite;

	public NumerosId() {
	}

	public NumerosId(short codemp, short coddel, short ejerci, String clanum) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.ejerci = ejerci;
		this.clanum = clanum;
	}

	public NumerosId(short codemp, short coddel, short ejerci, String clanum, Integer numero, Integer limite) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.ejerci = ejerci;
		this.clanum = clanum;
		this.numero = numero;
		this.limite = limite;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public short getEjerci() {
		return this.ejerci;
	}

	public void setEjerci(short ejerci) {
		this.ejerci = ejerci;
	}

	public String getClanum() {
		return this.clanum;
	}

	public void setClanum(String clanum) {
		this.clanum = clanum;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public Integer getLimite() {
		return this.limite;
	}

	public void setLimite(Integer limite) {
		this.limite = limite;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NumerosId))
			return false;
		NumerosId castOther = (NumerosId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& (this.getEjerci() == castOther.getEjerci())
				&& ((this.getClanum() == castOther.getClanum()) || (this.getClanum() != null
						&& castOther.getClanum() != null && this.getClanum().equals(castOther.getClanum())))
				&& ((this.getNumero() == castOther.getNumero()) || (this.getNumero() != null
						&& castOther.getNumero() != null && this.getNumero().equals(castOther.getNumero())))
				&& ((this.getLimite() == castOther.getLimite()) || (this.getLimite() != null
						&& castOther.getLimite() != null && this.getLimite().equals(castOther.getLimite())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + this.getEjerci();
		result = 37 * result + (getClanum() == null ? 0 : this.getClanum().hashCode());
		result = 37 * result + (getNumero() == null ? 0 : this.getNumero().hashCode());
		result = 37 * result + (getLimite() == null ? 0 : this.getLimite().hashCode());
		return result;
	}

}
