package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Ocupalmac generated by hbm2java
 */
public class Ocupalmac implements java.io.Serializable {

	private OcupalmacId id;

	public Ocupalmac() {
	}

	public Ocupalmac(OcupalmacId id) {
		this.id = id;
	}

	public OcupalmacId getId() {
		return this.id;
	}

	public void setId(OcupalmacId id) {
		this.id = id;
	}

}
