package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Ocupbasal generated by hbm2java
 */
public class Ocupbasal implements java.io.Serializable {

	private OcupbasalId id;

	public Ocupbasal() {
	}

	public Ocupbasal(OcupbasalId id) {
		this.id = id;
	}

	public OcupbasalId getId() {
		return this.id;
	}

	public void setId(OcupbasalId id) {
		this.id = id;
	}

}
