package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Ocupalmwk generated by hbm2java
 */
public class Ocupalmwk implements java.io.Serializable {

	private OcupalmwkId id;

	public Ocupalmwk() {
	}

	public Ocupalmwk(OcupalmwkId id) {
		this.id = id;
	}

	public OcupalmwkId getId() {
		return this.id;
	}

	public void setId(OcupalmwkId id) {
		this.id = id;
	}

}
