package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * OcupbasalId generated by hbm2java
 */
public class OcupbasalId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private String horizo;
	private short vertic;
	private short codcli;
	private String basalm;
	private BigDecimal udsalm;

	public OcupbasalId() {
	}

	public OcupbasalId(short codemp, short coddel, String horizo, short vertic, short codcli, String basalm) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.horizo = horizo;
		this.vertic = vertic;
		this.codcli = codcli;
		this.basalm = basalm;
	}

	public OcupbasalId(short codemp, short coddel, String horizo, short vertic, short codcli, String basalm,
			BigDecimal udsalm) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.horizo = horizo;
		this.vertic = vertic;
		this.codcli = codcli;
		this.basalm = basalm;
		this.udsalm = udsalm;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public String getHorizo() {
		return this.horizo;
	}

	public void setHorizo(String horizo) {
		this.horizo = horizo;
	}

	public short getVertic() {
		return this.vertic;
	}

	public void setVertic(short vertic) {
		this.vertic = vertic;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public String getBasalm() {
		return this.basalm;
	}

	public void setBasalm(String basalm) {
		this.basalm = basalm;
	}

	public BigDecimal getUdsalm() {
		return this.udsalm;
	}

	public void setUdsalm(BigDecimal udsalm) {
		this.udsalm = udsalm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OcupbasalId))
			return false;
		OcupbasalId castOther = (OcupbasalId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& ((this.getHorizo() == castOther.getHorizo()) || (this.getHorizo() != null
						&& castOther.getHorizo() != null && this.getHorizo().equals(castOther.getHorizo())))
				&& (this.getVertic() == castOther.getVertic()) && (this.getCodcli() == castOther.getCodcli())
				&& ((this.getBasalm() == castOther.getBasalm()) || (this.getBasalm() != null
						&& castOther.getBasalm() != null && this.getBasalm().equals(castOther.getBasalm())))
				&& ((this.getUdsalm() == castOther.getUdsalm()) || (this.getUdsalm() != null
						&& castOther.getUdsalm() != null && this.getUdsalm().equals(castOther.getUdsalm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + (getHorizo() == null ? 0 : this.getHorizo().hashCode());
		result = 37 * result + this.getVertic();
		result = 37 * result + this.getCodcli();
		result = 37 * result + (getBasalm() == null ? 0 : this.getBasalm().hashCode());
		result = 37 * result + (getUdsalm() == null ? 0 : this.getUdsalm().hashCode());
		return result;
	}

}
