package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * OperwkaId generated by hbm2java
 */
public class OperwkaId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private Short ejerci;
	private Integer numdoc;
	private char operac;
	private Short codcli;
	private Character indica;

	public OperwkaId() {
	}

	public OperwkaId(short codemp, short coddel, char operac) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.operac = operac;
	}

	public OperwkaId(short codemp, short coddel, Short ejerci, Integer numdoc, char operac, Short codcli,
			Character indica) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.ejerci = ejerci;
		this.numdoc = numdoc;
		this.operac = operac;
		this.codcli = codcli;
		this.indica = indica;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public Short getEjerci() {
		return this.ejerci;
	}

	public void setEjerci(Short ejerci) {
		this.ejerci = ejerci;
	}

	public Integer getNumdoc() {
		return this.numdoc;
	}

	public void setNumdoc(Integer numdoc) {
		this.numdoc = numdoc;
	}

	public char getOperac() {
		return this.operac;
	}

	public void setOperac(char operac) {
		this.operac = operac;
	}

	public Short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(Short codcli) {
		this.codcli = codcli;
	}

	public Character getIndica() {
		return this.indica;
	}

	public void setIndica(Character indica) {
		this.indica = indica;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OperwkaId))
			return false;
		OperwkaId castOther = (OperwkaId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& ((this.getEjerci() == castOther.getEjerci()) || (this.getEjerci() != null
						&& castOther.getEjerci() != null && this.getEjerci().equals(castOther.getEjerci())))
				&& ((this.getNumdoc() == castOther.getNumdoc()) || (this.getNumdoc() != null
						&& castOther.getNumdoc() != null && this.getNumdoc().equals(castOther.getNumdoc())))
				&& (this.getOperac() == castOther.getOperac())
				&& ((this.getCodcli() == castOther.getCodcli()) || (this.getCodcli() != null
						&& castOther.getCodcli() != null && this.getCodcli().equals(castOther.getCodcli())))
				&& ((this.getIndica() == castOther.getIndica()) || (this.getIndica() != null
						&& castOther.getIndica() != null && this.getIndica().equals(castOther.getIndica())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + (getEjerci() == null ? 0 : this.getEjerci().hashCode());
		result = 37 * result + (getNumdoc() == null ? 0 : this.getNumdoc().hashCode());
		result = 37 * result + this.getOperac();
		result = 37 * result + (getCodcli() == null ? 0 : this.getCodcli().hashCode());
		result = 37 * result + (getIndica() == null ? 0 : this.getIndica().hashCode());
		return result;
	}

}
