package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Operwka generated by hbm2java
 */
public class Operwka implements java.io.Serializable {

	private OperwkaId id;

	public Operwka() {
	}

	public Operwka(OperwkaId id) {
		this.id = id;
	}

	public OperwkaId getId() {
		return this.id;
	}

	public void setId(OperwkaId id) {
		this.id = id;
	}

}
