package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Paises generated by hbm2java
 */
public class Paises implements java.io.Serializable {

	private short pais;
	private String nombre;
	private Short ranpro;
	private Integer rancpo;

	public Paises() {
	}

	public Paises(short pais, String nombre) {
		this.pais = pais;
		this.nombre = nombre;
	}

	public Paises(short pais, String nombre, Short ranpro, Integer rancpo) {
		this.pais = pais;
		this.nombre = nombre;
		this.ranpro = ranpro;
		this.rancpo = rancpo;
	}

	public short getPais() {
		return this.pais;
	}

	public void setPais(short pais) {
		this.pais = pais;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Short getRanpro() {
		return this.ranpro;
	}

	public void setRanpro(Short ranpro) {
		this.ranpro = ranpro;
	}

	public Integer getRancpo() {
		return this.rancpo;
	}

	public void setRancpo(Integer rancpo) {
		this.rancpo = rancpo;
	}

}
