package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Paispro generated by hbm2java
 */
public class Paispro implements java.io.Serializable {

	private PaisproId id;

	public Paispro() {
	}

	public Paispro(PaisproId id) {
		this.id = id;
	}

	public PaisproId getId() {
		return this.id;
	}

	public void setId(PaisproId id) {
		this.id = id;
	}

}
