package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * PaisproId generated by hbm2java
 */
public class PaisproId implements java.io.Serializable {

	private short pais;
	private short provin;
	private String nombre;

	public PaisproId() {
	}

	public PaisproId(short pais, short provin, String nombre) {
		this.pais = pais;
		this.provin = provin;
		this.nombre = nombre;
	}

	public short getPais() {
		return this.pais;
	}

	public void setPais(short pais) {
		this.pais = pais;
	}

	public short getProvin() {
		return this.provin;
	}

	public void setProvin(short provin) {
		this.provin = provin;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaisproId))
			return false;
		PaisproId castOther = (PaisproId) other;

		return (this.getPais() == castOther.getPais()) && (this.getProvin() == castOther.getProvin())
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPais();
		result = 37 * result + this.getProvin();
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		return result;
	}

}
