package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos implements java.io.Serializable {

	private PedidosId id;
	private Date fecped;
	private Character inddis;
	private Short totbul;
	private BigDecimal totkil;
	private BigDecimal totvol;
	private BigDecimal reembo;
	private BigDecimal imptot;
	private String nomtec;
	private String dirtec;
	private String pobtec;
	private Integer cpotec;
	private String codtec;
	private String observ;
	private String transp;
	private Character indser;
	private Character reserv;
	private Date fecent;
	private Character estado;
	private Character envweb;
	private String pobdis;
	private Integer cpodis;
	private String nomfis;
	private String refped;
	private Character valora;
	private Character apliva;
	private BigDecimal tipiva;
	private Short ejeope;
	private Integer numope;
	private Character finope;
	private String txtven;
	private String okpick;

	public Pedidos() {
	}

	public Pedidos(PedidosId id, Date fecped) {
		this.id = id;
		this.fecped = fecped;
	}

	public Pedidos(PedidosId id, Date fecped, Character inddis, Short totbul, BigDecimal totkil, BigDecimal totvol,
			BigDecimal reembo, BigDecimal imptot, String nomtec, String dirtec, String pobtec, Integer cpotec,
			String codtec, String observ, String transp, Character indser, Character reserv, Date fecent,
			Character estado, Character envweb, String pobdis, Integer cpodis, String nomfis, String refped,
			Character valora, Character apliva, BigDecimal tipiva, Short ejeope, Integer numope, Character finope,
			String txtven, String okpick) {
		this.id = id;
		this.fecped = fecped;
		this.inddis = inddis;
		this.totbul = totbul;
		this.totkil = totkil;
		this.totvol = totvol;
		this.reembo = reembo;
		this.imptot = imptot;
		this.nomtec = nomtec;
		this.dirtec = dirtec;
		this.pobtec = pobtec;
		this.cpotec = cpotec;
		this.codtec = codtec;
		this.observ = observ;
		this.transp = transp;
		this.indser = indser;
		this.reserv = reserv;
		this.fecent = fecent;
		this.estado = estado;
		this.envweb = envweb;
		this.pobdis = pobdis;
		this.cpodis = cpodis;
		this.nomfis = nomfis;
		this.refped = refped;
		this.valora = valora;
		this.apliva = apliva;
		this.tipiva = tipiva;
		this.ejeope = ejeope;
		this.numope = numope;
		this.finope = finope;
		this.txtven = txtven;
		this.okpick = okpick;
	}

	public PedidosId getId() {
		return this.id;
	}

	public void setId(PedidosId id) {
		this.id = id;
	}

	public Date getFecped() {
		return this.fecped;
	}

	public void setFecped(Date fecped) {
		this.fecped = fecped;
	}

	public Character getInddis() {
		return this.inddis;
	}

	public void setInddis(Character inddis) {
		this.inddis = inddis;
	}

	public Short getTotbul() {
		return this.totbul;
	}

	public void setTotbul(Short totbul) {
		this.totbul = totbul;
	}

	public BigDecimal getTotkil() {
		return this.totkil;
	}

	public void setTotkil(BigDecimal totkil) {
		this.totkil = totkil;
	}

	public BigDecimal getTotvol() {
		return this.totvol;
	}

	public void setTotvol(BigDecimal totvol) {
		this.totvol = totvol;
	}

	public BigDecimal getReembo() {
		return this.reembo;
	}

	public void setReembo(BigDecimal reembo) {
		this.reembo = reembo;
	}

	public BigDecimal getImptot() {
		return this.imptot;
	}

	public void setImptot(BigDecimal imptot) {
		this.imptot = imptot;
	}

	public String getNomtec() {
		return this.nomtec;
	}

	public void setNomtec(String nomtec) {
		this.nomtec = nomtec;
	}

	public String getDirtec() {
		return this.dirtec;
	}

	public void setDirtec(String dirtec) {
		this.dirtec = dirtec;
	}

	public String getPobtec() {
		return this.pobtec;
	}

	public void setPobtec(String pobtec) {
		this.pobtec = pobtec;
	}

	public Integer getCpotec() {
		return this.cpotec;
	}

	public void setCpotec(Integer cpotec) {
		this.cpotec = cpotec;
	}

	public String getCodtec() {
		return this.codtec;
	}

	public void setCodtec(String codtec) {
		this.codtec = codtec;
	}

	public String getObserv() {
		return this.observ;
	}

	public void setObserv(String observ) {
		this.observ = observ;
	}

	public String getTransp() {
		return this.transp;
	}

	public void setTransp(String transp) {
		this.transp = transp;
	}

	public Character getIndser() {
		return this.indser;
	}

	public void setIndser(Character indser) {
		this.indser = indser;
	}

	public Character getReserv() {
		return this.reserv;
	}

	public void setReserv(Character reserv) {
		this.reserv = reserv;
	}

	public Date getFecent() {
		return this.fecent;
	}

	public void setFecent(Date fecent) {
		this.fecent = fecent;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public Character getEnvweb() {
		return this.envweb;
	}

	public void setEnvweb(Character envweb) {
		this.envweb = envweb;
	}

	public String getPobdis() {
		return this.pobdis;
	}

	public void setPobdis(String pobdis) {
		this.pobdis = pobdis;
	}

	public Integer getCpodis() {
		return this.cpodis;
	}

	public void setCpodis(Integer cpodis) {
		this.cpodis = cpodis;
	}

	public String getNomfis() {
		return this.nomfis;
	}

	public void setNomfis(String nomfis) {
		this.nomfis = nomfis;
	}

	public String getRefped() {
		return this.refped;
	}

	public void setRefped(String refped) {
		this.refped = refped;
	}

	public Character getValora() {
		return this.valora;
	}

	public void setValora(Character valora) {
		this.valora = valora;
	}

	public Character getApliva() {
		return this.apliva;
	}

	public void setApliva(Character apliva) {
		this.apliva = apliva;
	}

	public BigDecimal getTipiva() {
		return this.tipiva;
	}

	public void setTipiva(BigDecimal tipiva) {
		this.tipiva = tipiva;
	}

	public Short getEjeope() {
		return this.ejeope;
	}

	public void setEjeope(Short ejeope) {
		this.ejeope = ejeope;
	}

	public Integer getNumope() {
		return this.numope;
	}

	public void setNumope(Integer numope) {
		this.numope = numope;
	}

	public Character getFinope() {
		return this.finope;
	}

	public void setFinope(Character finope) {
		this.finope = finope;
	}

	public String getTxtven() {
		return this.txtven;
	}

	public void setTxtven(String txtven) {
		this.txtven = txtven;
	}

	public String getOkpick() {
		return this.okpick;
	}

	public void setOkpick(String okpick) {
		this.okpick = okpick;
	}

}
