package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PelhaminId generated by hbm2java
 */
public class PelhaminId implements java.io.Serializable {

	private String empresa;
	private char entsal;
	private String nument;
	private Date fecrec;
	private String idclie;
	private String nomcli;
	private String domter;
	private String pobter;
	private String cpoter;
	private String prvter;
	private String paiter;
	private String tefter;
	private String faxter;
	private String observ;
	private String nconte;
	private String idline;
	private String idartic;
	private String localiz;
	private String pack;
	private Short pares;
	private String modelo;
	private String color;
	private String marca;
	private Integer cajas;
	private String codbar;
	private String codfis;
	private String nomfis;
	private short numlin;

	public PelhaminId() {
	}

	public PelhaminId(String empresa, char entsal, String idartic, String pack, short numlin) {
		this.empresa = empresa;
		this.entsal = entsal;
		this.idartic = idartic;
		this.pack = pack;
		this.numlin = numlin;
	}

	public PelhaminId(String empresa, char entsal, String nument, Date fecrec, String idclie, String nomcli,
			String domter, String pobter, String cpoter, String prvter, String paiter, String tefter, String faxter,
			String observ, String nconte, String idline, String idartic, String localiz, String pack, Short pares,
			String modelo, String color, String marca, Integer cajas, String codbar, String codfis, String nomfis,
			short numlin) {
		this.empresa = empresa;
		this.entsal = entsal;
		this.nument = nument;
		this.fecrec = fecrec;
		this.idclie = idclie;
		this.nomcli = nomcli;
		this.domter = domter;
		this.pobter = pobter;
		this.cpoter = cpoter;
		this.prvter = prvter;
		this.paiter = paiter;
		this.tefter = tefter;
		this.faxter = faxter;
		this.observ = observ;
		this.nconte = nconte;
		this.idline = idline;
		this.idartic = idartic;
		this.localiz = localiz;
		this.pack = pack;
		this.pares = pares;
		this.modelo = modelo;
		this.color = color;
		this.marca = marca;
		this.cajas = cajas;
		this.codbar = codbar;
		this.codfis = codfis;
		this.nomfis = nomfis;
		this.numlin = numlin;
	}

	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	public char getEntsal() {
		return this.entsal;
	}

	public void setEntsal(char entsal) {
		this.entsal = entsal;
	}

	public String getNument() {
		return this.nument;
	}

	public void setNument(String nument) {
		this.nument = nument;
	}

	public Date getFecrec() {
		return this.fecrec;
	}

	public void setFecrec(Date fecrec) {
		this.fecrec = fecrec;
	}

	public String getIdclie() {
		return this.idclie;
	}

	public void setIdclie(String idclie) {
		this.idclie = idclie;
	}

	public String getNomcli() {
		return this.nomcli;
	}

	public void setNomcli(String nomcli) {
		this.nomcli = nomcli;
	}

	public String getDomter() {
		return this.domter;
	}

	public void setDomter(String domter) {
		this.domter = domter;
	}

	public String getPobter() {
		return this.pobter;
	}

	public void setPobter(String pobter) {
		this.pobter = pobter;
	}

	public String getCpoter() {
		return this.cpoter;
	}

	public void setCpoter(String cpoter) {
		this.cpoter = cpoter;
	}

	public String getPrvter() {
		return this.prvter;
	}

	public void setPrvter(String prvter) {
		this.prvter = prvter;
	}

	public String getPaiter() {
		return this.paiter;
	}

	public void setPaiter(String paiter) {
		this.paiter = paiter;
	}

	public String getTefter() {
		return this.tefter;
	}

	public void setTefter(String tefter) {
		this.tefter = tefter;
	}

	public String getFaxter() {
		return this.faxter;
	}

	public void setFaxter(String faxter) {
		this.faxter = faxter;
	}

	public String getObserv() {
		return this.observ;
	}

	public void setObserv(String observ) {
		this.observ = observ;
	}

	public String getNconte() {
		return this.nconte;
	}

	public void setNconte(String nconte) {
		this.nconte = nconte;
	}

	public String getIdline() {
		return this.idline;
	}

	public void setIdline(String idline) {
		this.idline = idline;
	}

	public String getIdartic() {
		return this.idartic;
	}

	public void setIdartic(String idartic) {
		this.idartic = idartic;
	}

	public String getLocaliz() {
		return this.localiz;
	}

	public void setLocaliz(String localiz) {
		this.localiz = localiz;
	}

	public String getPack() {
		return this.pack;
	}

	public void setPack(String pack) {
		this.pack = pack;
	}

	public Short getPares() {
		return this.pares;
	}

	public void setPares(Short pares) {
		this.pares = pares;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public Integer getCajas() {
		return this.cajas;
	}

	public void setCajas(Integer cajas) {
		this.cajas = cajas;
	}

	public String getCodbar() {
		return this.codbar;
	}

	public void setCodbar(String codbar) {
		this.codbar = codbar;
	}

	public String getCodfis() {
		return this.codfis;
	}

	public void setCodfis(String codfis) {
		this.codfis = codfis;
	}

	public String getNomfis() {
		return this.nomfis;
	}

	public void setNomfis(String nomfis) {
		this.nomfis = nomfis;
	}

	public short getNumlin() {
		return this.numlin;
	}

	public void setNumlin(short numlin) {
		this.numlin = numlin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PelhaminId))
			return false;
		PelhaminId castOther = (PelhaminId) other;

		return ((this.getEmpresa() == castOther.getEmpresa()) || (this.getEmpresa() != null
				&& castOther.getEmpresa() != null && this.getEmpresa().equals(castOther.getEmpresa())))
				&& (this.getEntsal() == castOther.getEntsal())
				&& ((this.getNument() == castOther.getNument()) || (this.getNument() != null
						&& castOther.getNument() != null && this.getNument().equals(castOther.getNument())))
				&& ((this.getFecrec() == castOther.getFecrec()) || (this.getFecrec() != null
						&& castOther.getFecrec() != null && this.getFecrec().equals(castOther.getFecrec())))
				&& ((this.getIdclie() == castOther.getIdclie()) || (this.getIdclie() != null
						&& castOther.getIdclie() != null && this.getIdclie().equals(castOther.getIdclie())))
				&& ((this.getNomcli() == castOther.getNomcli()) || (this.getNomcli() != null
						&& castOther.getNomcli() != null && this.getNomcli().equals(castOther.getNomcli())))
				&& ((this.getDomter() == castOther.getDomter()) || (this.getDomter() != null
						&& castOther.getDomter() != null && this.getDomter().equals(castOther.getDomter())))
				&& ((this.getPobter() == castOther.getPobter()) || (this.getPobter() != null
						&& castOther.getPobter() != null && this.getPobter().equals(castOther.getPobter())))
				&& ((this.getCpoter() == castOther.getCpoter()) || (this.getCpoter() != null
						&& castOther.getCpoter() != null && this.getCpoter().equals(castOther.getCpoter())))
				&& ((this.getPrvter() == castOther.getPrvter()) || (this.getPrvter() != null
						&& castOther.getPrvter() != null && this.getPrvter().equals(castOther.getPrvter())))
				&& ((this.getPaiter() == castOther.getPaiter()) || (this.getPaiter() != null
						&& castOther.getPaiter() != null && this.getPaiter().equals(castOther.getPaiter())))
				&& ((this.getTefter() == castOther.getTefter()) || (this.getTefter() != null
						&& castOther.getTefter() != null && this.getTefter().equals(castOther.getTefter())))
				&& ((this.getFaxter() == castOther.getFaxter()) || (this.getFaxter() != null
						&& castOther.getFaxter() != null && this.getFaxter().equals(castOther.getFaxter())))
				&& ((this.getObserv() == castOther.getObserv()) || (this.getObserv() != null
						&& castOther.getObserv() != null && this.getObserv().equals(castOther.getObserv())))
				&& ((this.getNconte() == castOther.getNconte()) || (this.getNconte() != null
						&& castOther.getNconte() != null && this.getNconte().equals(castOther.getNconte())))
				&& ((this.getIdline() == castOther.getIdline()) || (this.getIdline() != null
						&& castOther.getIdline() != null && this.getIdline().equals(castOther.getIdline())))
				&& ((this.getIdartic() == castOther.getIdartic()) || (this.getIdartic() != null
						&& castOther.getIdartic() != null && this.getIdartic().equals(castOther.getIdartic())))
				&& ((this.getLocaliz() == castOther.getLocaliz()) || (this.getLocaliz() != null
						&& castOther.getLocaliz() != null && this.getLocaliz().equals(castOther.getLocaliz())))
				&& ((this.getPack() == castOther.getPack()) || (this.getPack() != null && castOther.getPack() != null
						&& this.getPack().equals(castOther.getPack())))
				&& ((this.getPares() == castOther.getPares()) || (this.getPares() != null
						&& castOther.getPares() != null && this.getPares().equals(castOther.getPares())))
				&& ((this.getModelo() == castOther.getModelo()) || (this.getModelo() != null
						&& castOther.getModelo() != null && this.getModelo().equals(castOther.getModelo())))
				&& ((this.getColor() == castOther.getColor()) || (this.getColor() != null
						&& castOther.getColor() != null && this.getColor().equals(castOther.getColor())))
				&& ((this.getMarca() == castOther.getMarca()) || (this.getMarca() != null
						&& castOther.getMarca() != null && this.getMarca().equals(castOther.getMarca())))
				&& ((this.getCajas() == castOther.getCajas()) || (this.getCajas() != null
						&& castOther.getCajas() != null && this.getCajas().equals(castOther.getCajas())))
				&& ((this.getCodbar() == castOther.getCodbar()) || (this.getCodbar() != null
						&& castOther.getCodbar() != null && this.getCodbar().equals(castOther.getCodbar())))
				&& ((this.getCodfis() == castOther.getCodfis()) || (this.getCodfis() != null
						&& castOther.getCodfis() != null && this.getCodfis().equals(castOther.getCodfis())))
				&& ((this.getNomfis() == castOther.getNomfis()) || (this.getNomfis() != null
						&& castOther.getNomfis() != null && this.getNomfis().equals(castOther.getNomfis())))
				&& (this.getNumlin() == castOther.getNumlin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmpresa() == null ? 0 : this.getEmpresa().hashCode());
		result = 37 * result + this.getEntsal();
		result = 37 * result + (getNument() == null ? 0 : this.getNument().hashCode());
		result = 37 * result + (getFecrec() == null ? 0 : this.getFecrec().hashCode());
		result = 37 * result + (getIdclie() == null ? 0 : this.getIdclie().hashCode());
		result = 37 * result + (getNomcli() == null ? 0 : this.getNomcli().hashCode());
		result = 37 * result + (getDomter() == null ? 0 : this.getDomter().hashCode());
		result = 37 * result + (getPobter() == null ? 0 : this.getPobter().hashCode());
		result = 37 * result + (getCpoter() == null ? 0 : this.getCpoter().hashCode());
		result = 37 * result + (getPrvter() == null ? 0 : this.getPrvter().hashCode());
		result = 37 * result + (getPaiter() == null ? 0 : this.getPaiter().hashCode());
		result = 37 * result + (getTefter() == null ? 0 : this.getTefter().hashCode());
		result = 37 * result + (getFaxter() == null ? 0 : this.getFaxter().hashCode());
		result = 37 * result + (getObserv() == null ? 0 : this.getObserv().hashCode());
		result = 37 * result + (getNconte() == null ? 0 : this.getNconte().hashCode());
		result = 37 * result + (getIdline() == null ? 0 : this.getIdline().hashCode());
		result = 37 * result + (getIdartic() == null ? 0 : this.getIdartic().hashCode());
		result = 37 * result + (getLocaliz() == null ? 0 : this.getLocaliz().hashCode());
		result = 37 * result + (getPack() == null ? 0 : this.getPack().hashCode());
		result = 37 * result + (getPares() == null ? 0 : this.getPares().hashCode());
		result = 37 * result + (getModelo() == null ? 0 : this.getModelo().hashCode());
		result = 37 * result + (getColor() == null ? 0 : this.getColor().hashCode());
		result = 37 * result + (getMarca() == null ? 0 : this.getMarca().hashCode());
		result = 37 * result + (getCajas() == null ? 0 : this.getCajas().hashCode());
		result = 37 * result + (getCodbar() == null ? 0 : this.getCodbar().hashCode());
		result = 37 * result + (getCodfis() == null ? 0 : this.getCodfis().hashCode());
		result = 37 * result + (getNomfis() == null ? 0 : this.getNomfis().hashCode());
		result = 37 * result + this.getNumlin();
		return result;
	}

}
