package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Pelhamin generated by hbm2java
 */
public class Pelhamin implements java.io.Serializable {

	private PelhaminId id;

	public Pelhamin() {
	}

	public Pelhamin(PelhaminId id) {
		this.id = id;
	}

	public PelhaminId getId() {
		return this.id;
	}

	public void setId(PelhaminId id) {
		this.id = id;
	}

}
