package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Picking generated by hbm2java
 */
public class Picking implements java.io.Serializable {

	private PickingId id;

	public Picking() {
	}

	public Picking(PickingId id) {
		this.id = id;
	}

	public PickingId getId() {
		return this.id;
	}

	public void setId(PickingId id) {
		this.id = id;
	}

}
