package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Pickped generated by hbm2java
 */
public class Pickped implements java.io.Serializable {

	private PickpedId id;

	public Pickped() {
	}

	public Pickped(PickpedId id) {
		this.id = id;
	}

	public PickpedId getId() {
		return this.id;
	}

	public void setId(PickpedId id) {
		this.id = id;
	}

}
