package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Pobalma generated by hbm2java
 */
public class Pobalma implements java.io.Serializable {

	private PobalmaId id;
	private Character barrxp;
	private Short codtra;
	private Short grupo;

	public Pobalma() {
	}

	public Pobalma(PobalmaId id) {
		this.id = id;
	}

	public Pobalma(PobalmaId id, Character barrxp, Short codtra, Short grupo) {
		this.id = id;
		this.barrxp = barrxp;
		this.codtra = codtra;
		this.grupo = grupo;
	}

	public PobalmaId getId() {
		return this.id;
	}

	public void setId(PobalmaId id) {
		this.id = id;
	}

	public Character getBarrxp() {
		return this.barrxp;
	}

	public void setBarrxp(Character barrxp) {
		this.barrxp = barrxp;
	}

	public Short getCodtra() {
		return this.codtra;
	}

	public void setCodtra(Short codtra) {
		this.codtra = codtra;
	}

	public Short getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Short grupo) {
		this.grupo = grupo;
	}

}
