package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Pobagen generated by hbm2java
 */
public class Pobagen implements java.io.Serializable {

	private PobagenId id;
	private Short plztas;
	private char aplrxp;

	public Pobagen() {
	}

	public Pobagen(PobagenId id, char aplrxp) {
		this.id = id;
		this.aplrxp = aplrxp;
	}

	public Pobagen(PobagenId id, Short plztas, char aplrxp) {
		this.id = id;
		this.plztas = plztas;
		this.aplrxp = aplrxp;
	}

	public PobagenId getId() {
		return this.id;
	}

	public void setId(PobagenId id) {
		this.id = id;
	}

	public Short getPlztas() {
		return this.plztas;
	}

	public void setPlztas(Short plztas) {
		this.plztas = plztas;
	}

	public char getAplrxp() {
		return this.aplrxp;
	}

	public void setAplrxp(char aplrxp) {
		this.aplrxp = aplrxp;
	}

}
