package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Poblaci generated by hbm2java
 */
public class Poblaci implements java.io.Serializable {

	private String nombre;
	private int numero;
	private short pais;
	private short provin;
	private Integer cpoini;
	private Integer cpofin;

	public Poblaci() {
	}

	public Poblaci(String nombre, int numero, short pais, short provin) {
		this.nombre = nombre;
		this.numero = numero;
		this.pais = pais;
		this.provin = provin;
	}

	public Poblaci(String nombre, int numero, short pais, short provin, Integer cpoini, Integer cpofin) {
		this.nombre = nombre;
		this.numero = numero;
		this.pais = pais;
		this.provin = provin;
		this.cpoini = cpoini;
		this.cpofin = cpofin;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public short getPais() {
		return this.pais;
	}

	public void setPais(short pais) {
		this.pais = pais;
	}

	public short getProvin() {
		return this.provin;
	}

	public void setProvin(short provin) {
		this.provin = provin;
	}

	public Integer getCpoini() {
		return this.cpoini;
	}

	public void setCpoini(Integer cpoini) {
		this.cpoini = cpoini;
	}

	public Integer getCpofin() {
		return this.cpofin;
	}

	public void setCpofin(Integer cpofin) {
		this.cpofin = cpofin;
	}

}
