package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * PrefactuId generated by hbm2java
 */
public class PrefactuId implements java.io.Serializable {

	private Short codcli;
	private String aplica;
	private String bastar;
	private Short numtar;
	private Character tipcal;
	private Short diacal;
	private Character grufac;
	private BigDecimal dtofac;
	private Short coddel;
	private Character omitir;

	public PrefactuId() {
	}

	public PrefactuId(Short codcli, String aplica, String bastar, Short numtar, Character tipcal, Short diacal,
			Character grufac, BigDecimal dtofac, Short coddel, Character omitir) {
		this.codcli = codcli;
		this.aplica = aplica;
		this.bastar = bastar;
		this.numtar = numtar;
		this.tipcal = tipcal;
		this.diacal = diacal;
		this.grufac = grufac;
		this.dtofac = dtofac;
		this.coddel = coddel;
		this.omitir = omitir;
	}

	public Short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(Short codcli) {
		this.codcli = codcli;
	}

	public String getAplica() {
		return this.aplica;
	}

	public void setAplica(String aplica) {
		this.aplica = aplica;
	}

	public String getBastar() {
		return this.bastar;
	}

	public void setBastar(String bastar) {
		this.bastar = bastar;
	}

	public Short getNumtar() {
		return this.numtar;
	}

	public void setNumtar(Short numtar) {
		this.numtar = numtar;
	}

	public Character getTipcal() {
		return this.tipcal;
	}

	public void setTipcal(Character tipcal) {
		this.tipcal = tipcal;
	}

	public Short getDiacal() {
		return this.diacal;
	}

	public void setDiacal(Short diacal) {
		this.diacal = diacal;
	}

	public Character getGrufac() {
		return this.grufac;
	}

	public void setGrufac(Character grufac) {
		this.grufac = grufac;
	}

	public BigDecimal getDtofac() {
		return this.dtofac;
	}

	public void setDtofac(BigDecimal dtofac) {
		this.dtofac = dtofac;
	}

	public Short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(Short coddel) {
		this.coddel = coddel;
	}

	public Character getOmitir() {
		return this.omitir;
	}

	public void setOmitir(Character omitir) {
		this.omitir = omitir;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrefactuId))
			return false;
		PrefactuId castOther = (PrefactuId) other;

		return ((this.getCodcli() == castOther.getCodcli()) || (this.getCodcli() != null
				&& castOther.getCodcli() != null && this.getCodcli().equals(castOther.getCodcli())))
				&& ((this.getAplica() == castOther.getAplica()) || (this.getAplica() != null
						&& castOther.getAplica() != null && this.getAplica().equals(castOther.getAplica())))
				&& ((this.getBastar() == castOther.getBastar()) || (this.getBastar() != null
						&& castOther.getBastar() != null && this.getBastar().equals(castOther.getBastar())))
				&& ((this.getNumtar() == castOther.getNumtar()) || (this.getNumtar() != null
						&& castOther.getNumtar() != null && this.getNumtar().equals(castOther.getNumtar())))
				&& ((this.getTipcal() == castOther.getTipcal()) || (this.getTipcal() != null
						&& castOther.getTipcal() != null && this.getTipcal().equals(castOther.getTipcal())))
				&& ((this.getDiacal() == castOther.getDiacal()) || (this.getDiacal() != null
						&& castOther.getDiacal() != null && this.getDiacal().equals(castOther.getDiacal())))
				&& ((this.getGrufac() == castOther.getGrufac()) || (this.getGrufac() != null
						&& castOther.getGrufac() != null && this.getGrufac().equals(castOther.getGrufac())))
				&& ((this.getDtofac() == castOther.getDtofac()) || (this.getDtofac() != null
						&& castOther.getDtofac() != null && this.getDtofac().equals(castOther.getDtofac())))
				&& ((this.getCoddel() == castOther.getCoddel()) || (this.getCoddel() != null
						&& castOther.getCoddel() != null && this.getCoddel().equals(castOther.getCoddel())))
				&& ((this.getOmitir() == castOther.getOmitir()) || (this.getOmitir() != null
						&& castOther.getOmitir() != null && this.getOmitir().equals(castOther.getOmitir())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodcli() == null ? 0 : this.getCodcli().hashCode());
		result = 37 * result + (getAplica() == null ? 0 : this.getAplica().hashCode());
		result = 37 * result + (getBastar() == null ? 0 : this.getBastar().hashCode());
		result = 37 * result + (getNumtar() == null ? 0 : this.getNumtar().hashCode());
		result = 37 * result + (getTipcal() == null ? 0 : this.getTipcal().hashCode());
		result = 37 * result + (getDiacal() == null ? 0 : this.getDiacal().hashCode());
		result = 37 * result + (getGrufac() == null ? 0 : this.getGrufac().hashCode());
		result = 37 * result + (getDtofac() == null ? 0 : this.getDtofac().hashCode());
		result = 37 * result + (getCoddel() == null ? 0 : this.getCoddel().hashCode());
		result = 37 * result + (getOmitir() == null ? 0 : this.getOmitir().hashCode());
		return result;
	}

}
