package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * PueblosId generated by hbm2java
 */
public class PueblosId implements java.io.Serializable {

	private Integer codigo;
	private String nompob;
	private String ruta;

	public PueblosId() {
	}

	public PueblosId(Integer codigo, String nompob, String ruta) {
		this.codigo = codigo;
		this.nompob = nompob;
		this.ruta = ruta;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getNompob() {
		return this.nompob;
	}

	public void setNompob(String nompob) {
		this.nompob = nompob;
	}

	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PueblosId))
			return false;
		PueblosId castOther = (PueblosId) other;

		return ((this.getCodigo() == castOther.getCodigo()) || (this.getCodigo() != null
				&& castOther.getCodigo() != null && this.getCodigo().equals(castOther.getCodigo())))
				&& ((this.getNompob() == castOther.getNompob()) || (this.getNompob() != null
						&& castOther.getNompob() != null && this.getNompob().equals(castOther.getNompob())))
				&& ((this.getRuta() == castOther.getRuta()) || (this.getRuta() != null && castOther.getRuta() != null
						&& this.getRuta().equals(castOther.getRuta())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodigo() == null ? 0 : this.getCodigo().hashCode());
		result = 37 * result + (getNompob() == null ? 0 : this.getNompob().hashCode());
		result = 37 * result + (getRuta() == null ? 0 : this.getRuta().hashCode());
		return result;
	}

}
