package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Pueblos generated by hbm2java
 */
public class Pueblos implements java.io.Serializable {

	private PueblosId id;

	public Pueblos() {
	}

	public Pueblos(PueblosId id) {
		this.id = id;
	}

	public PueblosId getId() {
		return this.id;
	}

	public void setId(PueblosId id) {
		this.id = id;
	}

}
