package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Reembolsos generated by hbm2java
 */
public class Reembolsos implements java.io.Serializable {

	private ReembolsosId id;

	public Reembolsos() {
	}

	public Reembolsos(ReembolsosId id) {
		this.id = id;
	}

	public ReembolsosId getId() {
		return this.id;
	}

	public void setId(ReembolsosId id) {
		this.id = id;
	}

}
