package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ReembolsosId generated by hbm2java
 */
public class ReembolsosId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private short codcli;
	private char tipalb;
	private char seralb;
	private short ejerci;
	private int numalb;
	private Short codtra;
	private Date fecalb;
	private Date fecexp;
	private Date feccob;
	private Date fecliq;
	private Character codliq;
	private BigDecimal reembo;
	private String observ;
	private Short cenfac;
	private Character serfac;
	private Short ejefac;
	private Integer numfac;

	public ReembolsosId() {
	}

	public ReembolsosId(short codemp, short coddel, short codcli, char tipalb, char seralb, short ejerci, int numalb,
			Date fecalb) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.codcli = codcli;
		this.tipalb = tipalb;
		this.seralb = seralb;
		this.ejerci = ejerci;
		this.numalb = numalb;
		this.fecalb = fecalb;
	}

	public ReembolsosId(short codemp, short coddel, short codcli, char tipalb, char seralb, short ejerci, int numalb,
			Short codtra, Date fecalb, Date fecexp, Date feccob, Date fecliq, Character codliq, BigDecimal reembo,
			String observ, Short cenfac, Character serfac, Short ejefac, Integer numfac) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.codcli = codcli;
		this.tipalb = tipalb;
		this.seralb = seralb;
		this.ejerci = ejerci;
		this.numalb = numalb;
		this.codtra = codtra;
		this.fecalb = fecalb;
		this.fecexp = fecexp;
		this.feccob = feccob;
		this.fecliq = fecliq;
		this.codliq = codliq;
		this.reembo = reembo;
		this.observ = observ;
		this.cenfac = cenfac;
		this.serfac = serfac;
		this.ejefac = ejefac;
		this.numfac = numfac;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public char getTipalb() {
		return this.tipalb;
	}

	public void setTipalb(char tipalb) {
		this.tipalb = tipalb;
	}

	public char getSeralb() {
		return this.seralb;
	}

	public void setSeralb(char seralb) {
		this.seralb = seralb;
	}

	public short getEjerci() {
		return this.ejerci;
	}

	public void setEjerci(short ejerci) {
		this.ejerci = ejerci;
	}

	public int getNumalb() {
		return this.numalb;
	}

	public void setNumalb(int numalb) {
		this.numalb = numalb;
	}

	public Short getCodtra() {
		return this.codtra;
	}

	public void setCodtra(Short codtra) {
		this.codtra = codtra;
	}

	public Date getFecalb() {
		return this.fecalb;
	}

	public void setFecalb(Date fecalb) {
		this.fecalb = fecalb;
	}

	public Date getFecexp() {
		return this.fecexp;
	}

	public void setFecexp(Date fecexp) {
		this.fecexp = fecexp;
	}

	public Date getFeccob() {
		return this.feccob;
	}

	public void setFeccob(Date feccob) {
		this.feccob = feccob;
	}

	public Date getFecliq() {
		return this.fecliq;
	}

	public void setFecliq(Date fecliq) {
		this.fecliq = fecliq;
	}

	public Character getCodliq() {
		return this.codliq;
	}

	public void setCodliq(Character codliq) {
		this.codliq = codliq;
	}

	public BigDecimal getReembo() {
		return this.reembo;
	}

	public void setReembo(BigDecimal reembo) {
		this.reembo = reembo;
	}

	public String getObserv() {
		return this.observ;
	}

	public void setObserv(String observ) {
		this.observ = observ;
	}

	public Short getCenfac() {
		return this.cenfac;
	}

	public void setCenfac(Short cenfac) {
		this.cenfac = cenfac;
	}

	public Character getSerfac() {
		return this.serfac;
	}

	public void setSerfac(Character serfac) {
		this.serfac = serfac;
	}

	public Short getEjefac() {
		return this.ejefac;
	}

	public void setEjefac(Short ejefac) {
		this.ejefac = ejefac;
	}

	public Integer getNumfac() {
		return this.numfac;
	}

	public void setNumfac(Integer numfac) {
		this.numfac = numfac;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReembolsosId))
			return false;
		ReembolsosId castOther = (ReembolsosId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& (this.getCodcli() == castOther.getCodcli()) && (this.getTipalb() == castOther.getTipalb())
				&& (this.getSeralb() == castOther.getSeralb()) && (this.getEjerci() == castOther.getEjerci())
				&& (this.getNumalb() == castOther.getNumalb())
				&& ((this.getCodtra() == castOther.getCodtra()) || (this.getCodtra() != null
						&& castOther.getCodtra() != null && this.getCodtra().equals(castOther.getCodtra())))
				&& ((this.getFecalb() == castOther.getFecalb()) || (this.getFecalb() != null
						&& castOther.getFecalb() != null && this.getFecalb().equals(castOther.getFecalb())))
				&& ((this.getFecexp() == castOther.getFecexp()) || (this.getFecexp() != null
						&& castOther.getFecexp() != null && this.getFecexp().equals(castOther.getFecexp())))
				&& ((this.getFeccob() == castOther.getFeccob()) || (this.getFeccob() != null
						&& castOther.getFeccob() != null && this.getFeccob().equals(castOther.getFeccob())))
				&& ((this.getFecliq() == castOther.getFecliq()) || (this.getFecliq() != null
						&& castOther.getFecliq() != null && this.getFecliq().equals(castOther.getFecliq())))
				&& ((this.getCodliq() == castOther.getCodliq()) || (this.getCodliq() != null
						&& castOther.getCodliq() != null && this.getCodliq().equals(castOther.getCodliq())))
				&& ((this.getReembo() == castOther.getReembo()) || (this.getReembo() != null
						&& castOther.getReembo() != null && this.getReembo().equals(castOther.getReembo())))
				&& ((this.getObserv() == castOther.getObserv()) || (this.getObserv() != null
						&& castOther.getObserv() != null && this.getObserv().equals(castOther.getObserv())))
				&& ((this.getCenfac() == castOther.getCenfac()) || (this.getCenfac() != null
						&& castOther.getCenfac() != null && this.getCenfac().equals(castOther.getCenfac())))
				&& ((this.getSerfac() == castOther.getSerfac()) || (this.getSerfac() != null
						&& castOther.getSerfac() != null && this.getSerfac().equals(castOther.getSerfac())))
				&& ((this.getEjefac() == castOther.getEjefac()) || (this.getEjefac() != null
						&& castOther.getEjefac() != null && this.getEjefac().equals(castOther.getEjefac())))
				&& ((this.getNumfac() == castOther.getNumfac()) || (this.getNumfac() != null
						&& castOther.getNumfac() != null && this.getNumfac().equals(castOther.getNumfac())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + this.getCodcli();
		result = 37 * result + this.getTipalb();
		result = 37 * result + this.getSeralb();
		result = 37 * result + this.getEjerci();
		result = 37 * result + this.getNumalb();
		result = 37 * result + (getCodtra() == null ? 0 : this.getCodtra().hashCode());
		result = 37 * result + (getFecalb() == null ? 0 : this.getFecalb().hashCode());
		result = 37 * result + (getFecexp() == null ? 0 : this.getFecexp().hashCode());
		result = 37 * result + (getFeccob() == null ? 0 : this.getFeccob().hashCode());
		result = 37 * result + (getFecliq() == null ? 0 : this.getFecliq().hashCode());
		result = 37 * result + (getCodliq() == null ? 0 : this.getCodliq().hashCode());
		result = 37 * result + (getReembo() == null ? 0 : this.getReembo().hashCode());
		result = 37 * result + (getObserv() == null ? 0 : this.getObserv().hashCode());
		result = 37 * result + (getCenfac() == null ? 0 : this.getCenfac().hashCode());
		result = 37 * result + (getSerfac() == null ? 0 : this.getSerfac().hashCode());
		result = 37 * result + (getEjefac() == null ? 0 : this.getEjefac().hashCode());
		result = 37 * result + (getNumfac() == null ? 0 : this.getNumfac().hashCode());
		return result;
	}

}
