package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RepartosId generated by hbm2java
 */
public class RepartosId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private short ejevue;
	private int numero;
	private short numveh;
	private Date fecvue;
	private Date fecliq;

	public RepartosId() {
	}

	public RepartosId(short codemp, short coddel, short ejevue, int numero, short numveh, Date fecvue) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.ejevue = ejevue;
		this.numero = numero;
		this.numveh = numveh;
		this.fecvue = fecvue;
	}

	public RepartosId(short codemp, short coddel, short ejevue, int numero, short numveh, Date fecvue, Date fecliq) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.ejevue = ejevue;
		this.numero = numero;
		this.numveh = numveh;
		this.fecvue = fecvue;
		this.fecliq = fecliq;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public short getEjevue() {
		return this.ejevue;
	}

	public void setEjevue(short ejevue) {
		this.ejevue = ejevue;
	}

	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public short getNumveh() {
		return this.numveh;
	}

	public void setNumveh(short numveh) {
		this.numveh = numveh;
	}

	public Date getFecvue() {
		return this.fecvue;
	}

	public void setFecvue(Date fecvue) {
		this.fecvue = fecvue;
	}

	public Date getFecliq() {
		return this.fecliq;
	}

	public void setFecliq(Date fecliq) {
		this.fecliq = fecliq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RepartosId))
			return false;
		RepartosId castOther = (RepartosId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& (this.getEjevue() == castOther.getEjevue()) && (this.getNumero() == castOther.getNumero())
				&& (this.getNumveh() == castOther.getNumveh())
				&& ((this.getFecvue() == castOther.getFecvue()) || (this.getFecvue() != null
						&& castOther.getFecvue() != null && this.getFecvue().equals(castOther.getFecvue())))
				&& ((this.getFecliq() == castOther.getFecliq()) || (this.getFecliq() != null
						&& castOther.getFecliq() != null && this.getFecliq().equals(castOther.getFecliq())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + this.getEjevue();
		result = 37 * result + this.getNumero();
		result = 37 * result + this.getNumveh();
		result = 37 * result + (getFecvue() == null ? 0 : this.getFecvue().hashCode());
		result = 37 * result + (getFecliq() == null ? 0 : this.getFecliq().hashCode());
		return result;
	}

}
