package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Repartos generated by hbm2java
 */
public class Repartos implements java.io.Serializable {

	private RepartosId id;

	public Repartos() {
	}

	public Repartos(RepartosId id) {
		this.id = id;
	}

	public RepartosId getId() {
		return this.id;
	}

	public void setId(RepartosId id) {
		this.id = id;
	}

}
