package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * ServiciosId generated by hbm2java
 */
public class ServiciosId implements java.io.Serializable {

	private short codemp;
	private String aplica;

	public ServiciosId() {
	}

	public ServiciosId(short codemp, String aplica) {
		this.codemp = codemp;
		this.aplica = aplica;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public String getAplica() {
		return this.aplica;
	}

	public void setAplica(String aplica) {
		this.aplica = aplica;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServiciosId))
			return false;
		ServiciosId castOther = (ServiciosId) other;

		return (this.getCodemp() == castOther.getCodemp())
				&& ((this.getAplica() == castOther.getAplica()) || (this.getAplica() != null
						&& castOther.getAplica() != null && this.getAplica().equals(castOther.getAplica())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + (getAplica() == null ? 0 : this.getAplica().hashCode());
		return result;
	}

}
