package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Servstk generated by hbm2java
 */
public class Servstk implements java.io.Serializable {

	private ServstkId id;

	public Servstk() {
	}

	public Servstk(ServstkId id) {
		this.id = id;
	}

	public ServstkId getId() {
		return this.id;
	}

	public void setId(ServstkId id) {
		this.id = id;
	}

}
