package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Servlpe generated by hbm2java
 */
public class Servlpe implements java.io.Serializable {

	private ServlpeId id;

	public Servlpe() {
	}

	public Servlpe(ServlpeId id) {
		this.id = id;
	}

	public ServlpeId getId() {
		return this.id;
	}

	public void setId(ServlpeId id) {
		this.id = id;
	}

}
