package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Servped generated by hbm2java
 */
public class Servped implements java.io.Serializable {

	private ServpedId id;

	public Servped() {
	}

	public Servped(ServpedId id) {
		this.id = id;
	}

	public ServpedId getId() {
		return this.id;
	}

	public void setId(ServpedId id) {
		this.id = id;
	}

}
