package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ServstkId generated by hbm2java
 */
public class ServstkId implements java.io.Serializable {

	private Short ntermi;
	private Short codcli;
	private String codart;
	private BigDecimal stkdsp;

	public ServstkId() {
	}

	public ServstkId(Short ntermi, Short codcli, String codart, BigDecimal stkdsp) {
		this.ntermi = ntermi;
		this.codcli = codcli;
		this.codart = codart;
		this.stkdsp = stkdsp;
	}

	public Short getNtermi() {
		return this.ntermi;
	}

	public void setNtermi(Short ntermi) {
		this.ntermi = ntermi;
	}

	public Short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(Short codcli) {
		this.codcli = codcli;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public BigDecimal getStkdsp() {
		return this.stkdsp;
	}

	public void setStkdsp(BigDecimal stkdsp) {
		this.stkdsp = stkdsp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServstkId))
			return false;
		ServstkId castOther = (ServstkId) other;

		return ((this.getNtermi() == castOther.getNtermi()) || (this.getNtermi() != null
				&& castOther.getNtermi() != null && this.getNtermi().equals(castOther.getNtermi())))
				&& ((this.getCodcli() == castOther.getCodcli()) || (this.getCodcli() != null
						&& castOther.getCodcli() != null && this.getCodcli().equals(castOther.getCodcli())))
				&& ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
						&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())))
				&& ((this.getStkdsp() == castOther.getStkdsp()) || (this.getStkdsp() != null
						&& castOther.getStkdsp() != null && this.getStkdsp().equals(castOther.getStkdsp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNtermi() == null ? 0 : this.getNtermi().hashCode());
		result = 37 * result + (getCodcli() == null ? 0 : this.getCodcli().hashCode());
		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		result = 37 * result + (getStkdsp() == null ? 0 : this.getStkdsp().hashCode());
		return result;
	}

}
