package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Servicios generated by hbm2java
 */
public class Servicios implements java.io.Serializable {

	private ServiciosId id;
	private String dscapl;

	public Servicios() {
	}

	public Servicios(ServiciosId id, String dscapl) {
		this.id = id;
		this.dscapl = dscapl;
	}

	public ServiciosId getId() {
		return this.id;
	}

	public void setId(ServiciosId id) {
		this.id = id;
	}

	public String getDscapl() {
		return this.dscapl;
	}

	public void setDscapl(String dscapl) {
		this.dscapl = dscapl;
	}

}
