package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * SisagendaId generated by hbm2java
 */
public class SisagendaId implements java.io.Serializable {

	private String sislog;
	private String nombre;
	private Character lectur;
	private String clogin;
	private String contra;
	private String horari;
	private String cmodem;
	private String baudio;
	private char protoc;
	private String telefo;
	private String lecdir;
	private String escdir;

	public SisagendaId() {
	}

	public SisagendaId(String sislog, String nombre, String clogin, String horari, String cmodem, String baudio,
			char protoc) {
		this.sislog = sislog;
		this.nombre = nombre;
		this.clogin = clogin;
		this.horari = horari;
		this.cmodem = cmodem;
		this.baudio = baudio;
		this.protoc = protoc;
	}

	public SisagendaId(String sislog, String nombre, Character lectur, String clogin, String contra, String horari,
			String cmodem, String baudio, char protoc, String telefo, String lecdir, String escdir) {
		this.sislog = sislog;
		this.nombre = nombre;
		this.lectur = lectur;
		this.clogin = clogin;
		this.contra = contra;
		this.horari = horari;
		this.cmodem = cmodem;
		this.baudio = baudio;
		this.protoc = protoc;
		this.telefo = telefo;
		this.lecdir = lecdir;
		this.escdir = escdir;
	}

	public String getSislog() {
		return this.sislog;
	}

	public void setSislog(String sislog) {
		this.sislog = sislog;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Character getLectur() {
		return this.lectur;
	}

	public void setLectur(Character lectur) {
		this.lectur = lectur;
	}

	public String getClogin() {
		return this.clogin;
	}

	public void setClogin(String clogin) {
		this.clogin = clogin;
	}

	public String getContra() {
		return this.contra;
	}

	public void setContra(String contra) {
		this.contra = contra;
	}

	public String getHorari() {
		return this.horari;
	}

	public void setHorari(String horari) {
		this.horari = horari;
	}

	public String getCmodem() {
		return this.cmodem;
	}

	public void setCmodem(String cmodem) {
		this.cmodem = cmodem;
	}

	public String getBaudio() {
		return this.baudio;
	}

	public void setBaudio(String baudio) {
		this.baudio = baudio;
	}

	public char getProtoc() {
		return this.protoc;
	}

	public void setProtoc(char protoc) {
		this.protoc = protoc;
	}

	public String getTelefo() {
		return this.telefo;
	}

	public void setTelefo(String telefo) {
		this.telefo = telefo;
	}

	public String getLecdir() {
		return this.lecdir;
	}

	public void setLecdir(String lecdir) {
		this.lecdir = lecdir;
	}

	public String getEscdir() {
		return this.escdir;
	}

	public void setEscdir(String escdir) {
		this.escdir = escdir;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SisagendaId))
			return false;
		SisagendaId castOther = (SisagendaId) other;

		return ((this.getSislog() == castOther.getSislog()) || (this.getSislog() != null
				&& castOther.getSislog() != null && this.getSislog().equals(castOther.getSislog())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getLectur() == castOther.getLectur()) || (this.getLectur() != null
						&& castOther.getLectur() != null && this.getLectur().equals(castOther.getLectur())))
				&& ((this.getClogin() == castOther.getClogin()) || (this.getClogin() != null
						&& castOther.getClogin() != null && this.getClogin().equals(castOther.getClogin())))
				&& ((this.getContra() == castOther.getContra()) || (this.getContra() != null
						&& castOther.getContra() != null && this.getContra().equals(castOther.getContra())))
				&& ((this.getHorari() == castOther.getHorari()) || (this.getHorari() != null
						&& castOther.getHorari() != null && this.getHorari().equals(castOther.getHorari())))
				&& ((this.getCmodem() == castOther.getCmodem()) || (this.getCmodem() != null
						&& castOther.getCmodem() != null && this.getCmodem().equals(castOther.getCmodem())))
				&& ((this.getBaudio() == castOther.getBaudio()) || (this.getBaudio() != null
						&& castOther.getBaudio() != null && this.getBaudio().equals(castOther.getBaudio())))
				&& (this.getProtoc() == castOther.getProtoc())
				&& ((this.getTelefo() == castOther.getTelefo()) || (this.getTelefo() != null
						&& castOther.getTelefo() != null && this.getTelefo().equals(castOther.getTelefo())))
				&& ((this.getLecdir() == castOther.getLecdir()) || (this.getLecdir() != null
						&& castOther.getLecdir() != null && this.getLecdir().equals(castOther.getLecdir())))
				&& ((this.getEscdir() == castOther.getEscdir()) || (this.getEscdir() != null
						&& castOther.getEscdir() != null && this.getEscdir().equals(castOther.getEscdir())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSislog() == null ? 0 : this.getSislog().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getLectur() == null ? 0 : this.getLectur().hashCode());
		result = 37 * result + (getClogin() == null ? 0 : this.getClogin().hashCode());
		result = 37 * result + (getContra() == null ? 0 : this.getContra().hashCode());
		result = 37 * result + (getHorari() == null ? 0 : this.getHorari().hashCode());
		result = 37 * result + (getCmodem() == null ? 0 : this.getCmodem().hashCode());
		result = 37 * result + (getBaudio() == null ? 0 : this.getBaudio().hashCode());
		result = 37 * result + this.getProtoc();
		result = 37 * result + (getTelefo() == null ? 0 : this.getTelefo().hashCode());
		result = 37 * result + (getLecdir() == null ? 0 : this.getLecdir().hashCode());
		result = 37 * result + (getEscdir() == null ? 0 : this.getEscdir().hashCode());
		return result;
	}

}
