package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Sisagenda generated by hbm2java
 */
public class Sisagenda implements java.io.Serializable {

	private SisagendaId id;

	public Sisagenda() {
	}

	public Sisagenda(SisagendaId id) {
		this.id = id;
	}

	public SisagendaId getId() {
		return this.id;
	}

	public void setId(SisagendaId id) {
		this.id = id;
	}

}
