package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Sislogins generated by hbm2java
 */
public class Sislogins implements java.io.Serializable {

	private SisloginsId id;

	public Sislogins() {
	}

	public Sislogins(SisloginsId id) {
		this.id = id;
	}

	public SisloginsId getId() {
		return this.id;
	}

	public void setId(SisloginsId id) {
		this.id = id;
	}

}
