package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Sisuustat generated by hbm2java
 */
public class Sisuustat implements java.io.Serializable {

	private SisuustatId id;

	public Sisuustat() {
	}

	public Sisuustat(SisuustatId id) {
		this.id = id;
	}

	public SisuustatId getId() {
		return this.id;
	}

	public void setId(SisuustatId id) {
		this.id = id;
	}

}
