package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SisuustatId generated by hbm2java
 */
public class SisuustatId implements java.io.Serializable {

	private String sislog;
	private String nomjob;
	private Character tipjob;
	private Date fecjob;
	private Date horjob;
	private String archiv;
	private String orides;
	private Character borjob;

	public SisuustatId() {
	}

	public SisuustatId(String sislog, String nomjob) {
		this.sislog = sislog;
		this.nomjob = nomjob;
	}

	public SisuustatId(String sislog, String nomjob, Character tipjob, Date fecjob, Date horjob, String archiv,
			String orides, Character borjob) {
		this.sislog = sislog;
		this.nomjob = nomjob;
		this.tipjob = tipjob;
		this.fecjob = fecjob;
		this.horjob = horjob;
		this.archiv = archiv;
		this.orides = orides;
		this.borjob = borjob;
	}

	public String getSislog() {
		return this.sislog;
	}

	public void setSislog(String sislog) {
		this.sislog = sislog;
	}

	public String getNomjob() {
		return this.nomjob;
	}

	public void setNomjob(String nomjob) {
		this.nomjob = nomjob;
	}

	public Character getTipjob() {
		return this.tipjob;
	}

	public void setTipjob(Character tipjob) {
		this.tipjob = tipjob;
	}

	public Date getFecjob() {
		return this.fecjob;
	}

	public void setFecjob(Date fecjob) {
		this.fecjob = fecjob;
	}

	public Date getHorjob() {
		return this.horjob;
	}

	public void setHorjob(Date horjob) {
		this.horjob = horjob;
	}

	public String getArchiv() {
		return this.archiv;
	}

	public void setArchiv(String archiv) {
		this.archiv = archiv;
	}

	public String getOrides() {
		return this.orides;
	}

	public void setOrides(String orides) {
		this.orides = orides;
	}

	public Character getBorjob() {
		return this.borjob;
	}

	public void setBorjob(Character borjob) {
		this.borjob = borjob;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SisuustatId))
			return false;
		SisuustatId castOther = (SisuustatId) other;

		return ((this.getSislog() == castOther.getSislog()) || (this.getSislog() != null
				&& castOther.getSislog() != null && this.getSislog().equals(castOther.getSislog())))
				&& ((this.getNomjob() == castOther.getNomjob()) || (this.getNomjob() != null
						&& castOther.getNomjob() != null && this.getNomjob().equals(castOther.getNomjob())))
				&& ((this.getTipjob() == castOther.getTipjob()) || (this.getTipjob() != null
						&& castOther.getTipjob() != null && this.getTipjob().equals(castOther.getTipjob())))
				&& ((this.getFecjob() == castOther.getFecjob()) || (this.getFecjob() != null
						&& castOther.getFecjob() != null && this.getFecjob().equals(castOther.getFecjob())))
				&& ((this.getHorjob() == castOther.getHorjob()) || (this.getHorjob() != null
						&& castOther.getHorjob() != null && this.getHorjob().equals(castOther.getHorjob())))
				&& ((this.getArchiv() == castOther.getArchiv()) || (this.getArchiv() != null
						&& castOther.getArchiv() != null && this.getArchiv().equals(castOther.getArchiv())))
				&& ((this.getOrides() == castOther.getOrides()) || (this.getOrides() != null
						&& castOther.getOrides() != null && this.getOrides().equals(castOther.getOrides())))
				&& ((this.getBorjob() == castOther.getBorjob()) || (this.getBorjob() != null
						&& castOther.getBorjob() != null && this.getBorjob().equals(castOther.getBorjob())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSislog() == null ? 0 : this.getSislog().hashCode());
		result = 37 * result + (getNomjob() == null ? 0 : this.getNomjob().hashCode());
		result = 37 * result + (getTipjob() == null ? 0 : this.getTipjob().hashCode());
		result = 37 * result + (getFecjob() == null ? 0 : this.getFecjob().hashCode());
		result = 37 * result + (getHorjob() == null ? 0 : this.getHorjob().hashCode());
		result = 37 * result + (getArchiv() == null ? 0 : this.getArchiv().hashCode());
		result = 37 * result + (getOrides() == null ? 0 : this.getOrides().hashCode());
		result = 37 * result + (getBorjob() == null ? 0 : this.getBorjob().hashCode());
		return result;
	}

}
