package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * TabincidId generated by hbm2java
 */
public class TabincidId implements java.io.Serializable {

	private Short codemp;
	private Short codcli;
	private Short codinc;
	private String dscinc;
	private Character txtfij;

	public TabincidId() {
	}

	public TabincidId(Short codemp, Short codcli, Short codinc, String dscinc, Character txtfij) {
		this.codemp = codemp;
		this.codcli = codcli;
		this.codinc = codinc;
		this.dscinc = dscinc;
		this.txtfij = txtfij;
	}

	public Short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(Short codemp) {
		this.codemp = codemp;
	}

	public Short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(Short codcli) {
		this.codcli = codcli;
	}

	public Short getCodinc() {
		return this.codinc;
	}

	public void setCodinc(Short codinc) {
		this.codinc = codinc;
	}

	public String getDscinc() {
		return this.dscinc;
	}

	public void setDscinc(String dscinc) {
		this.dscinc = dscinc;
	}

	public Character getTxtfij() {
		return this.txtfij;
	}

	public void setTxtfij(Character txtfij) {
		this.txtfij = txtfij;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TabincidId))
			return false;
		TabincidId castOther = (TabincidId) other;

		return ((this.getCodemp() == castOther.getCodemp()) || (this.getCodemp() != null
				&& castOther.getCodemp() != null && this.getCodemp().equals(castOther.getCodemp())))
				&& ((this.getCodcli() == castOther.getCodcli()) || (this.getCodcli() != null
						&& castOther.getCodcli() != null && this.getCodcli().equals(castOther.getCodcli())))
				&& ((this.getCodinc() == castOther.getCodinc()) || (this.getCodinc() != null
						&& castOther.getCodinc() != null && this.getCodinc().equals(castOther.getCodinc())))
				&& ((this.getDscinc() == castOther.getDscinc()) || (this.getDscinc() != null
						&& castOther.getDscinc() != null && this.getDscinc().equals(castOther.getDscinc())))
				&& ((this.getTxtfij() == castOther.getTxtfij()) || (this.getTxtfij() != null
						&& castOther.getTxtfij() != null && this.getTxtfij().equals(castOther.getTxtfij())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodemp() == null ? 0 : this.getCodemp().hashCode());
		result = 37 * result + (getCodcli() == null ? 0 : this.getCodcli().hashCode());
		result = 37 * result + (getCodinc() == null ? 0 : this.getCodinc().hashCode());
		result = 37 * result + (getDscinc() == null ? 0 : this.getDscinc().hashCode());
		result = 37 * result + (getTxtfij() == null ? 0 : this.getTxtfij().hashCode());
		return result;
	}

}
