package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Tabincid generated by hbm2java
 */
public class Tabincid implements java.io.Serializable {

	private TabincidId id;

	public Tabincid() {
	}

	public Tabincid(TabincidId id) {
		this.id = id;
	}

	public TabincidId getId() {
		return this.id;
	}

	public void setId(TabincidId id) {
		this.id = id;
	}

}
