package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Tardirec generated by hbm2java
 */
public class Tardirec implements java.io.Serializable {

	private TardirecId id;
	private String observ;

	public Tardirec() {
	}

	public Tardirec(TardirecId id) {
		this.id = id;
	}

	public Tardirec(TardirecId id, String observ) {
		this.id = id;
		this.observ = observ;
	}

	public TardirecId getId() {
		return this.id;
	}

	public void setId(TardirecId id) {
		this.id = id;
	}

	public String getObserv() {
		return this.observ;
	}

	public void setObserv(String observ) {
		this.observ = observ;
	}

}
