package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tarfracc generated by hbm2java
 */
public class Tarfracc implements java.io.Serializable {

	private TarfraccId id;
	private BigDecimal precio;
	private Character fraton;

	public Tarfracc() {
	}

	public Tarfracc(TarfraccId id, BigDecimal precio) {
		this.id = id;
		this.precio = precio;
	}

	public Tarfracc(TarfraccId id, BigDecimal precio, Character fraton) {
		this.id = id;
		this.precio = precio;
		this.fraton = fraton;
	}

	public TarfraccId getId() {
		return this.id;
	}

	public void setId(TarfraccId id) {
		this.id = id;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public Character getFraton() {
		return this.fraton;
	}

	public void setFraton(Character fraton) {
		this.fraton = fraton;
	}

}
