package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TarfraccId generated by hbm2java
 */
public class TarfraccId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private short numtar;
	private String aplica;
	private Date feclim;
	private BigDecimal fracci;
	private char baremo;

	public TarfraccId() {
	}

	public TarfraccId(short codemp, short coddel, short numtar, String aplica, Date feclim, BigDecimal fracci,
			char baremo) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.numtar = numtar;
		this.aplica = aplica;
		this.feclim = feclim;
		this.fracci = fracci;
		this.baremo = baremo;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public short getNumtar() {
		return this.numtar;
	}

	public void setNumtar(short numtar) {
		this.numtar = numtar;
	}

	public String getAplica() {
		return this.aplica;
	}

	public void setAplica(String aplica) {
		this.aplica = aplica;
	}

	public Date getFeclim() {
		return this.feclim;
	}

	public void setFeclim(Date feclim) {
		this.feclim = feclim;
	}

	public BigDecimal getFracci() {
		return this.fracci;
	}

	public void setFracci(BigDecimal fracci) {
		this.fracci = fracci;
	}

	public char getBaremo() {
		return this.baremo;
	}

	public void setBaremo(char baremo) {
		this.baremo = baremo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TarfraccId))
			return false;
		TarfraccId castOther = (TarfraccId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& (this.getNumtar() == castOther.getNumtar())
				&& ((this.getAplica() == castOther.getAplica()) || (this.getAplica() != null
						&& castOther.getAplica() != null && this.getAplica().equals(castOther.getAplica())))
				&& ((this.getFeclim() == castOther.getFeclim()) || (this.getFeclim() != null
						&& castOther.getFeclim() != null && this.getFeclim().equals(castOther.getFeclim())))
				&& ((this.getFracci() == castOther.getFracci()) || (this.getFracci() != null
						&& castOther.getFracci() != null && this.getFracci().equals(castOther.getFracci())))
				&& (this.getBaremo() == castOther.getBaremo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + this.getNumtar();
		result = 37 * result + (getAplica() == null ? 0 : this.getAplica().hashCode());
		result = 37 * result + (getFeclim() == null ? 0 : this.getFeclim().hashCode());
		result = 37 * result + (getFracci() == null ? 0 : this.getFracci().hashCode());
		result = 37 * result + this.getBaremo();
		return result;
	}

}
