package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Targrupo generated by hbm2java
 */
public class Targrupo implements java.io.Serializable {

	private TargrupoId id;
	private char bardis;
	private Character barrxp;

	public Targrupo() {
	}

	public Targrupo(TargrupoId id, char bardis) {
		this.id = id;
		this.bardis = bardis;
	}

	public Targrupo(TargrupoId id, char bardis, Character barrxp) {
		this.id = id;
		this.bardis = bardis;
		this.barrxp = barrxp;
	}

	public TargrupoId getId() {
		return this.id;
	}

	public void setId(TargrupoId id) {
		this.id = id;
	}

	public char getBardis() {
		return this.bardis;
	}

	public void setBardis(char bardis) {
		this.bardis = bardis;
	}

	public Character getBarrxp() {
		return this.barrxp;
	}

	public void setBarrxp(Character barrxp) {
		this.barrxp = barrxp;
	}

}
