package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TargrupoId generated by hbm2java
 */
public class TargrupoId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private short numtar;
	private String aplica;
	private Date feclim;
	private short grupo;

	public TargrupoId() {
	}

	public TargrupoId(short codemp, short coddel, short numtar, String aplica, Date feclim, short grupo) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.numtar = numtar;
		this.aplica = aplica;
		this.feclim = feclim;
		this.grupo = grupo;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public short getNumtar() {
		return this.numtar;
	}

	public void setNumtar(short numtar) {
		this.numtar = numtar;
	}

	public String getAplica() {
		return this.aplica;
	}

	public void setAplica(String aplica) {
		this.aplica = aplica;
	}

	public Date getFeclim() {
		return this.feclim;
	}

	public void setFeclim(Date feclim) {
		this.feclim = feclim;
	}

	public short getGrupo() {
		return this.grupo;
	}

	public void setGrupo(short grupo) {
		this.grupo = grupo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TargrupoId))
			return false;
		TargrupoId castOther = (TargrupoId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& (this.getNumtar() == castOther.getNumtar())
				&& ((this.getAplica() == castOther.getAplica()) || (this.getAplica() != null
						&& castOther.getAplica() != null && this.getAplica().equals(castOther.getAplica())))
				&& ((this.getFeclim() == castOther.getFeclim()) || (this.getFeclim() != null
						&& castOther.getFeclim() != null && this.getFeclim().equals(castOther.getFeclim())))
				&& (this.getGrupo() == castOther.getGrupo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + this.getNumtar();
		result = 37 * result + (getAplica() == null ? 0 : this.getAplica().hashCode());
		result = 37 * result + (getFeclim() == null ? 0 : this.getFeclim().hashCode());
		result = 37 * result + this.getGrupo();
		return result;
	}

}
