package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Transpcl generated by hbm2java
 */
public class Transpcl implements java.io.Serializable {

	private TranspclId id;

	public Transpcl() {
	}

	public Transpcl(TranspclId id) {
		this.id = id;
	}

	public TranspclId getId() {
		return this.id;
	}

	public void setId(TranspclId id) {
		this.id = id;
	}

}
