package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * TransporId generated by hbm2java
 */
public class TransporId implements java.io.Serializable {

	private short codemp;
	private short codtra;

	public TransporId() {
	}

	public TransporId(short codemp, short codtra) {
		this.codemp = codemp;
		this.codtra = codtra;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCodtra() {
		return this.codtra;
	}

	public void setCodtra(short codtra) {
		this.codtra = codtra;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransporId))
			return false;
		TransporId castOther = (TransporId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCodtra() == castOther.getCodtra());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCodtra();
		return result;
	}

}
