package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * TranspclId generated by hbm2java
 */
public class TranspclId implements java.io.Serializable {

	private short codemp;
	private short codtra;
	private short codcli;
	private int codctr;
	private String nomctr;
	private Character alfirm;

	public TranspclId() {
	}

	public TranspclId(short codemp, short codtra, short codcli, int codctr) {
		this.codemp = codemp;
		this.codtra = codtra;
		this.codcli = codcli;
		this.codctr = codctr;
	}

	public TranspclId(short codemp, short codtra, short codcli, int codctr, String nomctr, Character alfirm) {
		this.codemp = codemp;
		this.codtra = codtra;
		this.codcli = codcli;
		this.codctr = codctr;
		this.nomctr = nomctr;
		this.alfirm = alfirm;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCodtra() {
		return this.codtra;
	}

	public void setCodtra(short codtra) {
		this.codtra = codtra;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public int getCodctr() {
		return this.codctr;
	}

	public void setCodctr(int codctr) {
		this.codctr = codctr;
	}

	public String getNomctr() {
		return this.nomctr;
	}

	public void setNomctr(String nomctr) {
		this.nomctr = nomctr;
	}

	public Character getAlfirm() {
		return this.alfirm;
	}

	public void setAlfirm(Character alfirm) {
		this.alfirm = alfirm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TranspclId))
			return false;
		TranspclId castOther = (TranspclId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCodtra() == castOther.getCodtra())
				&& (this.getCodcli() == castOther.getCodcli()) && (this.getCodctr() == castOther.getCodctr())
				&& ((this.getNomctr() == castOther.getNomctr()) || (this.getNomctr() != null
						&& castOther.getNomctr() != null && this.getNomctr().equals(castOther.getNomctr())))
				&& ((this.getAlfirm() == castOther.getAlfirm()) || (this.getAlfirm() != null
						&& castOther.getAlfirm() != null && this.getAlfirm().equals(castOther.getAlfirm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCodtra();
		result = 37 * result + this.getCodcli();
		result = 37 * result + this.getCodctr();
		result = 37 * result + (getNomctr() == null ? 0 : this.getNomctr().hashCode());
		result = 37 * result + (getAlfirm() == null ? 0 : this.getAlfirm().hashCode());
		return result;
	}

}
