package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * TxtalbaranId generated by hbm2java
 */
public class TxtalbaranId implements java.io.Serializable {

	private Short codemp;
	private Short codcli;
	private String texto;

	public TxtalbaranId() {
	}

	public TxtalbaranId(Short codemp, Short codcli, String texto) {
		this.codemp = codemp;
		this.codcli = codcli;
		this.texto = texto;
	}

	public Short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(Short codemp) {
		this.codemp = codemp;
	}

	public Short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(Short codcli) {
		this.codcli = codcli;
	}

	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TxtalbaranId))
			return false;
		TxtalbaranId castOther = (TxtalbaranId) other;

		return ((this.getCodemp() == castOther.getCodemp()) || (this.getCodemp() != null
				&& castOther.getCodemp() != null && this.getCodemp().equals(castOther.getCodemp())))
				&& ((this.getCodcli() == castOther.getCodcli()) || (this.getCodcli() != null
						&& castOther.getCodcli() != null && this.getCodcli().equals(castOther.getCodcli())))
				&& ((this.getTexto() == castOther.getTexto()) || (this.getTexto() != null
						&& castOther.getTexto() != null && this.getTexto().equals(castOther.getTexto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodemp() == null ? 0 : this.getCodemp().hashCode());
		result = 37 * result + (getCodcli() == null ? 0 : this.getCodcli().hashCode());
		result = 37 * result + (getTexto() == null ? 0 : this.getTexto().hashCode());
		return result;
	}

}
