package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Txtalbaran generated by hbm2java
 */
public class Txtalbaran implements java.io.Serializable {

	private TxtalbaranId id;

	public Txtalbaran() {
	}

	public Txtalbaran(TxtalbaranId id) {
		this.id = id;
	}

	public TxtalbaranId getId() {
		return this.id;
	}

	public void setId(TxtalbaranId id) {
		this.id = id;
	}

}
