package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UltimosCalculosId generated by hbm2java
 */
public class UltimosCalculosId implements java.io.Serializable {

	private short codemp;
	private short cenfac;
	private short codcli;
	private String aplica;
	private String bastar;
	private char baremo;
	private Date feccal;

	public UltimosCalculosId() {
	}

	public UltimosCalculosId(short codemp, short cenfac, short codcli, String aplica, String bastar, char baremo,
			Date feccal) {
		this.codemp = codemp;
		this.cenfac = cenfac;
		this.codcli = codcli;
		this.aplica = aplica;
		this.bastar = bastar;
		this.baremo = baremo;
		this.feccal = feccal;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCenfac() {
		return this.cenfac;
	}

	public void setCenfac(short cenfac) {
		this.cenfac = cenfac;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public String getAplica() {
		return this.aplica;
	}

	public void setAplica(String aplica) {
		this.aplica = aplica;
	}

	public String getBastar() {
		return this.bastar;
	}

	public void setBastar(String bastar) {
		this.bastar = bastar;
	}

	public char getBaremo() {
		return this.baremo;
	}

	public void setBaremo(char baremo) {
		this.baremo = baremo;
	}

	public Date getFeccal() {
		return this.feccal;
	}

	public void setFeccal(Date feccal) {
		this.feccal = feccal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UltimosCalculosId))
			return false;
		UltimosCalculosId castOther = (UltimosCalculosId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCenfac() == castOther.getCenfac())
				&& (this.getCodcli() == castOther.getCodcli())
				&& ((this.getAplica() == castOther.getAplica()) || (this.getAplica() != null
						&& castOther.getAplica() != null && this.getAplica().equals(castOther.getAplica())))
				&& ((this.getBastar() == castOther.getBastar()) || (this.getBastar() != null
						&& castOther.getBastar() != null && this.getBastar().equals(castOther.getBastar())))
				&& (this.getBaremo() == castOther.getBaremo())
				&& ((this.getFeccal() == castOther.getFeccal()) || (this.getFeccal() != null
						&& castOther.getFeccal() != null && this.getFeccal().equals(castOther.getFeccal())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCenfac();
		result = 37 * result + this.getCodcli();
		result = 37 * result + (getAplica() == null ? 0 : this.getAplica().hashCode());
		result = 37 * result + (getBastar() == null ? 0 : this.getBastar().hashCode());
		result = 37 * result + this.getBaremo();
		result = 37 * result + (getFeccal() == null ? 0 : this.getFeccal().hashCode());
		return result;
	}

}
