package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * UltimosCalculos generated by hbm2java
 */
public class UltimosCalculos implements java.io.Serializable {

	private UltimosCalculosId id;
	private BigDecimal udsalm;

	public UltimosCalculos() {
	}

	public UltimosCalculos(UltimosCalculosId id) {
		this.id = id;
	}

	public UltimosCalculos(UltimosCalculosId id, BigDecimal udsalm) {
		this.id = id;
		this.udsalm = udsalm;
	}

	public UltimosCalculosId getId() {
		return this.id;
	}

	public void setId(UltimosCalculosId id) {
		this.id = id;
	}

	public BigDecimal getUdsalm() {
		return this.udsalm;
	}

	public void setUdsalm(BigDecimal udsalm) {
		this.udsalm = udsalm;
	}

}
