package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private UsuariosId id;

	public Usuarios() {
	}

	public Usuarios(UsuariosId id) {
		this.id = id;
	}

	public UsuariosId getId() {
		return this.id;
	}

	public void setId(UsuariosId id) {
		this.id = id;
	}

}
