package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * UsuariosId generated by hbm2java
 */
public class UsuariosId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private String nomusu;
	private String claacc;
	private String cloper;
	private short nivope;
	private char tipins;

	public UsuariosId() {
	}

	public UsuariosId(short codemp, short coddel, String nomusu, String claacc, String cloper, short nivope,
			char tipins) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.nomusu = nomusu;
		this.claacc = claacc;
		this.cloper = cloper;
		this.nivope = nivope;
		this.tipins = tipins;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public String getNomusu() {
		return this.nomusu;
	}

	public void setNomusu(String nomusu) {
		this.nomusu = nomusu;
	}

	public String getClaacc() {
		return this.claacc;
	}

	public void setClaacc(String claacc) {
		this.claacc = claacc;
	}

	public String getCloper() {
		return this.cloper;
	}

	public void setCloper(String cloper) {
		this.cloper = cloper;
	}

	public short getNivope() {
		return this.nivope;
	}

	public void setNivope(short nivope) {
		this.nivope = nivope;
	}

	public char getTipins() {
		return this.tipins;
	}

	public void setTipins(char tipins) {
		this.tipins = tipins;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuariosId))
			return false;
		UsuariosId castOther = (UsuariosId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& ((this.getNomusu() == castOther.getNomusu()) || (this.getNomusu() != null
						&& castOther.getNomusu() != null && this.getNomusu().equals(castOther.getNomusu())))
				&& ((this.getClaacc() == castOther.getClaacc()) || (this.getClaacc() != null
						&& castOther.getClaacc() != null && this.getClaacc().equals(castOther.getClaacc())))
				&& ((this.getCloper() == castOther.getCloper()) || (this.getCloper() != null
						&& castOther.getCloper() != null && this.getCloper().equals(castOther.getCloper())))
				&& (this.getNivope() == castOther.getNivope()) && (this.getTipins() == castOther.getTipins());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + (getNomusu() == null ? 0 : this.getNomusu().hashCode());
		result = 37 * result + (getClaacc() == null ? 0 : this.getClaacc().hashCode());
		result = 37 * result + (getCloper() == null ? 0 : this.getCloper().hashCode());
		result = 37 * result + this.getNivope();
		result = 37 * result + this.getTipins();
		return result;
	}

}
