package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Valservi generated by hbm2java
 */
public class Valservi implements java.io.Serializable {

	private ValserviId id;
	private short cenfac;
	private char serfac;
	private short ejefac;
	private int numfac;
	private short numlin;
	private BigDecimal unitas;
	private BigDecimal import_;
	private BigDecimal perseg;
	private BigDecimal seguro;

	public Valservi() {
	}

	public Valservi(ValserviId id, short cenfac, char serfac, short ejefac, int numfac, short numlin) {
		this.id = id;
		this.cenfac = cenfac;
		this.serfac = serfac;
		this.ejefac = ejefac;
		this.numfac = numfac;
		this.numlin = numlin;
	}

	public Valservi(ValserviId id, short cenfac, char serfac, short ejefac, int numfac, short numlin, BigDecimal unitas,
			BigDecimal import_, BigDecimal perseg, BigDecimal seguro) {
		this.id = id;
		this.cenfac = cenfac;
		this.serfac = serfac;
		this.ejefac = ejefac;
		this.numfac = numfac;
		this.numlin = numlin;
		this.unitas = unitas;
		this.import_ = import_;
		this.perseg = perseg;
		this.seguro = seguro;
	}

	public ValserviId getId() {
		return this.id;
	}

	public void setId(ValserviId id) {
		this.id = id;
	}

	public short getCenfac() {
		return this.cenfac;
	}

	public void setCenfac(short cenfac) {
		this.cenfac = cenfac;
	}

	public char getSerfac() {
		return this.serfac;
	}

	public void setSerfac(char serfac) {
		this.serfac = serfac;
	}

	public short getEjefac() {
		return this.ejefac;
	}

	public void setEjefac(short ejefac) {
		this.ejefac = ejefac;
	}

	public int getNumfac() {
		return this.numfac;
	}

	public void setNumfac(int numfac) {
		this.numfac = numfac;
	}

	public short getNumlin() {
		return this.numlin;
	}

	public void setNumlin(short numlin) {
		this.numlin = numlin;
	}

	public BigDecimal getUnitas() {
		return this.unitas;
	}

	public void setUnitas(BigDecimal unitas) {
		this.unitas = unitas;
	}

	public BigDecimal getImport_() {
		return this.import_;
	}

	public void setImport_(BigDecimal import_) {
		this.import_ = import_;
	}

	public BigDecimal getPerseg() {
		return this.perseg;
	}

	public void setPerseg(BigDecimal perseg) {
		this.perseg = perseg;
	}

	public BigDecimal getSeguro() {
		return this.seguro;
	}

	public void setSeguro(BigDecimal seguro) {
		this.seguro = seguro;
	}

}
