package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * ValserviId generated by hbm2java
 */
public class ValserviId implements java.io.Serializable {

	private short codemp;
	private short codcli;
	private char tipalb;
	private String seralb;
	private short ejerci;
	private int numalb;
	private String aplica;
	private String bastar;

	public ValserviId() {
	}

	public ValserviId(short codemp, short codcli, char tipalb, String seralb, short ejerci, int numalb, String aplica,
			String bastar) {
		this.codemp = codemp;
		this.codcli = codcli;
		this.tipalb = tipalb;
		this.seralb = seralb;
		this.ejerci = ejerci;
		this.numalb = numalb;
		this.aplica = aplica;
		this.bastar = bastar;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public char getTipalb() {
		return this.tipalb;
	}

	public void setTipalb(char tipalb) {
		this.tipalb = tipalb;
	}

	public String getSeralb() {
		return this.seralb;
	}

	public void setSeralb(String seralb) {
		this.seralb = seralb;
	}

	public short getEjerci() {
		return this.ejerci;
	}

	public void setEjerci(short ejerci) {
		this.ejerci = ejerci;
	}

	public int getNumalb() {
		return this.numalb;
	}

	public void setNumalb(int numalb) {
		this.numalb = numalb;
	}

	public String getAplica() {
		return this.aplica;
	}

	public void setAplica(String aplica) {
		this.aplica = aplica;
	}

	public String getBastar() {
		return this.bastar;
	}

	public void setBastar(String bastar) {
		this.bastar = bastar;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ValserviId))
			return false;
		ValserviId castOther = (ValserviId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCodcli() == castOther.getCodcli())
				&& (this.getTipalb() == castOther.getTipalb())
				&& ((this.getSeralb() == castOther.getSeralb()) || (this.getSeralb() != null
						&& castOther.getSeralb() != null && this.getSeralb().equals(castOther.getSeralb())))
				&& (this.getEjerci() == castOther.getEjerci()) && (this.getNumalb() == castOther.getNumalb())
				&& ((this.getAplica() == castOther.getAplica()) || (this.getAplica() != null
						&& castOther.getAplica() != null && this.getAplica().equals(castOther.getAplica())))
				&& ((this.getBastar() == castOther.getBastar()) || (this.getBastar() != null
						&& castOther.getBastar() != null && this.getBastar().equals(castOther.getBastar())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCodcli();
		result = 37 * result + this.getTipalb();
		result = 37 * result + (getSeralb() == null ? 0 : this.getSeralb().hashCode());
		result = 37 * result + this.getEjerci();
		result = 37 * result + this.getNumalb();
		result = 37 * result + (getAplica() == null ? 0 : this.getAplica().hashCode());
		result = 37 * result + (getBastar() == null ? 0 : this.getBastar().hashCode());
		return result;
	}

}
