package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * VehiculosId generated by hbm2java
 */
public class VehiculosId implements java.io.Serializable {

	private short codemp;
	private short numveh;

	public VehiculosId() {
	}

	public VehiculosId(short codemp, short numveh) {
		this.codemp = codemp;
		this.numveh = numveh;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getNumveh() {
		return this.numveh;
	}

	public void setNumveh(short numveh) {
		this.numveh = numveh;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VehiculosId))
			return false;
		VehiculosId castOther = (VehiculosId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getNumveh() == castOther.getNumveh());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getNumveh();
		return result;
	}

}
