package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Vehiculos generated by hbm2java
 */
public class Vehiculos implements java.io.Serializable {

	private VehiculosId id;
	private String cifdni;
	private String nombre;
	private String domici;
	private Integer codpos;
	private String poblac;
	private Short provin;
	private Short pais;
	private String telefo;
	private String telefx;

	public Vehiculos() {
	}

	public Vehiculos(VehiculosId id, String cifdni, String nombre, String domici, String poblac) {
		this.id = id;
		this.cifdni = cifdni;
		this.nombre = nombre;
		this.domici = domici;
		this.poblac = poblac;
	}

	public Vehiculos(VehiculosId id, String cifdni, String nombre, String domici, Integer codpos, String poblac,
			Short provin, Short pais, String telefo, String telefx) {
		this.id = id;
		this.cifdni = cifdni;
		this.nombre = nombre;
		this.domici = domici;
		this.codpos = codpos;
		this.poblac = poblac;
		this.provin = provin;
		this.pais = pais;
		this.telefo = telefo;
		this.telefx = telefx;
	}

	public VehiculosId getId() {
		return this.id;
	}

	public void setId(VehiculosId id) {
		this.id = id;
	}

	public String getCifdni() {
		return this.cifdni;
	}

	public void setCifdni(String cifdni) {
		this.cifdni = cifdni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDomici() {
		return this.domici;
	}

	public void setDomici(String domici) {
		this.domici = domici;
	}

	public Integer getCodpos() {
		return this.codpos;
	}

	public void setCodpos(Integer codpos) {
		this.codpos = codpos;
	}

	public String getPoblac() {
		return this.poblac;
	}

	public void setPoblac(String poblac) {
		this.poblac = poblac;
	}

	public Short getProvin() {
		return this.provin;
	}

	public void setProvin(Short provin) {
		this.provin = provin;
	}

	public Short getPais() {
		return this.pais;
	}

	public void setPais(Short pais) {
		this.pais = pais;
	}

	public String getTelefo() {
		return this.telefo;
	}

	public void setTelefo(String telefo) {
		this.telefo = telefo;
	}

	public String getTelefx() {
		return this.telefx;
	}

	public void setTelefx(String telefx) {
		this.telefx = telefx;
	}

}
