package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * WarticulId generated by hbm2java
 */
public class WarticulId implements java.io.Serializable {

	private short codcli;
	private String codart;

	public WarticulId() {
	}

	public WarticulId(short codcli, String codart) {
		this.codcli = codcli;
		this.codart = codart;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WarticulId))
			return false;
		WarticulId castOther = (WarticulId) other;

		return (this.getCodcli() == castOther.getCodcli())
				&& ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
						&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodcli();
		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		return result;
	}

}
