package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Warticul generated by hbm2java
 */
public class Warticul implements java.io.Serializable {

	private WarticulId id;
	private String dscart;
	private BigDecimal pdtser;
	private BigDecimal pdtrec;

	public Warticul() {
	}

	public Warticul(WarticulId id, String dscart) {
		this.id = id;
		this.dscart = dscart;
	}

	public Warticul(WarticulId id, String dscart, BigDecimal pdtser, BigDecimal pdtrec) {
		this.id = id;
		this.dscart = dscart;
		this.pdtser = pdtser;
		this.pdtrec = pdtrec;
	}

	public WarticulId getId() {
		return this.id;
	}

	public void setId(WarticulId id) {
		this.id = id;
	}

	public String getDscart() {
		return this.dscart;
	}

	public void setDscart(String dscart) {
		this.dscart = dscart;
	}

	public BigDecimal getPdtser() {
		return this.pdtser;
	}

	public void setPdtser(BigDecimal pdtser) {
		this.pdtser = pdtser;
	}

	public BigDecimal getPdtrec() {
		return this.pdtrec;
	}

	public void setPdtrec(BigDecimal pdtrec) {
		this.pdtrec = pdtrec;
	}

}
