package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Wwwanul generated by hbm2java
 */
public class Wwwanul implements java.io.Serializable {

	private WwwanulId id;

	public Wwwanul() {
	}

	public Wwwanul(WwwanulId id) {
		this.id = id;
	}

	public WwwanulId getId() {
		return this.id;
	}

	public void setId(WwwanulId id) {
		this.id = id;
	}

}
