package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ZacumoviId generated by hbm2java
 */
public class ZacumoviId implements java.io.Serializable {

	private short codemp;
	private short ejerci;
	private short coddel;
	private short codcli;
	private String codart;
	private BigDecimal stkini;
	private BigDecimal unie01;
	private BigDecimal unie02;
	private BigDecimal unie03;
	private BigDecimal unie04;
	private BigDecimal unie05;
	private BigDecimal unie06;
	private BigDecimal unie07;
	private BigDecimal unie08;
	private BigDecimal unie09;
	private BigDecimal unie10;
	private BigDecimal unie11;
	private BigDecimal unie12;
	private BigDecimal unis01;
	private BigDecimal unis02;
	private BigDecimal unis03;
	private BigDecimal unis04;
	private BigDecimal unis05;
	private BigDecimal unis06;
	private BigDecimal unis07;
	private BigDecimal unis08;
	private BigDecimal unis09;
	private BigDecimal unis10;
	private BigDecimal unis11;
	private BigDecimal unis12;
	private BigDecimal unir01;
	private BigDecimal unir02;
	private BigDecimal unir03;
	private BigDecimal unir04;
	private BigDecimal unir05;
	private BigDecimal unir06;
	private BigDecimal unir07;
	private BigDecimal unir08;
	private BigDecimal unir09;
	private BigDecimal unir10;
	private BigDecimal unir11;
	private BigDecimal unir12;

	public ZacumoviId() {
	}

	public ZacumoviId(short codemp, short ejerci, short coddel, short codcli) {
		this.codemp = codemp;
		this.ejerci = ejerci;
		this.coddel = coddel;
		this.codcli = codcli;
	}

	public ZacumoviId(short codemp, short ejerci, short coddel, short codcli, String codart, BigDecimal stkini,
			BigDecimal unie01, BigDecimal unie02, BigDecimal unie03, BigDecimal unie04, BigDecimal unie05,
			BigDecimal unie06, BigDecimal unie07, BigDecimal unie08, BigDecimal unie09, BigDecimal unie10,
			BigDecimal unie11, BigDecimal unie12, BigDecimal unis01, BigDecimal unis02, BigDecimal unis03,
			BigDecimal unis04, BigDecimal unis05, BigDecimal unis06, BigDecimal unis07, BigDecimal unis08,
			BigDecimal unis09, BigDecimal unis10, BigDecimal unis11, BigDecimal unis12, BigDecimal unir01,
			BigDecimal unir02, BigDecimal unir03, BigDecimal unir04, BigDecimal unir05, BigDecimal unir06,
			BigDecimal unir07, BigDecimal unir08, BigDecimal unir09, BigDecimal unir10, BigDecimal unir11,
			BigDecimal unir12) {
		this.codemp = codemp;
		this.ejerci = ejerci;
		this.coddel = coddel;
		this.codcli = codcli;
		this.codart = codart;
		this.stkini = stkini;
		this.unie01 = unie01;
		this.unie02 = unie02;
		this.unie03 = unie03;
		this.unie04 = unie04;
		this.unie05 = unie05;
		this.unie06 = unie06;
		this.unie07 = unie07;
		this.unie08 = unie08;
		this.unie09 = unie09;
		this.unie10 = unie10;
		this.unie11 = unie11;
		this.unie12 = unie12;
		this.unis01 = unis01;
		this.unis02 = unis02;
		this.unis03 = unis03;
		this.unis04 = unis04;
		this.unis05 = unis05;
		this.unis06 = unis06;
		this.unis07 = unis07;
		this.unis08 = unis08;
		this.unis09 = unis09;
		this.unis10 = unis10;
		this.unis11 = unis11;
		this.unis12 = unis12;
		this.unir01 = unir01;
		this.unir02 = unir02;
		this.unir03 = unir03;
		this.unir04 = unir04;
		this.unir05 = unir05;
		this.unir06 = unir06;
		this.unir07 = unir07;
		this.unir08 = unir08;
		this.unir09 = unir09;
		this.unir10 = unir10;
		this.unir11 = unir11;
		this.unir12 = unir12;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getEjerci() {
		return this.ejerci;
	}

	public void setEjerci(short ejerci) {
		this.ejerci = ejerci;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public BigDecimal getStkini() {
		return this.stkini;
	}

	public void setStkini(BigDecimal stkini) {
		this.stkini = stkini;
	}

	public BigDecimal getUnie01() {
		return this.unie01;
	}

	public void setUnie01(BigDecimal unie01) {
		this.unie01 = unie01;
	}

	public BigDecimal getUnie02() {
		return this.unie02;
	}

	public void setUnie02(BigDecimal unie02) {
		this.unie02 = unie02;
	}

	public BigDecimal getUnie03() {
		return this.unie03;
	}

	public void setUnie03(BigDecimal unie03) {
		this.unie03 = unie03;
	}

	public BigDecimal getUnie04() {
		return this.unie04;
	}

	public void setUnie04(BigDecimal unie04) {
		this.unie04 = unie04;
	}

	public BigDecimal getUnie05() {
		return this.unie05;
	}

	public void setUnie05(BigDecimal unie05) {
		this.unie05 = unie05;
	}

	public BigDecimal getUnie06() {
		return this.unie06;
	}

	public void setUnie06(BigDecimal unie06) {
		this.unie06 = unie06;
	}

	public BigDecimal getUnie07() {
		return this.unie07;
	}

	public void setUnie07(BigDecimal unie07) {
		this.unie07 = unie07;
	}

	public BigDecimal getUnie08() {
		return this.unie08;
	}

	public void setUnie08(BigDecimal unie08) {
		this.unie08 = unie08;
	}

	public BigDecimal getUnie09() {
		return this.unie09;
	}

	public void setUnie09(BigDecimal unie09) {
		this.unie09 = unie09;
	}

	public BigDecimal getUnie10() {
		return this.unie10;
	}

	public void setUnie10(BigDecimal unie10) {
		this.unie10 = unie10;
	}

	public BigDecimal getUnie11() {
		return this.unie11;
	}

	public void setUnie11(BigDecimal unie11) {
		this.unie11 = unie11;
	}

	public BigDecimal getUnie12() {
		return this.unie12;
	}

	public void setUnie12(BigDecimal unie12) {
		this.unie12 = unie12;
	}

	public BigDecimal getUnis01() {
		return this.unis01;
	}

	public void setUnis01(BigDecimal unis01) {
		this.unis01 = unis01;
	}

	public BigDecimal getUnis02() {
		return this.unis02;
	}

	public void setUnis02(BigDecimal unis02) {
		this.unis02 = unis02;
	}

	public BigDecimal getUnis03() {
		return this.unis03;
	}

	public void setUnis03(BigDecimal unis03) {
		this.unis03 = unis03;
	}

	public BigDecimal getUnis04() {
		return this.unis04;
	}

	public void setUnis04(BigDecimal unis04) {
		this.unis04 = unis04;
	}

	public BigDecimal getUnis05() {
		return this.unis05;
	}

	public void setUnis05(BigDecimal unis05) {
		this.unis05 = unis05;
	}

	public BigDecimal getUnis06() {
		return this.unis06;
	}

	public void setUnis06(BigDecimal unis06) {
		this.unis06 = unis06;
	}

	public BigDecimal getUnis07() {
		return this.unis07;
	}

	public void setUnis07(BigDecimal unis07) {
		this.unis07 = unis07;
	}

	public BigDecimal getUnis08() {
		return this.unis08;
	}

	public void setUnis08(BigDecimal unis08) {
		this.unis08 = unis08;
	}

	public BigDecimal getUnis09() {
		return this.unis09;
	}

	public void setUnis09(BigDecimal unis09) {
		this.unis09 = unis09;
	}

	public BigDecimal getUnis10() {
		return this.unis10;
	}

	public void setUnis10(BigDecimal unis10) {
		this.unis10 = unis10;
	}

	public BigDecimal getUnis11() {
		return this.unis11;
	}

	public void setUnis11(BigDecimal unis11) {
		this.unis11 = unis11;
	}

	public BigDecimal getUnis12() {
		return this.unis12;
	}

	public void setUnis12(BigDecimal unis12) {
		this.unis12 = unis12;
	}

	public BigDecimal getUnir01() {
		return this.unir01;
	}

	public void setUnir01(BigDecimal unir01) {
		this.unir01 = unir01;
	}

	public BigDecimal getUnir02() {
		return this.unir02;
	}

	public void setUnir02(BigDecimal unir02) {
		this.unir02 = unir02;
	}

	public BigDecimal getUnir03() {
		return this.unir03;
	}

	public void setUnir03(BigDecimal unir03) {
		this.unir03 = unir03;
	}

	public BigDecimal getUnir04() {
		return this.unir04;
	}

	public void setUnir04(BigDecimal unir04) {
		this.unir04 = unir04;
	}

	public BigDecimal getUnir05() {
		return this.unir05;
	}

	public void setUnir05(BigDecimal unir05) {
		this.unir05 = unir05;
	}

	public BigDecimal getUnir06() {
		return this.unir06;
	}

	public void setUnir06(BigDecimal unir06) {
		this.unir06 = unir06;
	}

	public BigDecimal getUnir07() {
		return this.unir07;
	}

	public void setUnir07(BigDecimal unir07) {
		this.unir07 = unir07;
	}

	public BigDecimal getUnir08() {
		return this.unir08;
	}

	public void setUnir08(BigDecimal unir08) {
		this.unir08 = unir08;
	}

	public BigDecimal getUnir09() {
		return this.unir09;
	}

	public void setUnir09(BigDecimal unir09) {
		this.unir09 = unir09;
	}

	public BigDecimal getUnir10() {
		return this.unir10;
	}

	public void setUnir10(BigDecimal unir10) {
		this.unir10 = unir10;
	}

	public BigDecimal getUnir11() {
		return this.unir11;
	}

	public void setUnir11(BigDecimal unir11) {
		this.unir11 = unir11;
	}

	public BigDecimal getUnir12() {
		return this.unir12;
	}

	public void setUnir12(BigDecimal unir12) {
		this.unir12 = unir12;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZacumoviId))
			return false;
		ZacumoviId castOther = (ZacumoviId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getEjerci() == castOther.getEjerci())
				&& (this.getCoddel() == castOther.getCoddel()) && (this.getCodcli() == castOther.getCodcli())
				&& ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
						&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())))
				&& ((this.getStkini() == castOther.getStkini()) || (this.getStkini() != null
						&& castOther.getStkini() != null && this.getStkini().equals(castOther.getStkini())))
				&& ((this.getUnie01() == castOther.getUnie01()) || (this.getUnie01() != null
						&& castOther.getUnie01() != null && this.getUnie01().equals(castOther.getUnie01())))
				&& ((this.getUnie02() == castOther.getUnie02()) || (this.getUnie02() != null
						&& castOther.getUnie02() != null && this.getUnie02().equals(castOther.getUnie02())))
				&& ((this.getUnie03() == castOther.getUnie03()) || (this.getUnie03() != null
						&& castOther.getUnie03() != null && this.getUnie03().equals(castOther.getUnie03())))
				&& ((this.getUnie04() == castOther.getUnie04()) || (this.getUnie04() != null
						&& castOther.getUnie04() != null && this.getUnie04().equals(castOther.getUnie04())))
				&& ((this.getUnie05() == castOther.getUnie05()) || (this.getUnie05() != null
						&& castOther.getUnie05() != null && this.getUnie05().equals(castOther.getUnie05())))
				&& ((this.getUnie06() == castOther.getUnie06()) || (this.getUnie06() != null
						&& castOther.getUnie06() != null && this.getUnie06().equals(castOther.getUnie06())))
				&& ((this.getUnie07() == castOther.getUnie07()) || (this.getUnie07() != null
						&& castOther.getUnie07() != null && this.getUnie07().equals(castOther.getUnie07())))
				&& ((this.getUnie08() == castOther.getUnie08()) || (this.getUnie08() != null
						&& castOther.getUnie08() != null && this.getUnie08().equals(castOther.getUnie08())))
				&& ((this.getUnie09() == castOther.getUnie09()) || (this.getUnie09() != null
						&& castOther.getUnie09() != null && this.getUnie09().equals(castOther.getUnie09())))
				&& ((this.getUnie10() == castOther.getUnie10()) || (this.getUnie10() != null
						&& castOther.getUnie10() != null && this.getUnie10().equals(castOther.getUnie10())))
				&& ((this.getUnie11() == castOther.getUnie11()) || (this.getUnie11() != null
						&& castOther.getUnie11() != null && this.getUnie11().equals(castOther.getUnie11())))
				&& ((this.getUnie12() == castOther.getUnie12()) || (this.getUnie12() != null
						&& castOther.getUnie12() != null && this.getUnie12().equals(castOther.getUnie12())))
				&& ((this.getUnis01() == castOther.getUnis01()) || (this.getUnis01() != null
						&& castOther.getUnis01() != null && this.getUnis01().equals(castOther.getUnis01())))
				&& ((this.getUnis02() == castOther.getUnis02()) || (this.getUnis02() != null
						&& castOther.getUnis02() != null && this.getUnis02().equals(castOther.getUnis02())))
				&& ((this.getUnis03() == castOther.getUnis03()) || (this.getUnis03() != null
						&& castOther.getUnis03() != null && this.getUnis03().equals(castOther.getUnis03())))
				&& ((this.getUnis04() == castOther.getUnis04()) || (this.getUnis04() != null
						&& castOther.getUnis04() != null && this.getUnis04().equals(castOther.getUnis04())))
				&& ((this.getUnis05() == castOther.getUnis05()) || (this.getUnis05() != null
						&& castOther.getUnis05() != null && this.getUnis05().equals(castOther.getUnis05())))
				&& ((this.getUnis06() == castOther.getUnis06()) || (this.getUnis06() != null
						&& castOther.getUnis06() != null && this.getUnis06().equals(castOther.getUnis06())))
				&& ((this.getUnis07() == castOther.getUnis07()) || (this.getUnis07() != null
						&& castOther.getUnis07() != null && this.getUnis07().equals(castOther.getUnis07())))
				&& ((this.getUnis08() == castOther.getUnis08()) || (this.getUnis08() != null
						&& castOther.getUnis08() != null && this.getUnis08().equals(castOther.getUnis08())))
				&& ((this.getUnis09() == castOther.getUnis09()) || (this.getUnis09() != null
						&& castOther.getUnis09() != null && this.getUnis09().equals(castOther.getUnis09())))
				&& ((this.getUnis10() == castOther.getUnis10()) || (this.getUnis10() != null
						&& castOther.getUnis10() != null && this.getUnis10().equals(castOther.getUnis10())))
				&& ((this.getUnis11() == castOther.getUnis11()) || (this.getUnis11() != null
						&& castOther.getUnis11() != null && this.getUnis11().equals(castOther.getUnis11())))
				&& ((this.getUnis12() == castOther.getUnis12()) || (this.getUnis12() != null
						&& castOther.getUnis12() != null && this.getUnis12().equals(castOther.getUnis12())))
				&& ((this.getUnir01() == castOther.getUnir01()) || (this.getUnir01() != null
						&& castOther.getUnir01() != null && this.getUnir01().equals(castOther.getUnir01())))
				&& ((this.getUnir02() == castOther.getUnir02()) || (this.getUnir02() != null
						&& castOther.getUnir02() != null && this.getUnir02().equals(castOther.getUnir02())))
				&& ((this.getUnir03() == castOther.getUnir03()) || (this.getUnir03() != null
						&& castOther.getUnir03() != null && this.getUnir03().equals(castOther.getUnir03())))
				&& ((this.getUnir04() == castOther.getUnir04()) || (this.getUnir04() != null
						&& castOther.getUnir04() != null && this.getUnir04().equals(castOther.getUnir04())))
				&& ((this.getUnir05() == castOther.getUnir05()) || (this.getUnir05() != null
						&& castOther.getUnir05() != null && this.getUnir05().equals(castOther.getUnir05())))
				&& ((this.getUnir06() == castOther.getUnir06()) || (this.getUnir06() != null
						&& castOther.getUnir06() != null && this.getUnir06().equals(castOther.getUnir06())))
				&& ((this.getUnir07() == castOther.getUnir07()) || (this.getUnir07() != null
						&& castOther.getUnir07() != null && this.getUnir07().equals(castOther.getUnir07())))
				&& ((this.getUnir08() == castOther.getUnir08()) || (this.getUnir08() != null
						&& castOther.getUnir08() != null && this.getUnir08().equals(castOther.getUnir08())))
				&& ((this.getUnir09() == castOther.getUnir09()) || (this.getUnir09() != null
						&& castOther.getUnir09() != null && this.getUnir09().equals(castOther.getUnir09())))
				&& ((this.getUnir10() == castOther.getUnir10()) || (this.getUnir10() != null
						&& castOther.getUnir10() != null && this.getUnir10().equals(castOther.getUnir10())))
				&& ((this.getUnir11() == castOther.getUnir11()) || (this.getUnir11() != null
						&& castOther.getUnir11() != null && this.getUnir11().equals(castOther.getUnir11())))
				&& ((this.getUnir12() == castOther.getUnir12()) || (this.getUnir12() != null
						&& castOther.getUnir12() != null && this.getUnir12().equals(castOther.getUnir12())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getEjerci();
		result = 37 * result + this.getCoddel();
		result = 37 * result + this.getCodcli();
		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		result = 37 * result + (getStkini() == null ? 0 : this.getStkini().hashCode());
		result = 37 * result + (getUnie01() == null ? 0 : this.getUnie01().hashCode());
		result = 37 * result + (getUnie02() == null ? 0 : this.getUnie02().hashCode());
		result = 37 * result + (getUnie03() == null ? 0 : this.getUnie03().hashCode());
		result = 37 * result + (getUnie04() == null ? 0 : this.getUnie04().hashCode());
		result = 37 * result + (getUnie05() == null ? 0 : this.getUnie05().hashCode());
		result = 37 * result + (getUnie06() == null ? 0 : this.getUnie06().hashCode());
		result = 37 * result + (getUnie07() == null ? 0 : this.getUnie07().hashCode());
		result = 37 * result + (getUnie08() == null ? 0 : this.getUnie08().hashCode());
		result = 37 * result + (getUnie09() == null ? 0 : this.getUnie09().hashCode());
		result = 37 * result + (getUnie10() == null ? 0 : this.getUnie10().hashCode());
		result = 37 * result + (getUnie11() == null ? 0 : this.getUnie11().hashCode());
		result = 37 * result + (getUnie12() == null ? 0 : this.getUnie12().hashCode());
		result = 37 * result + (getUnis01() == null ? 0 : this.getUnis01().hashCode());
		result = 37 * result + (getUnis02() == null ? 0 : this.getUnis02().hashCode());
		result = 37 * result + (getUnis03() == null ? 0 : this.getUnis03().hashCode());
		result = 37 * result + (getUnis04() == null ? 0 : this.getUnis04().hashCode());
		result = 37 * result + (getUnis05() == null ? 0 : this.getUnis05().hashCode());
		result = 37 * result + (getUnis06() == null ? 0 : this.getUnis06().hashCode());
		result = 37 * result + (getUnis07() == null ? 0 : this.getUnis07().hashCode());
		result = 37 * result + (getUnis08() == null ? 0 : this.getUnis08().hashCode());
		result = 37 * result + (getUnis09() == null ? 0 : this.getUnis09().hashCode());
		result = 37 * result + (getUnis10() == null ? 0 : this.getUnis10().hashCode());
		result = 37 * result + (getUnis11() == null ? 0 : this.getUnis11().hashCode());
		result = 37 * result + (getUnis12() == null ? 0 : this.getUnis12().hashCode());
		result = 37 * result + (getUnir01() == null ? 0 : this.getUnir01().hashCode());
		result = 37 * result + (getUnir02() == null ? 0 : this.getUnir02().hashCode());
		result = 37 * result + (getUnir03() == null ? 0 : this.getUnir03().hashCode());
		result = 37 * result + (getUnir04() == null ? 0 : this.getUnir04().hashCode());
		result = 37 * result + (getUnir05() == null ? 0 : this.getUnir05().hashCode());
		result = 37 * result + (getUnir06() == null ? 0 : this.getUnir06().hashCode());
		result = 37 * result + (getUnir07() == null ? 0 : this.getUnir07().hashCode());
		result = 37 * result + (getUnir08() == null ? 0 : this.getUnir08().hashCode());
		result = 37 * result + (getUnir09() == null ? 0 : this.getUnir09().hashCode());
		result = 37 * result + (getUnir10() == null ? 0 : this.getUnir10().hashCode());
		result = 37 * result + (getUnir11() == null ? 0 : this.getUnir11().hashCode());
		result = 37 * result + (getUnir12() == null ? 0 : this.getUnir12().hashCode());
		return result;
	}

}
