package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Zacumovi generated by hbm2java
 */
public class Zacumovi implements java.io.Serializable {

	private ZacumoviId id;

	public Zacumovi() {
	}

	public Zacumovi(ZacumoviId id) {
		this.id = id;
	}

	public ZacumoviId getId() {
		return this.id;
	}

	public void setId(ZacumoviId id) {
		this.id = id;
	}

}
