package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Zartic generated by hbm2java
 */
public class Zartic implements java.io.Serializable {

	private ZarticId id;

	public Zartic() {
	}

	public Zartic(ZarticId id) {
		this.id = id;
	}

	public ZarticId getId() {
		return this.id;
	}

	public void setId(ZarticId id) {
		this.id = id;
	}

}
