package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ZarticId generated by hbm2java
 */
public class ZarticId implements java.io.Serializable {

	private short codemp;
	private short codcli;
	private String codart;
	private String descri;
	private BigDecimal kgsuni;
	private BigDecimal facbas;
	private String basalm;
	private BigDecimal precio;
	private BigDecimal stkmin;
	private char baralm;
	private char caduci;
	private String tipzon;
	private BigDecimal volume;
	private String codbar;
	private Character ctlser;
	private Character adecua;
	private Character barcpe;
	private String basman;
	private Character barman;
	private String basmen;
	private Character barmen;
	private String basmsa;
	private Character barmsa;
	private Character envweb;
	private String codkit;
	private Integer codcom;

	public ZarticId() {
	}

	public ZarticId(short codemp, short codcli, String descri, BigDecimal kgsuni, BigDecimal facbas, String basalm,
			char baralm, char caduci) {
		this.codemp = codemp;
		this.codcli = codcli;
		this.descri = descri;
		this.kgsuni = kgsuni;
		this.facbas = facbas;
		this.basalm = basalm;
		this.baralm = baralm;
		this.caduci = caduci;
	}

	public ZarticId(short codemp, short codcli, String codart, String descri, BigDecimal kgsuni, BigDecimal facbas,
			String basalm, BigDecimal precio, BigDecimal stkmin, char baralm, char caduci, String tipzon,
			BigDecimal volume, String codbar, Character ctlser, Character adecua, Character barcpe, String basman,
			Character barman, String basmen, Character barmen, String basmsa, Character barmsa, Character envweb,
			String codkit, Integer codcom) {
		this.codemp = codemp;
		this.codcli = codcli;
		this.codart = codart;
		this.descri = descri;
		this.kgsuni = kgsuni;
		this.facbas = facbas;
		this.basalm = basalm;
		this.precio = precio;
		this.stkmin = stkmin;
		this.baralm = baralm;
		this.caduci = caduci;
		this.tipzon = tipzon;
		this.volume = volume;
		this.codbar = codbar;
		this.ctlser = ctlser;
		this.adecua = adecua;
		this.barcpe = barcpe;
		this.basman = basman;
		this.barman = barman;
		this.basmen = basmen;
		this.barmen = barmen;
		this.basmsa = basmsa;
		this.barmsa = barmsa;
		this.envweb = envweb;
		this.codkit = codkit;
		this.codcom = codcom;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public BigDecimal getKgsuni() {
		return this.kgsuni;
	}

	public void setKgsuni(BigDecimal kgsuni) {
		this.kgsuni = kgsuni;
	}

	public BigDecimal getFacbas() {
		return this.facbas;
	}

	public void setFacbas(BigDecimal facbas) {
		this.facbas = facbas;
	}

	public String getBasalm() {
		return this.basalm;
	}

	public void setBasalm(String basalm) {
		this.basalm = basalm;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public BigDecimal getStkmin() {
		return this.stkmin;
	}

	public void setStkmin(BigDecimal stkmin) {
		this.stkmin = stkmin;
	}

	public char getBaralm() {
		return this.baralm;
	}

	public void setBaralm(char baralm) {
		this.baralm = baralm;
	}

	public char getCaduci() {
		return this.caduci;
	}

	public void setCaduci(char caduci) {
		this.caduci = caduci;
	}

	public String getTipzon() {
		return this.tipzon;
	}

	public void setTipzon(String tipzon) {
		this.tipzon = tipzon;
	}

	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	public String getCodbar() {
		return this.codbar;
	}

	public void setCodbar(String codbar) {
		this.codbar = codbar;
	}

	public Character getCtlser() {
		return this.ctlser;
	}

	public void setCtlser(Character ctlser) {
		this.ctlser = ctlser;
	}

	public Character getAdecua() {
		return this.adecua;
	}

	public void setAdecua(Character adecua) {
		this.adecua = adecua;
	}

	public Character getBarcpe() {
		return this.barcpe;
	}

	public void setBarcpe(Character barcpe) {
		this.barcpe = barcpe;
	}

	public String getBasman() {
		return this.basman;
	}

	public void setBasman(String basman) {
		this.basman = basman;
	}

	public Character getBarman() {
		return this.barman;
	}

	public void setBarman(Character barman) {
		this.barman = barman;
	}

	public String getBasmen() {
		return this.basmen;
	}

	public void setBasmen(String basmen) {
		this.basmen = basmen;
	}

	public Character getBarmen() {
		return this.barmen;
	}

	public void setBarmen(Character barmen) {
		this.barmen = barmen;
	}

	public String getBasmsa() {
		return this.basmsa;
	}

	public void setBasmsa(String basmsa) {
		this.basmsa = basmsa;
	}

	public Character getBarmsa() {
		return this.barmsa;
	}

	public void setBarmsa(Character barmsa) {
		this.barmsa = barmsa;
	}

	public Character getEnvweb() {
		return this.envweb;
	}

	public void setEnvweb(Character envweb) {
		this.envweb = envweb;
	}

	public String getCodkit() {
		return this.codkit;
	}

	public void setCodkit(String codkit) {
		this.codkit = codkit;
	}

	public Integer getCodcom() {
		return this.codcom;
	}

	public void setCodcom(Integer codcom) {
		this.codcom = codcom;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZarticId))
			return false;
		ZarticId castOther = (ZarticId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCodcli() == castOther.getCodcli())
				&& ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
						&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())))
				&& ((this.getDescri() == castOther.getDescri()) || (this.getDescri() != null
						&& castOther.getDescri() != null && this.getDescri().equals(castOther.getDescri())))
				&& ((this.getKgsuni() == castOther.getKgsuni()) || (this.getKgsuni() != null
						&& castOther.getKgsuni() != null && this.getKgsuni().equals(castOther.getKgsuni())))
				&& ((this.getFacbas() == castOther.getFacbas()) || (this.getFacbas() != null
						&& castOther.getFacbas() != null && this.getFacbas().equals(castOther.getFacbas())))
				&& ((this.getBasalm() == castOther.getBasalm()) || (this.getBasalm() != null
						&& castOther.getBasalm() != null && this.getBasalm().equals(castOther.getBasalm())))
				&& ((this.getPrecio() == castOther.getPrecio()) || (this.getPrecio() != null
						&& castOther.getPrecio() != null && this.getPrecio().equals(castOther.getPrecio())))
				&& ((this.getStkmin() == castOther.getStkmin()) || (this.getStkmin() != null
						&& castOther.getStkmin() != null && this.getStkmin().equals(castOther.getStkmin())))
				&& (this.getBaralm() == castOther.getBaralm()) && (this.getCaduci() == castOther.getCaduci())
				&& ((this.getTipzon() == castOther.getTipzon()) || (this.getTipzon() != null
						&& castOther.getTipzon() != null && this.getTipzon().equals(castOther.getTipzon())))
				&& ((this.getVolume() == castOther.getVolume()) || (this.getVolume() != null
						&& castOther.getVolume() != null && this.getVolume().equals(castOther.getVolume())))
				&& ((this.getCodbar() == castOther.getCodbar()) || (this.getCodbar() != null
						&& castOther.getCodbar() != null && this.getCodbar().equals(castOther.getCodbar())))
				&& ((this.getCtlser() == castOther.getCtlser()) || (this.getCtlser() != null
						&& castOther.getCtlser() != null && this.getCtlser().equals(castOther.getCtlser())))
				&& ((this.getAdecua() == castOther.getAdecua()) || (this.getAdecua() != null
						&& castOther.getAdecua() != null && this.getAdecua().equals(castOther.getAdecua())))
				&& ((this.getBarcpe() == castOther.getBarcpe()) || (this.getBarcpe() != null
						&& castOther.getBarcpe() != null && this.getBarcpe().equals(castOther.getBarcpe())))
				&& ((this.getBasman() == castOther.getBasman()) || (this.getBasman() != null
						&& castOther.getBasman() != null && this.getBasman().equals(castOther.getBasman())))
				&& ((this.getBarman() == castOther.getBarman()) || (this.getBarman() != null
						&& castOther.getBarman() != null && this.getBarman().equals(castOther.getBarman())))
				&& ((this.getBasmen() == castOther.getBasmen()) || (this.getBasmen() != null
						&& castOther.getBasmen() != null && this.getBasmen().equals(castOther.getBasmen())))
				&& ((this.getBarmen() == castOther.getBarmen()) || (this.getBarmen() != null
						&& castOther.getBarmen() != null && this.getBarmen().equals(castOther.getBarmen())))
				&& ((this.getBasmsa() == castOther.getBasmsa()) || (this.getBasmsa() != null
						&& castOther.getBasmsa() != null && this.getBasmsa().equals(castOther.getBasmsa())))
				&& ((this.getBarmsa() == castOther.getBarmsa()) || (this.getBarmsa() != null
						&& castOther.getBarmsa() != null && this.getBarmsa().equals(castOther.getBarmsa())))
				&& ((this.getEnvweb() == castOther.getEnvweb()) || (this.getEnvweb() != null
						&& castOther.getEnvweb() != null && this.getEnvweb().equals(castOther.getEnvweb())))
				&& ((this.getCodkit() == castOther.getCodkit()) || (this.getCodkit() != null
						&& castOther.getCodkit() != null && this.getCodkit().equals(castOther.getCodkit())))
				&& ((this.getCodcom() == castOther.getCodcom()) || (this.getCodcom() != null
						&& castOther.getCodcom() != null && this.getCodcom().equals(castOther.getCodcom())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCodcli();
		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		result = 37 * result + (getDescri() == null ? 0 : this.getDescri().hashCode());
		result = 37 * result + (getKgsuni() == null ? 0 : this.getKgsuni().hashCode());
		result = 37 * result + (getFacbas() == null ? 0 : this.getFacbas().hashCode());
		result = 37 * result + (getBasalm() == null ? 0 : this.getBasalm().hashCode());
		result = 37 * result + (getPrecio() == null ? 0 : this.getPrecio().hashCode());
		result = 37 * result + (getStkmin() == null ? 0 : this.getStkmin().hashCode());
		result = 37 * result + this.getBaralm();
		result = 37 * result + this.getCaduci();
		result = 37 * result + (getTipzon() == null ? 0 : this.getTipzon().hashCode());
		result = 37 * result + (getVolume() == null ? 0 : this.getVolume().hashCode());
		result = 37 * result + (getCodbar() == null ? 0 : this.getCodbar().hashCode());
		result = 37 * result + (getCtlser() == null ? 0 : this.getCtlser().hashCode());
		result = 37 * result + (getAdecua() == null ? 0 : this.getAdecua().hashCode());
		result = 37 * result + (getBarcpe() == null ? 0 : this.getBarcpe().hashCode());
		result = 37 * result + (getBasman() == null ? 0 : this.getBasman().hashCode());
		result = 37 * result + (getBarman() == null ? 0 : this.getBarman().hashCode());
		result = 37 * result + (getBasmen() == null ? 0 : this.getBasmen().hashCode());
		result = 37 * result + (getBarmen() == null ? 0 : this.getBarmen().hashCode());
		result = 37 * result + (getBasmsa() == null ? 0 : this.getBasmsa().hashCode());
		result = 37 * result + (getBarmsa() == null ? 0 : this.getBarmsa().hashCode());
		result = 37 * result + (getEnvweb() == null ? 0 : this.getEnvweb().hashCode());
		result = 37 * result + (getCodkit() == null ? 0 : this.getCodkit().hashCode());
		result = 37 * result + (getCodcom() == null ? 0 : this.getCodcom().hashCode());
		return result;
	}

}
