package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ZlinalbaId generated by hbm2java
 */
public class ZlinalbaId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private short codcli;
	private char tipalb;
	private String seralb;
	private short ejerci;
	private int numalb;
	private short numlin;
	private String codart;
	private BigDecimal cantid;
	private short bultos;
	private BigDecimal kilos;
	private BigDecimal volume;
	private BigDecimal precio;
	private Date fecalb;
	private Date fcaduc;
	private String horizo;
	private Short vertic;
	private Character baralm;
	private BigDecimal udsalm;
	private String basalm;
	private String lotefb;
	private String tipemb;
	private BigDecimal dtoli1;
	private BigDecimal dtoli2;
	private String descri;
	private String serped;
	private Short ejeped;
	private Integer numped;
	private Short linped;
	private Character estado;
	private Short palets;
	private String nserie;
	private String idsscc;
	private Integer nopick;
	private Short lnpick;
	private String codkit;

	public ZlinalbaId() {
	}

	public ZlinalbaId(short codemp, short coddel, short codcli, char tipalb, String seralb, short ejerci, int numalb,
			short numlin, BigDecimal cantid, short bultos, BigDecimal kilos, Date fecalb) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.codcli = codcli;
		this.tipalb = tipalb;
		this.seralb = seralb;
		this.ejerci = ejerci;
		this.numalb = numalb;
		this.numlin = numlin;
		this.cantid = cantid;
		this.bultos = bultos;
		this.kilos = kilos;
		this.fecalb = fecalb;
	}

	public ZlinalbaId(short codemp, short coddel, short codcli, char tipalb, String seralb, short ejerci, int numalb,
			short numlin, String codart, BigDecimal cantid, short bultos, BigDecimal kilos, BigDecimal volume,
			BigDecimal precio, Date fecalb, Date fcaduc, String horizo, Short vertic, Character baralm,
			BigDecimal udsalm, String basalm, String lotefb, String tipemb, BigDecimal dtoli1, BigDecimal dtoli2,
			String descri, String serped, Short ejeped, Integer numped, Short linped, Character estado, Short palets,
			String nserie, String idsscc, Integer nopick, Short lnpick, String codkit) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.codcli = codcli;
		this.tipalb = tipalb;
		this.seralb = seralb;
		this.ejerci = ejerci;
		this.numalb = numalb;
		this.numlin = numlin;
		this.codart = codart;
		this.cantid = cantid;
		this.bultos = bultos;
		this.kilos = kilos;
		this.volume = volume;
		this.precio = precio;
		this.fecalb = fecalb;
		this.fcaduc = fcaduc;
		this.horizo = horizo;
		this.vertic = vertic;
		this.baralm = baralm;
		this.udsalm = udsalm;
		this.basalm = basalm;
		this.lotefb = lotefb;
		this.tipemb = tipemb;
		this.dtoli1 = dtoli1;
		this.dtoli2 = dtoli2;
		this.descri = descri;
		this.serped = serped;
		this.ejeped = ejeped;
		this.numped = numped;
		this.linped = linped;
		this.estado = estado;
		this.palets = palets;
		this.nserie = nserie;
		this.idsscc = idsscc;
		this.nopick = nopick;
		this.lnpick = lnpick;
		this.codkit = codkit;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public char getTipalb() {
		return this.tipalb;
	}

	public void setTipalb(char tipalb) {
		this.tipalb = tipalb;
	}

	public String getSeralb() {
		return this.seralb;
	}

	public void setSeralb(String seralb) {
		this.seralb = seralb;
	}

	public short getEjerci() {
		return this.ejerci;
	}

	public void setEjerci(short ejerci) {
		this.ejerci = ejerci;
	}

	public int getNumalb() {
		return this.numalb;
	}

	public void setNumalb(int numalb) {
		this.numalb = numalb;
	}

	public short getNumlin() {
		return this.numlin;
	}

	public void setNumlin(short numlin) {
		this.numlin = numlin;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public BigDecimal getCantid() {
		return this.cantid;
	}

	public void setCantid(BigDecimal cantid) {
		this.cantid = cantid;
	}

	public short getBultos() {
		return this.bultos;
	}

	public void setBultos(short bultos) {
		this.bultos = bultos;
	}

	public BigDecimal getKilos() {
		return this.kilos;
	}

	public void setKilos(BigDecimal kilos) {
		this.kilos = kilos;
	}

	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public Date getFecalb() {
		return this.fecalb;
	}

	public void setFecalb(Date fecalb) {
		this.fecalb = fecalb;
	}

	public Date getFcaduc() {
		return this.fcaduc;
	}

	public void setFcaduc(Date fcaduc) {
		this.fcaduc = fcaduc;
	}

	public String getHorizo() {
		return this.horizo;
	}

	public void setHorizo(String horizo) {
		this.horizo = horizo;
	}

	public Short getVertic() {
		return this.vertic;
	}

	public void setVertic(Short vertic) {
		this.vertic = vertic;
	}

	public Character getBaralm() {
		return this.baralm;
	}

	public void setBaralm(Character baralm) {
		this.baralm = baralm;
	}

	public BigDecimal getUdsalm() {
		return this.udsalm;
	}

	public void setUdsalm(BigDecimal udsalm) {
		this.udsalm = udsalm;
	}

	public String getBasalm() {
		return this.basalm;
	}

	public void setBasalm(String basalm) {
		this.basalm = basalm;
	}

	public String getLotefb() {
		return this.lotefb;
	}

	public void setLotefb(String lotefb) {
		this.lotefb = lotefb;
	}

	public String getTipemb() {
		return this.tipemb;
	}

	public void setTipemb(String tipemb) {
		this.tipemb = tipemb;
	}

	public BigDecimal getDtoli1() {
		return this.dtoli1;
	}

	public void setDtoli1(BigDecimal dtoli1) {
		this.dtoli1 = dtoli1;
	}

	public BigDecimal getDtoli2() {
		return this.dtoli2;
	}

	public void setDtoli2(BigDecimal dtoli2) {
		this.dtoli2 = dtoli2;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public String getSerped() {
		return this.serped;
	}

	public void setSerped(String serped) {
		this.serped = serped;
	}

	public Short getEjeped() {
		return this.ejeped;
	}

	public void setEjeped(Short ejeped) {
		this.ejeped = ejeped;
	}

	public Integer getNumped() {
		return this.numped;
	}

	public void setNumped(Integer numped) {
		this.numped = numped;
	}

	public Short getLinped() {
		return this.linped;
	}

	public void setLinped(Short linped) {
		this.linped = linped;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public Short getPalets() {
		return this.palets;
	}

	public void setPalets(Short palets) {
		this.palets = palets;
	}

	public String getNserie() {
		return this.nserie;
	}

	public void setNserie(String nserie) {
		this.nserie = nserie;
	}

	public String getIdsscc() {
		return this.idsscc;
	}

	public void setIdsscc(String idsscc) {
		this.idsscc = idsscc;
	}

	public Integer getNopick() {
		return this.nopick;
	}

	public void setNopick(Integer nopick) {
		this.nopick = nopick;
	}

	public Short getLnpick() {
		return this.lnpick;
	}

	public void setLnpick(Short lnpick) {
		this.lnpick = lnpick;
	}

	public String getCodkit() {
		return this.codkit;
	}

	public void setCodkit(String codkit) {
		this.codkit = codkit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZlinalbaId))
			return false;
		ZlinalbaId castOther = (ZlinalbaId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& (this.getCodcli() == castOther.getCodcli()) && (this.getTipalb() == castOther.getTipalb())
				&& ((this.getSeralb() == castOther.getSeralb()) || (this.getSeralb() != null
						&& castOther.getSeralb() != null && this.getSeralb().equals(castOther.getSeralb())))
				&& (this.getEjerci() == castOther.getEjerci()) && (this.getNumalb() == castOther.getNumalb())
				&& (this.getNumlin() == castOther.getNumlin())
				&& ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
						&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())))
				&& ((this.getCantid() == castOther.getCantid()) || (this.getCantid() != null
						&& castOther.getCantid() != null && this.getCantid().equals(castOther.getCantid())))
				&& (this.getBultos() == castOther.getBultos())
				&& ((this.getKilos() == castOther.getKilos()) || (this.getKilos() != null
						&& castOther.getKilos() != null && this.getKilos().equals(castOther.getKilos())))
				&& ((this.getVolume() == castOther.getVolume()) || (this.getVolume() != null
						&& castOther.getVolume() != null && this.getVolume().equals(castOther.getVolume())))
				&& ((this.getPrecio() == castOther.getPrecio()) || (this.getPrecio() != null
						&& castOther.getPrecio() != null && this.getPrecio().equals(castOther.getPrecio())))
				&& ((this.getFecalb() == castOther.getFecalb()) || (this.getFecalb() != null
						&& castOther.getFecalb() != null && this.getFecalb().equals(castOther.getFecalb())))
				&& ((this.getFcaduc() == castOther.getFcaduc()) || (this.getFcaduc() != null
						&& castOther.getFcaduc() != null && this.getFcaduc().equals(castOther.getFcaduc())))
				&& ((this.getHorizo() == castOther.getHorizo()) || (this.getHorizo() != null
						&& castOther.getHorizo() != null && this.getHorizo().equals(castOther.getHorizo())))
				&& ((this.getVertic() == castOther.getVertic()) || (this.getVertic() != null
						&& castOther.getVertic() != null && this.getVertic().equals(castOther.getVertic())))
				&& ((this.getBaralm() == castOther.getBaralm()) || (this.getBaralm() != null
						&& castOther.getBaralm() != null && this.getBaralm().equals(castOther.getBaralm())))
				&& ((this.getUdsalm() == castOther.getUdsalm()) || (this.getUdsalm() != null
						&& castOther.getUdsalm() != null && this.getUdsalm().equals(castOther.getUdsalm())))
				&& ((this.getBasalm() == castOther.getBasalm()) || (this.getBasalm() != null
						&& castOther.getBasalm() != null && this.getBasalm().equals(castOther.getBasalm())))
				&& ((this.getLotefb() == castOther.getLotefb()) || (this.getLotefb() != null
						&& castOther.getLotefb() != null && this.getLotefb().equals(castOther.getLotefb())))
				&& ((this.getTipemb() == castOther.getTipemb()) || (this.getTipemb() != null
						&& castOther.getTipemb() != null && this.getTipemb().equals(castOther.getTipemb())))
				&& ((this.getDtoli1() == castOther.getDtoli1()) || (this.getDtoli1() != null
						&& castOther.getDtoli1() != null && this.getDtoli1().equals(castOther.getDtoli1())))
				&& ((this.getDtoli2() == castOther.getDtoli2()) || (this.getDtoli2() != null
						&& castOther.getDtoli2() != null && this.getDtoli2().equals(castOther.getDtoli2())))
				&& ((this.getDescri() == castOther.getDescri()) || (this.getDescri() != null
						&& castOther.getDescri() != null && this.getDescri().equals(castOther.getDescri())))
				&& ((this.getSerped() == castOther.getSerped()) || (this.getSerped() != null
						&& castOther.getSerped() != null && this.getSerped().equals(castOther.getSerped())))
				&& ((this.getEjeped() == castOther.getEjeped()) || (this.getEjeped() != null
						&& castOther.getEjeped() != null && this.getEjeped().equals(castOther.getEjeped())))
				&& ((this.getNumped() == castOther.getNumped()) || (this.getNumped() != null
						&& castOther.getNumped() != null && this.getNumped().equals(castOther.getNumped())))
				&& ((this.getLinped() == castOther.getLinped()) || (this.getLinped() != null
						&& castOther.getLinped() != null && this.getLinped().equals(castOther.getLinped())))
				&& ((this.getEstado() == castOther.getEstado()) || (this.getEstado() != null
						&& castOther.getEstado() != null && this.getEstado().equals(castOther.getEstado())))
				&& ((this.getPalets() == castOther.getPalets()) || (this.getPalets() != null
						&& castOther.getPalets() != null && this.getPalets().equals(castOther.getPalets())))
				&& ((this.getNserie() == castOther.getNserie()) || (this.getNserie() != null
						&& castOther.getNserie() != null && this.getNserie().equals(castOther.getNserie())))
				&& ((this.getIdsscc() == castOther.getIdsscc()) || (this.getIdsscc() != null
						&& castOther.getIdsscc() != null && this.getIdsscc().equals(castOther.getIdsscc())))
				&& ((this.getNopick() == castOther.getNopick()) || (this.getNopick() != null
						&& castOther.getNopick() != null && this.getNopick().equals(castOther.getNopick())))
				&& ((this.getLnpick() == castOther.getLnpick()) || (this.getLnpick() != null
						&& castOther.getLnpick() != null && this.getLnpick().equals(castOther.getLnpick())))
				&& ((this.getCodkit() == castOther.getCodkit()) || (this.getCodkit() != null
						&& castOther.getCodkit() != null && this.getCodkit().equals(castOther.getCodkit())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + this.getCodcli();
		result = 37 * result + this.getTipalb();
		result = 37 * result + (getSeralb() == null ? 0 : this.getSeralb().hashCode());
		result = 37 * result + this.getEjerci();
		result = 37 * result + this.getNumalb();
		result = 37 * result + this.getNumlin();
		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		result = 37 * result + (getCantid() == null ? 0 : this.getCantid().hashCode());
		result = 37 * result + this.getBultos();
		result = 37 * result + (getKilos() == null ? 0 : this.getKilos().hashCode());
		result = 37 * result + (getVolume() == null ? 0 : this.getVolume().hashCode());
		result = 37 * result + (getPrecio() == null ? 0 : this.getPrecio().hashCode());
		result = 37 * result + (getFecalb() == null ? 0 : this.getFecalb().hashCode());
		result = 37 * result + (getFcaduc() == null ? 0 : this.getFcaduc().hashCode());
		result = 37 * result + (getHorizo() == null ? 0 : this.getHorizo().hashCode());
		result = 37 * result + (getVertic() == null ? 0 : this.getVertic().hashCode());
		result = 37 * result + (getBaralm() == null ? 0 : this.getBaralm().hashCode());
		result = 37 * result + (getUdsalm() == null ? 0 : this.getUdsalm().hashCode());
		result = 37 * result + (getBasalm() == null ? 0 : this.getBasalm().hashCode());
		result = 37 * result + (getLotefb() == null ? 0 : this.getLotefb().hashCode());
		result = 37 * result + (getTipemb() == null ? 0 : this.getTipemb().hashCode());
		result = 37 * result + (getDtoli1() == null ? 0 : this.getDtoli1().hashCode());
		result = 37 * result + (getDtoli2() == null ? 0 : this.getDtoli2().hashCode());
		result = 37 * result + (getDescri() == null ? 0 : this.getDescri().hashCode());
		result = 37 * result + (getSerped() == null ? 0 : this.getSerped().hashCode());
		result = 37 * result + (getEjeped() == null ? 0 : this.getEjeped().hashCode());
		result = 37 * result + (getNumped() == null ? 0 : this.getNumped().hashCode());
		result = 37 * result + (getLinped() == null ? 0 : this.getLinped().hashCode());
		result = 37 * result + (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37 * result + (getPalets() == null ? 0 : this.getPalets().hashCode());
		result = 37 * result + (getNserie() == null ? 0 : this.getNserie().hashCode());
		result = 37 * result + (getIdsscc() == null ? 0 : this.getIdsscc().hashCode());
		result = 37 * result + (getNopick() == null ? 0 : this.getNopick().hashCode());
		result = 37 * result + (getLnpick() == null ? 0 : this.getLnpick().hashCode());
		result = 37 * result + (getCodkit() == null ? 0 : this.getCodkit().hashCode());
		return result;
	}

}
