package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Zlinalba generated by hbm2java
 */
public class Zlinalba implements java.io.Serializable {

	private ZlinalbaId id;

	public Zlinalba() {
	}

	public Zlinalba(ZlinalbaId id) {
		this.id = id;
	}

	public ZlinalbaId getId() {
		return this.id;
	}

	public void setId(ZlinalbaId id) {
		this.id = id;
	}

}
