package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Zlinpedi generated by hbm2java
 */
public class Zlinpedi implements java.io.Serializable {

	private ZlinpediId id;

	public Zlinpedi() {
	}

	public Zlinpedi(ZlinpediId id) {
		this.id = id;
	}

	public ZlinpediId getId() {
		return this.id;
	}

	public void setId(ZlinpediId id) {
		this.id = id;
	}

}
