package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ZlinpediId generated by hbm2java
 */
public class ZlinpediId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private short codcli;
	private char tipped;
	private String serped;
	private short ejeped;
	private int numped;
	private short numlin;
	private String codart;
	private BigDecimal cantid;
	private short bultos;
	private BigDecimal kilos;
	private BigDecimal volume;
	private BigDecimal precio;
	private BigDecimal dtoli1;
	private BigDecimal dtoli2;
	private String descri;
	private Character estado;
	private Character tipdoc;
	private BigDecimal tipiva;
	private Character edilin;
	private Short asocia;
	private Integer nopick;
	private Short lnpick;
	private String codkit;

	public ZlinpediId() {
	}

	public ZlinpediId(short codemp, short coddel, short codcli, char tipped, String serped, short ejeped, int numped,
			short numlin, BigDecimal cantid, short bultos, BigDecimal kilos) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.codcli = codcli;
		this.tipped = tipped;
		this.serped = serped;
		this.ejeped = ejeped;
		this.numped = numped;
		this.numlin = numlin;
		this.cantid = cantid;
		this.bultos = bultos;
		this.kilos = kilos;
	}

	public ZlinpediId(short codemp, short coddel, short codcli, char tipped, String serped, short ejeped, int numped,
			short numlin, String codart, BigDecimal cantid, short bultos, BigDecimal kilos, BigDecimal volume,
			BigDecimal precio, BigDecimal dtoli1, BigDecimal dtoli2, String descri, Character estado, Character tipdoc,
			BigDecimal tipiva, Character edilin, Short asocia, Integer nopick, Short lnpick, String codkit) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.codcli = codcli;
		this.tipped = tipped;
		this.serped = serped;
		this.ejeped = ejeped;
		this.numped = numped;
		this.numlin = numlin;
		this.codart = codart;
		this.cantid = cantid;
		this.bultos = bultos;
		this.kilos = kilos;
		this.volume = volume;
		this.precio = precio;
		this.dtoli1 = dtoli1;
		this.dtoli2 = dtoli2;
		this.descri = descri;
		this.estado = estado;
		this.tipdoc = tipdoc;
		this.tipiva = tipiva;
		this.edilin = edilin;
		this.asocia = asocia;
		this.nopick = nopick;
		this.lnpick = lnpick;
		this.codkit = codkit;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public char getTipped() {
		return this.tipped;
	}

	public void setTipped(char tipped) {
		this.tipped = tipped;
	}

	public String getSerped() {
		return this.serped;
	}

	public void setSerped(String serped) {
		this.serped = serped;
	}

	public short getEjeped() {
		return this.ejeped;
	}

	public void setEjeped(short ejeped) {
		this.ejeped = ejeped;
	}

	public int getNumped() {
		return this.numped;
	}

	public void setNumped(int numped) {
		this.numped = numped;
	}

	public short getNumlin() {
		return this.numlin;
	}

	public void setNumlin(short numlin) {
		this.numlin = numlin;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public BigDecimal getCantid() {
		return this.cantid;
	}

	public void setCantid(BigDecimal cantid) {
		this.cantid = cantid;
	}

	public short getBultos() {
		return this.bultos;
	}

	public void setBultos(short bultos) {
		this.bultos = bultos;
	}

	public BigDecimal getKilos() {
		return this.kilos;
	}

	public void setKilos(BigDecimal kilos) {
		this.kilos = kilos;
	}

	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public BigDecimal getDtoli1() {
		return this.dtoli1;
	}

	public void setDtoli1(BigDecimal dtoli1) {
		this.dtoli1 = dtoli1;
	}

	public BigDecimal getDtoli2() {
		return this.dtoli2;
	}

	public void setDtoli2(BigDecimal dtoli2) {
		this.dtoli2 = dtoli2;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public Character getTipdoc() {
		return this.tipdoc;
	}

	public void setTipdoc(Character tipdoc) {
		this.tipdoc = tipdoc;
	}

	public BigDecimal getTipiva() {
		return this.tipiva;
	}

	public void setTipiva(BigDecimal tipiva) {
		this.tipiva = tipiva;
	}

	public Character getEdilin() {
		return this.edilin;
	}

	public void setEdilin(Character edilin) {
		this.edilin = edilin;
	}

	public Short getAsocia() {
		return this.asocia;
	}

	public void setAsocia(Short asocia) {
		this.asocia = asocia;
	}

	public Integer getNopick() {
		return this.nopick;
	}

	public void setNopick(Integer nopick) {
		this.nopick = nopick;
	}

	public Short getLnpick() {
		return this.lnpick;
	}

	public void setLnpick(Short lnpick) {
		this.lnpick = lnpick;
	}

	public String getCodkit() {
		return this.codkit;
	}

	public void setCodkit(String codkit) {
		this.codkit = codkit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZlinpediId))
			return false;
		ZlinpediId castOther = (ZlinpediId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& (this.getCodcli() == castOther.getCodcli()) && (this.getTipped() == castOther.getTipped())
				&& ((this.getSerped() == castOther.getSerped()) || (this.getSerped() != null
						&& castOther.getSerped() != null && this.getSerped().equals(castOther.getSerped())))
				&& (this.getEjeped() == castOther.getEjeped()) && (this.getNumped() == castOther.getNumped())
				&& (this.getNumlin() == castOther.getNumlin())
				&& ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
						&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())))
				&& ((this.getCantid() == castOther.getCantid()) || (this.getCantid() != null
						&& castOther.getCantid() != null && this.getCantid().equals(castOther.getCantid())))
				&& (this.getBultos() == castOther.getBultos())
				&& ((this.getKilos() == castOther.getKilos()) || (this.getKilos() != null
						&& castOther.getKilos() != null && this.getKilos().equals(castOther.getKilos())))
				&& ((this.getVolume() == castOther.getVolume()) || (this.getVolume() != null
						&& castOther.getVolume() != null && this.getVolume().equals(castOther.getVolume())))
				&& ((this.getPrecio() == castOther.getPrecio()) || (this.getPrecio() != null
						&& castOther.getPrecio() != null && this.getPrecio().equals(castOther.getPrecio())))
				&& ((this.getDtoli1() == castOther.getDtoli1()) || (this.getDtoli1() != null
						&& castOther.getDtoli1() != null && this.getDtoli1().equals(castOther.getDtoli1())))
				&& ((this.getDtoli2() == castOther.getDtoli2()) || (this.getDtoli2() != null
						&& castOther.getDtoli2() != null && this.getDtoli2().equals(castOther.getDtoli2())))
				&& ((this.getDescri() == castOther.getDescri()) || (this.getDescri() != null
						&& castOther.getDescri() != null && this.getDescri().equals(castOther.getDescri())))
				&& ((this.getEstado() == castOther.getEstado()) || (this.getEstado() != null
						&& castOther.getEstado() != null && this.getEstado().equals(castOther.getEstado())))
				&& ((this.getTipdoc() == castOther.getTipdoc()) || (this.getTipdoc() != null
						&& castOther.getTipdoc() != null && this.getTipdoc().equals(castOther.getTipdoc())))
				&& ((this.getTipiva() == castOther.getTipiva()) || (this.getTipiva() != null
						&& castOther.getTipiva() != null && this.getTipiva().equals(castOther.getTipiva())))
				&& ((this.getEdilin() == castOther.getEdilin()) || (this.getEdilin() != null
						&& castOther.getEdilin() != null && this.getEdilin().equals(castOther.getEdilin())))
				&& ((this.getAsocia() == castOther.getAsocia()) || (this.getAsocia() != null
						&& castOther.getAsocia() != null && this.getAsocia().equals(castOther.getAsocia())))
				&& ((this.getNopick() == castOther.getNopick()) || (this.getNopick() != null
						&& castOther.getNopick() != null && this.getNopick().equals(castOther.getNopick())))
				&& ((this.getLnpick() == castOther.getLnpick()) || (this.getLnpick() != null
						&& castOther.getLnpick() != null && this.getLnpick().equals(castOther.getLnpick())))
				&& ((this.getCodkit() == castOther.getCodkit()) || (this.getCodkit() != null
						&& castOther.getCodkit() != null && this.getCodkit().equals(castOther.getCodkit())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + this.getCodcli();
		result = 37 * result + this.getTipped();
		result = 37 * result + (getSerped() == null ? 0 : this.getSerped().hashCode());
		result = 37 * result + this.getEjeped();
		result = 37 * result + this.getNumped();
		result = 37 * result + this.getNumlin();
		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		result = 37 * result + (getCantid() == null ? 0 : this.getCantid().hashCode());
		result = 37 * result + this.getBultos();
		result = 37 * result + (getKilos() == null ? 0 : this.getKilos().hashCode());
		result = 37 * result + (getVolume() == null ? 0 : this.getVolume().hashCode());
		result = 37 * result + (getPrecio() == null ? 0 : this.getPrecio().hashCode());
		result = 37 * result + (getDtoli1() == null ? 0 : this.getDtoli1().hashCode());
		result = 37 * result + (getDtoli2() == null ? 0 : this.getDtoli2().hashCode());
		result = 37 * result + (getDescri() == null ? 0 : this.getDescri().hashCode());
		result = 37 * result + (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37 * result + (getTipdoc() == null ? 0 : this.getTipdoc().hashCode());
		result = 37 * result + (getTipiva() == null ? 0 : this.getTipiva().hashCode());
		result = 37 * result + (getEdilin() == null ? 0 : this.getEdilin().hashCode());
		result = 37 * result + (getAsocia() == null ? 0 : this.getAsocia().hashCode());
		result = 37 * result + (getNopick() == null ? 0 : this.getNopick().hashCode());
		result = 37 * result + (getLnpick() == null ? 0 : this.getLnpick().hashCode());
		result = 37 * result + (getCodkit() == null ? 0 : this.getCodkit().hashCode());
		return result;
	}

}
