package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Zocupalm generated by hbm2java
 */
public class Zocupalm implements java.io.Serializable {

	private ZocupalmId id;

	public Zocupalm() {
	}

	public Zocupalm(ZocupalmId id) {
		this.id = id;
	}

	public ZocupalmId getId() {
		return this.id;
	}

	public void setId(ZocupalmId id) {
		this.id = id;
	}

}
