package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Zonasart generated by hbm2java
 */
public class Zonasart implements java.io.Serializable {

	private ZonasartId id;

	public Zonasart() {
	}

	public Zonasart(ZonasartId id) {
		this.id = id;
	}

	public ZonasartId getId() {
		return this.id;
	}

	public void setId(ZonasartId id) {
		this.id = id;
	}

}
