package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * ZonaslibId generated by hbm2java
 */
public class ZonaslibId implements java.io.Serializable {

	private String horizo;
	private Short vertic;
	private String basalm;
	private String descri;
	private String tipzon;

	public ZonaslibId() {
	}

	public ZonaslibId(String horizo, Short vertic, String basalm, String descri, String tipzon) {
		this.horizo = horizo;
		this.vertic = vertic;
		this.basalm = basalm;
		this.descri = descri;
		this.tipzon = tipzon;
	}

	public String getHorizo() {
		return this.horizo;
	}

	public void setHorizo(String horizo) {
		this.horizo = horizo;
	}

	public Short getVertic() {
		return this.vertic;
	}

	public void setVertic(Short vertic) {
		this.vertic = vertic;
	}

	public String getBasalm() {
		return this.basalm;
	}

	public void setBasalm(String basalm) {
		this.basalm = basalm;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public String getTipzon() {
		return this.tipzon;
	}

	public void setTipzon(String tipzon) {
		this.tipzon = tipzon;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZonaslibId))
			return false;
		ZonaslibId castOther = (ZonaslibId) other;

		return ((this.getHorizo() == castOther.getHorizo()) || (this.getHorizo() != null
				&& castOther.getHorizo() != null && this.getHorizo().equals(castOther.getHorizo())))
				&& ((this.getVertic() == castOther.getVertic()) || (this.getVertic() != null
						&& castOther.getVertic() != null && this.getVertic().equals(castOther.getVertic())))
				&& ((this.getBasalm() == castOther.getBasalm()) || (this.getBasalm() != null
						&& castOther.getBasalm() != null && this.getBasalm().equals(castOther.getBasalm())))
				&& ((this.getDescri() == castOther.getDescri()) || (this.getDescri() != null
						&& castOther.getDescri() != null && this.getDescri().equals(castOther.getDescri())))
				&& ((this.getTipzon() == castOther.getTipzon()) || (this.getTipzon() != null
						&& castOther.getTipzon() != null && this.getTipzon().equals(castOther.getTipzon())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHorizo() == null ? 0 : this.getHorizo().hashCode());
		result = 37 * result + (getVertic() == null ? 0 : this.getVertic().hashCode());
		result = 37 * result + (getBasalm() == null ? 0 : this.getBasalm().hashCode());
		result = 37 * result + (getDescri() == null ? 0 : this.getDescri().hashCode());
		result = 37 * result + (getTipzon() == null ? 0 : this.getTipzon().hashCode());
		return result;
	}

}
