package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ZonasartId generated by hbm2java
 */
public class ZonasartId implements java.io.Serializable {

	private String horizo;
	private Short vertic;
	private String lotefb;
	private Date fcaduc;
	private BigDecimal udsalm;
	private Integer udsart;
	private BigDecimal canalm;
	private Integer canart;
	private String tipzon;

	public ZonasartId() {
	}

	public ZonasartId(String horizo, Short vertic, String lotefb, Date fcaduc, BigDecimal udsalm, Integer udsart,
			BigDecimal canalm, Integer canart, String tipzon) {
		this.horizo = horizo;
		this.vertic = vertic;
		this.lotefb = lotefb;
		this.fcaduc = fcaduc;
		this.udsalm = udsalm;
		this.udsart = udsart;
		this.canalm = canalm;
		this.canart = canart;
		this.tipzon = tipzon;
	}

	public String getHorizo() {
		return this.horizo;
	}

	public void setHorizo(String horizo) {
		this.horizo = horizo;
	}

	public Short getVertic() {
		return this.vertic;
	}

	public void setVertic(Short vertic) {
		this.vertic = vertic;
	}

	public String getLotefb() {
		return this.lotefb;
	}

	public void setLotefb(String lotefb) {
		this.lotefb = lotefb;
	}

	public Date getFcaduc() {
		return this.fcaduc;
	}

	public void setFcaduc(Date fcaduc) {
		this.fcaduc = fcaduc;
	}

	public BigDecimal getUdsalm() {
		return this.udsalm;
	}

	public void setUdsalm(BigDecimal udsalm) {
		this.udsalm = udsalm;
	}

	public Integer getUdsart() {
		return this.udsart;
	}

	public void setUdsart(Integer udsart) {
		this.udsart = udsart;
	}

	public BigDecimal getCanalm() {
		return this.canalm;
	}

	public void setCanalm(BigDecimal canalm) {
		this.canalm = canalm;
	}

	public Integer getCanart() {
		return this.canart;
	}

	public void setCanart(Integer canart) {
		this.canart = canart;
	}

	public String getTipzon() {
		return this.tipzon;
	}

	public void setTipzon(String tipzon) {
		this.tipzon = tipzon;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZonasartId))
			return false;
		ZonasartId castOther = (ZonasartId) other;

		return ((this.getHorizo() == castOther.getHorizo()) || (this.getHorizo() != null
				&& castOther.getHorizo() != null && this.getHorizo().equals(castOther.getHorizo())))
				&& ((this.getVertic() == castOther.getVertic()) || (this.getVertic() != null
						&& castOther.getVertic() != null && this.getVertic().equals(castOther.getVertic())))
				&& ((this.getLotefb() == castOther.getLotefb()) || (this.getLotefb() != null
						&& castOther.getLotefb() != null && this.getLotefb().equals(castOther.getLotefb())))
				&& ((this.getFcaduc() == castOther.getFcaduc()) || (this.getFcaduc() != null
						&& castOther.getFcaduc() != null && this.getFcaduc().equals(castOther.getFcaduc())))
				&& ((this.getUdsalm() == castOther.getUdsalm()) || (this.getUdsalm() != null
						&& castOther.getUdsalm() != null && this.getUdsalm().equals(castOther.getUdsalm())))
				&& ((this.getUdsart() == castOther.getUdsart()) || (this.getUdsart() != null
						&& castOther.getUdsart() != null && this.getUdsart().equals(castOther.getUdsart())))
				&& ((this.getCanalm() == castOther.getCanalm()) || (this.getCanalm() != null
						&& castOther.getCanalm() != null && this.getCanalm().equals(castOther.getCanalm())))
				&& ((this.getCanart() == castOther.getCanart()) || (this.getCanart() != null
						&& castOther.getCanart() != null && this.getCanart().equals(castOther.getCanart())))
				&& ((this.getTipzon() == castOther.getTipzon()) || (this.getTipzon() != null
						&& castOther.getTipzon() != null && this.getTipzon().equals(castOther.getTipzon())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHorizo() == null ? 0 : this.getHorizo().hashCode());
		result = 37 * result + (getVertic() == null ? 0 : this.getVertic().hashCode());
		result = 37 * result + (getLotefb() == null ? 0 : this.getLotefb().hashCode());
		result = 37 * result + (getFcaduc() == null ? 0 : this.getFcaduc().hashCode());
		result = 37 * result + (getUdsalm() == null ? 0 : this.getUdsalm().hashCode());
		result = 37 * result + (getUdsart() == null ? 0 : this.getUdsart().hashCode());
		result = 37 * result + (getCanalm() == null ? 0 : this.getCanalm().hashCode());
		result = 37 * result + (getCanart() == null ? 0 : this.getCanart().hashCode());
		result = 37 * result + (getTipzon() == null ? 0 : this.getTipzon().hashCode());
		return result;
	}

}
