package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ZonaswkaId generated by hbm2java
 */
public class ZonaswkaId implements java.io.Serializable {

	private short codemp;
	private short coddel;
	private short codcli;
	private Short ejedoc;
	private Integer numdoc;
	private char tipalb;
	private String seralb;
	private short ejerci;
	private int numalb;
	private short numlin;
	private String codart;
	private String descri;
	private Character ctlser;
	private BigDecimal cantid;
	private short bultos;
	private BigDecimal kilos;
	private BigDecimal volume;
	private Short palets;
	private String horizo;
	private Short vertic;
	private Date fcaduc;
	private String lotefb;
	private String nserie;
	private Character indica;
	private BigDecimal canmov;
	private Character ctlcad;
	private Character ctllot;

	public ZonaswkaId() {
	}

	public ZonaswkaId(short codemp, short coddel, short codcli, char tipalb, String seralb, short ejerci, int numalb,
			short numlin, String codart, BigDecimal cantid, short bultos, BigDecimal kilos) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.codcli = codcli;
		this.tipalb = tipalb;
		this.seralb = seralb;
		this.ejerci = ejerci;
		this.numalb = numalb;
		this.numlin = numlin;
		this.codart = codart;
		this.cantid = cantid;
		this.bultos = bultos;
		this.kilos = kilos;
	}

	public ZonaswkaId(short codemp, short coddel, short codcli, Short ejedoc, Integer numdoc, char tipalb,
			String seralb, short ejerci, int numalb, short numlin, String codart, String descri, Character ctlser,
			BigDecimal cantid, short bultos, BigDecimal kilos, BigDecimal volume, Short palets, String horizo,
			Short vertic, Date fcaduc, String lotefb, String nserie, Character indica, BigDecimal canmov,
			Character ctlcad, Character ctllot) {
		this.codemp = codemp;
		this.coddel = coddel;
		this.codcli = codcli;
		this.ejedoc = ejedoc;
		this.numdoc = numdoc;
		this.tipalb = tipalb;
		this.seralb = seralb;
		this.ejerci = ejerci;
		this.numalb = numalb;
		this.numlin = numlin;
		this.codart = codart;
		this.descri = descri;
		this.ctlser = ctlser;
		this.cantid = cantid;
		this.bultos = bultos;
		this.kilos = kilos;
		this.volume = volume;
		this.palets = palets;
		this.horizo = horizo;
		this.vertic = vertic;
		this.fcaduc = fcaduc;
		this.lotefb = lotefb;
		this.nserie = nserie;
		this.indica = indica;
		this.canmov = canmov;
		this.ctlcad = ctlcad;
		this.ctllot = ctllot;
	}

	public short getCodemp() {
		return this.codemp;
	}

	public void setCodemp(short codemp) {
		this.codemp = codemp;
	}

	public short getCoddel() {
		return this.coddel;
	}

	public void setCoddel(short coddel) {
		this.coddel = coddel;
	}

	public short getCodcli() {
		return this.codcli;
	}

	public void setCodcli(short codcli) {
		this.codcli = codcli;
	}

	public Short getEjedoc() {
		return this.ejedoc;
	}

	public void setEjedoc(Short ejedoc) {
		this.ejedoc = ejedoc;
	}

	public Integer getNumdoc() {
		return this.numdoc;
	}

	public void setNumdoc(Integer numdoc) {
		this.numdoc = numdoc;
	}

	public char getTipalb() {
		return this.tipalb;
	}

	public void setTipalb(char tipalb) {
		this.tipalb = tipalb;
	}

	public String getSeralb() {
		return this.seralb;
	}

	public void setSeralb(String seralb) {
		this.seralb = seralb;
	}

	public short getEjerci() {
		return this.ejerci;
	}

	public void setEjerci(short ejerci) {
		this.ejerci = ejerci;
	}

	public int getNumalb() {
		return this.numalb;
	}

	public void setNumalb(int numalb) {
		this.numalb = numalb;
	}

	public short getNumlin() {
		return this.numlin;
	}

	public void setNumlin(short numlin) {
		this.numlin = numlin;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public Character getCtlser() {
		return this.ctlser;
	}

	public void setCtlser(Character ctlser) {
		this.ctlser = ctlser;
	}

	public BigDecimal getCantid() {
		return this.cantid;
	}

	public void setCantid(BigDecimal cantid) {
		this.cantid = cantid;
	}

	public short getBultos() {
		return this.bultos;
	}

	public void setBultos(short bultos) {
		this.bultos = bultos;
	}

	public BigDecimal getKilos() {
		return this.kilos;
	}

	public void setKilos(BigDecimal kilos) {
		this.kilos = kilos;
	}

	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	public Short getPalets() {
		return this.palets;
	}

	public void setPalets(Short palets) {
		this.palets = palets;
	}

	public String getHorizo() {
		return this.horizo;
	}

	public void setHorizo(String horizo) {
		this.horizo = horizo;
	}

	public Short getVertic() {
		return this.vertic;
	}

	public void setVertic(Short vertic) {
		this.vertic = vertic;
	}

	public Date getFcaduc() {
		return this.fcaduc;
	}

	public void setFcaduc(Date fcaduc) {
		this.fcaduc = fcaduc;
	}

	public String getLotefb() {
		return this.lotefb;
	}

	public void setLotefb(String lotefb) {
		this.lotefb = lotefb;
	}

	public String getNserie() {
		return this.nserie;
	}

	public void setNserie(String nserie) {
		this.nserie = nserie;
	}

	public Character getIndica() {
		return this.indica;
	}

	public void setIndica(Character indica) {
		this.indica = indica;
	}

	public BigDecimal getCanmov() {
		return this.canmov;
	}

	public void setCanmov(BigDecimal canmov) {
		this.canmov = canmov;
	}

	public Character getCtlcad() {
		return this.ctlcad;
	}

	public void setCtlcad(Character ctlcad) {
		this.ctlcad = ctlcad;
	}

	public Character getCtllot() {
		return this.ctllot;
	}

	public void setCtllot(Character ctllot) {
		this.ctllot = ctllot;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZonaswkaId))
			return false;
		ZonaswkaId castOther = (ZonaswkaId) other;

		return (this.getCodemp() == castOther.getCodemp()) && (this.getCoddel() == castOther.getCoddel())
				&& (this.getCodcli() == castOther.getCodcli())
				&& ((this.getEjedoc() == castOther.getEjedoc()) || (this.getEjedoc() != null
						&& castOther.getEjedoc() != null && this.getEjedoc().equals(castOther.getEjedoc())))
				&& ((this.getNumdoc() == castOther.getNumdoc()) || (this.getNumdoc() != null
						&& castOther.getNumdoc() != null && this.getNumdoc().equals(castOther.getNumdoc())))
				&& (this.getTipalb() == castOther.getTipalb())
				&& ((this.getSeralb() == castOther.getSeralb()) || (this.getSeralb() != null
						&& castOther.getSeralb() != null && this.getSeralb().equals(castOther.getSeralb())))
				&& (this.getEjerci() == castOther.getEjerci()) && (this.getNumalb() == castOther.getNumalb())
				&& (this.getNumlin() == castOther.getNumlin())
				&& ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
						&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())))
				&& ((this.getDescri() == castOther.getDescri()) || (this.getDescri() != null
						&& castOther.getDescri() != null && this.getDescri().equals(castOther.getDescri())))
				&& ((this.getCtlser() == castOther.getCtlser()) || (this.getCtlser() != null
						&& castOther.getCtlser() != null && this.getCtlser().equals(castOther.getCtlser())))
				&& ((this.getCantid() == castOther.getCantid()) || (this.getCantid() != null
						&& castOther.getCantid() != null && this.getCantid().equals(castOther.getCantid())))
				&& (this.getBultos() == castOther.getBultos())
				&& ((this.getKilos() == castOther.getKilos()) || (this.getKilos() != null
						&& castOther.getKilos() != null && this.getKilos().equals(castOther.getKilos())))
				&& ((this.getVolume() == castOther.getVolume()) || (this.getVolume() != null
						&& castOther.getVolume() != null && this.getVolume().equals(castOther.getVolume())))
				&& ((this.getPalets() == castOther.getPalets()) || (this.getPalets() != null
						&& castOther.getPalets() != null && this.getPalets().equals(castOther.getPalets())))
				&& ((this.getHorizo() == castOther.getHorizo()) || (this.getHorizo() != null
						&& castOther.getHorizo() != null && this.getHorizo().equals(castOther.getHorizo())))
				&& ((this.getVertic() == castOther.getVertic()) || (this.getVertic() != null
						&& castOther.getVertic() != null && this.getVertic().equals(castOther.getVertic())))
				&& ((this.getFcaduc() == castOther.getFcaduc()) || (this.getFcaduc() != null
						&& castOther.getFcaduc() != null && this.getFcaduc().equals(castOther.getFcaduc())))
				&& ((this.getLotefb() == castOther.getLotefb()) || (this.getLotefb() != null
						&& castOther.getLotefb() != null && this.getLotefb().equals(castOther.getLotefb())))
				&& ((this.getNserie() == castOther.getNserie()) || (this.getNserie() != null
						&& castOther.getNserie() != null && this.getNserie().equals(castOther.getNserie())))
				&& ((this.getIndica() == castOther.getIndica()) || (this.getIndica() != null
						&& castOther.getIndica() != null && this.getIndica().equals(castOther.getIndica())))
				&& ((this.getCanmov() == castOther.getCanmov()) || (this.getCanmov() != null
						&& castOther.getCanmov() != null && this.getCanmov().equals(castOther.getCanmov())))
				&& ((this.getCtlcad() == castOther.getCtlcad()) || (this.getCtlcad() != null
						&& castOther.getCtlcad() != null && this.getCtlcad().equals(castOther.getCtlcad())))
				&& ((this.getCtllot() == castOther.getCtllot()) || (this.getCtllot() != null
						&& castOther.getCtllot() != null && this.getCtllot().equals(castOther.getCtllot())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCoddel();
		result = 37 * result + this.getCodcli();
		result = 37 * result + (getEjedoc() == null ? 0 : this.getEjedoc().hashCode());
		result = 37 * result + (getNumdoc() == null ? 0 : this.getNumdoc().hashCode());
		result = 37 * result + this.getTipalb();
		result = 37 * result + (getSeralb() == null ? 0 : this.getSeralb().hashCode());
		result = 37 * result + this.getEjerci();
		result = 37 * result + this.getNumalb();
		result = 37 * result + this.getNumlin();
		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		result = 37 * result + (getDescri() == null ? 0 : this.getDescri().hashCode());
		result = 37 * result + (getCtlser() == null ? 0 : this.getCtlser().hashCode());
		result = 37 * result + (getCantid() == null ? 0 : this.getCantid().hashCode());
		result = 37 * result + this.getBultos();
		result = 37 * result + (getKilos() == null ? 0 : this.getKilos().hashCode());
		result = 37 * result + (getVolume() == null ? 0 : this.getVolume().hashCode());
		result = 37 * result + (getPalets() == null ? 0 : this.getPalets().hashCode());
		result = 37 * result + (getHorizo() == null ? 0 : this.getHorizo().hashCode());
		result = 37 * result + (getVertic() == null ? 0 : this.getVertic().hashCode());
		result = 37 * result + (getFcaduc() == null ? 0 : this.getFcaduc().hashCode());
		result = 37 * result + (getLotefb() == null ? 0 : this.getLotefb().hashCode());
		result = 37 * result + (getNserie() == null ? 0 : this.getNserie().hashCode());
		result = 37 * result + (getIndica() == null ? 0 : this.getIndica().hashCode());
		result = 37 * result + (getCanmov() == null ? 0 : this.getCanmov().hashCode());
		result = 37 * result + (getCtlcad() == null ? 0 : this.getCtlcad().hashCode());
		result = 37 * result + (getCtllot() == null ? 0 : this.getCtllot().hashCode());
		return result;
	}

}
