package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Zonaswka generated by hbm2java
 */
public class Zonaswka implements java.io.Serializable {

	private ZonaswkaId id;

	public Zonaswka() {
	}

	public Zonaswka(ZonaswkaId id) {
		this.id = id;
	}

	public ZonaswkaId getId() {
		return this.id;
	}

	public void setId(ZonaswkaId id) {
		this.id = id;
	}

}
