package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * Zonaslib generated by hbm2java
 */
public class Zonaslib implements java.io.Serializable {

	private ZonaslibId id;

	public Zonaslib() {
	}

	public Zonaslib(ZonaslibId id) {
		this.id = id;
	}

	public ZonaslibId getId() {
		return this.id;
	}

	public void setId(ZonaslibId id) {
		this.id = id;
	}

}
