package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ZonDesId generated by hbm2java
 */
public class ZonDesId implements java.io.Serializable {

	private Integer norden;
	private Integer cantid;
	private BigDecimal udsalm;
	private String horizo;
	private Short vertic;
	private int sublin;

	public ZonDesId() {
	}

	public ZonDesId(int sublin) {
		this.sublin = sublin;
	}

	public ZonDesId(Integer norden, Integer cantid, BigDecimal udsalm, String horizo, Short vertic, int sublin) {
		this.norden = norden;
		this.cantid = cantid;
		this.udsalm = udsalm;
		this.horizo = horizo;
		this.vertic = vertic;
		this.sublin = sublin;
	}

	public Integer getNorden() {
		return this.norden;
	}

	public void setNorden(Integer norden) {
		this.norden = norden;
	}

	public Integer getCantid() {
		return this.cantid;
	}

	public void setCantid(Integer cantid) {
		this.cantid = cantid;
	}

	public BigDecimal getUdsalm() {
		return this.udsalm;
	}

	public void setUdsalm(BigDecimal udsalm) {
		this.udsalm = udsalm;
	}

	public String getHorizo() {
		return this.horizo;
	}

	public void setHorizo(String horizo) {
		this.horizo = horizo;
	}

	public Short getVertic() {
		return this.vertic;
	}

	public void setVertic(Short vertic) {
		this.vertic = vertic;
	}

	public int getSublin() {
		return this.sublin;
	}

	public void setSublin(int sublin) {
		this.sublin = sublin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZonDesId))
			return false;
		ZonDesId castOther = (ZonDesId) other;

		return ((this.getNorden() == castOther.getNorden()) || (this.getNorden() != null
				&& castOther.getNorden() != null && this.getNorden().equals(castOther.getNorden())))
				&& ((this.getCantid() == castOther.getCantid()) || (this.getCantid() != null
						&& castOther.getCantid() != null && this.getCantid().equals(castOther.getCantid())))
				&& ((this.getUdsalm() == castOther.getUdsalm()) || (this.getUdsalm() != null
						&& castOther.getUdsalm() != null && this.getUdsalm().equals(castOther.getUdsalm())))
				&& ((this.getHorizo() == castOther.getHorizo()) || (this.getHorizo() != null
						&& castOther.getHorizo() != null && this.getHorizo().equals(castOther.getHorizo())))
				&& ((this.getVertic() == castOther.getVertic()) || (this.getVertic() != null
						&& castOther.getVertic() != null && this.getVertic().equals(castOther.getVertic())))
				&& (this.getSublin() == castOther.getSublin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNorden() == null ? 0 : this.getNorden().hashCode());
		result = 37 * result + (getCantid() == null ? 0 : this.getCantid().hashCode());
		result = 37 * result + (getUdsalm() == null ? 0 : this.getUdsalm().hashCode());
		result = 37 * result + (getHorizo() == null ? 0 : this.getHorizo().hashCode());
		result = 37 * result + (getVertic() == null ? 0 : this.getVertic().hashCode());
		result = 37 * result + this.getSublin();
		return result;
	}

}
