package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * ZonDes generated by hbm2java
 */
public class ZonDes implements java.io.Serializable {

	private ZonDesId id;

	public ZonDes() {
	}

	public ZonDes(ZonDesId id) {
		this.id = id;
	}

	public ZonDesId getId() {
		return this.id;
	}

	public void setId(ZonDesId id) {
		this.id = id;
	}

}
