package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ZonOriId generated by hbm2java
 */
public class ZonOriId implements java.io.Serializable {

	private String horizo;
	private Short vertic;
	private String codart;
	private String lotefb;
	private Date fcaduc;
	private Integer cantid;
	private BigDecimal udsalm;
	private int norden;

	public ZonOriId() {
	}

	public ZonOriId(int norden) {
		this.norden = norden;
	}

	public ZonOriId(String horizo, Short vertic, String codart, String lotefb, Date fcaduc, Integer cantid,
			BigDecimal udsalm, int norden) {
		this.horizo = horizo;
		this.vertic = vertic;
		this.codart = codart;
		this.lotefb = lotefb;
		this.fcaduc = fcaduc;
		this.cantid = cantid;
		this.udsalm = udsalm;
		this.norden = norden;
	}

	public String getHorizo() {
		return this.horizo;
	}

	public void setHorizo(String horizo) {
		this.horizo = horizo;
	}

	public Short getVertic() {
		return this.vertic;
	}

	public void setVertic(Short vertic) {
		this.vertic = vertic;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public String getLotefb() {
		return this.lotefb;
	}

	public void setLotefb(String lotefb) {
		this.lotefb = lotefb;
	}

	public Date getFcaduc() {
		return this.fcaduc;
	}

	public void setFcaduc(Date fcaduc) {
		this.fcaduc = fcaduc;
	}

	public Integer getCantid() {
		return this.cantid;
	}

	public void setCantid(Integer cantid) {
		this.cantid = cantid;
	}

	public BigDecimal getUdsalm() {
		return this.udsalm;
	}

	public void setUdsalm(BigDecimal udsalm) {
		this.udsalm = udsalm;
	}

	public int getNorden() {
		return this.norden;
	}

	public void setNorden(int norden) {
		this.norden = norden;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZonOriId))
			return false;
		ZonOriId castOther = (ZonOriId) other;

		return ((this.getHorizo() == castOther.getHorizo()) || (this.getHorizo() != null
				&& castOther.getHorizo() != null && this.getHorizo().equals(castOther.getHorizo())))
				&& ((this.getVertic() == castOther.getVertic()) || (this.getVertic() != null
						&& castOther.getVertic() != null && this.getVertic().equals(castOther.getVertic())))
				&& ((this.getCodart() == castOther.getCodart()) || (this.getCodart() != null
						&& castOther.getCodart() != null && this.getCodart().equals(castOther.getCodart())))
				&& ((this.getLotefb() == castOther.getLotefb()) || (this.getLotefb() != null
						&& castOther.getLotefb() != null && this.getLotefb().equals(castOther.getLotefb())))
				&& ((this.getFcaduc() == castOther.getFcaduc()) || (this.getFcaduc() != null
						&& castOther.getFcaduc() != null && this.getFcaduc().equals(castOther.getFcaduc())))
				&& ((this.getCantid() == castOther.getCantid()) || (this.getCantid() != null
						&& castOther.getCantid() != null && this.getCantid().equals(castOther.getCantid())))
				&& ((this.getUdsalm() == castOther.getUdsalm()) || (this.getUdsalm() != null
						&& castOther.getUdsalm() != null && this.getUdsalm().equals(castOther.getUdsalm())))
				&& (this.getNorden() == castOther.getNorden());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHorizo() == null ? 0 : this.getHorizo().hashCode());
		result = 37 * result + (getVertic() == null ? 0 : this.getVertic().hashCode());
		result = 37 * result + (getCodart() == null ? 0 : this.getCodart().hashCode());
		result = 37 * result + (getLotefb() == null ? 0 : this.getLotefb().hashCode());
		result = 37 * result + (getFcaduc() == null ? 0 : this.getFcaduc().hashCode());
		result = 37 * result + (getCantid() == null ? 0 : this.getCantid().hashCode());
		result = 37 * result + (getUdsalm() == null ? 0 : this.getUdsalm().hashCode());
		result = 37 * result + this.getNorden();
		return result;
	}

}
