package models;
// Generated 23-feb-2016 11:32:03 by Hibernate Tools 3.4.0.CR1

/**
 * ZonOri generated by hbm2java
 */
public class ZonOri implements java.io.Serializable {

	private ZonOriId id;

	public ZonOri() {
	}

	public ZonOri(ZonOriId id) {
		this.id = id;
	}

	public ZonOriId getId() {
		return this.id;
	}

	public void setId(ZonOriId id) {
		this.id = id;
	}

}
